/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GetAnalyticBookkeepingResponse,
    GetAnalyticBookkeepingResponseFromJSON,
    GetAnalyticBookkeepingResponseToJSON,
    GetAnalyticByPlatformResponse,
    GetAnalyticByPlatformResponseFromJSON,
    GetAnalyticByPlatformResponseToJSON,
    GetAnalyticDashboardResponse,
    GetAnalyticDashboardResponseFromJSON,
    GetAnalyticDashboardResponseToJSON,
    GetAnalyticItemResponse,
    GetAnalyticItemResponseFromJSON,
    GetAnalyticItemResponseToJSON,
    GetAnalyticSummaryResponse,
    GetAnalyticSummaryResponseFromJSON,
    GetAnalyticSummaryResponseToJSON,
    GetAnalyticTimeseryResponse,
    GetAnalyticTimeseryResponseFromJSON,
    GetAnalyticTimeseryResponseToJSON,
    GetAnalyticTodayResponse,
    GetAnalyticTodayResponseFromJSON,
    GetAnalyticTodayResponseToJSON,
    V1List,
    V1ListFromJSON,
    V1ListToJSON,
} from '../models';

export interface GetAnalyticSummaryRequest {
    days?: number;
}

/**
 * 
 */
export class AnalyticsApi extends runtime.BaseAPI {

    /**
     * Monthly P&L + per-platform breakdown for a calendar year.
     */
    async getAnalyticBookkeepingRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetAnalyticBookkeepingResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/analytics/bookkeeping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticBookkeepingResponseFromJSON(jsonValue));
    }

    /**
     * Monthly P&L + per-platform breakdown for a calendar year.
     */
    async getAnalyticBookkeeping(initOverrides?: RequestInit): Promise<GetAnalyticBookkeepingResponse> {
        const response = await this.getAnalyticBookkeepingRaw(initOverrides);
        return await response.value();
    }

    /**
     * Sales + revenue grouped by platform for the last N days.
     */
    async getAnalyticByPlatformRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetAnalyticByPlatformResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/analytics/by-platform`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticByPlatformResponseFromJSON(jsonValue));
    }

    /**
     * Sales + revenue grouped by platform for the last N days.
     */
    async getAnalyticByPlatform(initOverrides?: RequestInit): Promise<GetAnalyticByPlatformResponse> {
        const response = await this.getAnalyticByPlatformRaw(initOverrides);
        return await response.value();
    }

    /**
     * Composite dashboard: KPIs + breakdowns + recent activity.
     */
    async getAnalyticDashboardRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetAnalyticDashboardResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/analytics/dashboard`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticDashboardResponseFromJSON(jsonValue));
    }

    /**
     * Composite dashboard: KPIs + breakdowns + recent activity.
     */
    async getAnalyticDashboard(initOverrides?: RequestInit): Promise<GetAnalyticDashboardResponse> {
        const response = await this.getAnalyticDashboardRaw(initOverrides);
        return await response.value();
    }

    /**
     * Per-item P&L for sold inventory.
     */
    async getAnalyticItemRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetAnalyticItemResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/analytics/items`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticItemResponseFromJSON(jsonValue));
    }

    /**
     * Per-item P&L for sold inventory.
     */
    async getAnalyticItem(initOverrides?: RequestInit): Promise<GetAnalyticItemResponse> {
        const response = await this.getAnalyticItemRaw(initOverrides);
        return await response.value();
    }

    /**
     * Headline KPIs for the last N days.
     */
    async getAnalyticSummaryRaw(requestParameters: GetAnalyticSummaryRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetAnalyticSummaryResponse>> {
        const queryParameters: any = {};

        if (requestParameters.days !== undefined) {
            queryParameters['days'] = requestParameters.days;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/analytics/summary`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticSummaryResponseFromJSON(jsonValue));
    }

    /**
     * Headline KPIs for the last N days.
     */
    async getAnalyticSummary(requestParameters: GetAnalyticSummaryRequest = {}, initOverrides?: RequestInit): Promise<GetAnalyticSummaryResponse> {
        const response = await this.getAnalyticSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Daily sales + revenue series for the last N days.
     */
    async getAnalyticTimeseryRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetAnalyticTimeseryResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/analytics/timeseries`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticTimeseryResponseFromJSON(jsonValue));
    }

    /**
     * Daily sales + revenue series for the last N days.
     */
    async getAnalyticTimesery(initOverrides?: RequestInit): Promise<GetAnalyticTimeseryResponse> {
        const response = await this.getAnalyticTimeseryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Today\'s checklist + 14-day activity streak.
     */
    async getAnalyticTodayRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetAnalyticTodayResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/analytics/today`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAnalyticTodayResponseFromJSON(jsonValue));
    }

    /**
     * Today\'s checklist + 14-day activity streak.
     */
    async getAnalyticToday(initOverrides?: RequestInit): Promise<GetAnalyticTodayResponse> {
        const response = await this.getAnalyticTodayRaw(initOverrides);
        return await response.value();
    }

    /**
     * Platform velocity + margin insight (90-day window).
     */
    async listInsightByPlatformRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/insights/by-platform`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * Platform velocity + margin insight (90-day window).
     */
    async listInsightByPlatform(initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listInsightByPlatformRaw(initOverrides);
        return await response.value();
    }

}
