/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateBillingUpgradeResponse,
    CreateBillingUpgradeResponseFromJSON,
    CreateBillingUpgradeResponseToJSON,
    InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models';

export interface CreateBillingUpgradeRequest {
    inlineObject: InlineObject;
}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI {

    /**
     * Returns a Stripe Checkout URL. Nothing is charged by this call — a person completes the payment. Downgrades and cancellation are not available to a token at all; they stay with the account owner.
     * Start an upgrade to a higher plan.
     */
    async createBillingUpgradeRaw(requestParameters: CreateBillingUpgradeRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateBillingUpgradeResponse>> {
        if (requestParameters.inlineObject === null || requestParameters.inlineObject === undefined) {
            throw new runtime.RequiredError('inlineObject','Required parameter requestParameters.inlineObject was null or undefined when calling createBillingUpgrade.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/billing/upgrade`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObjectToJSON(requestParameters.inlineObject),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBillingUpgradeResponseFromJSON(jsonValue));
    }

    /**
     * Returns a Stripe Checkout URL. Nothing is charged by this call — a person completes the payment. Downgrades and cancellation are not available to a token at all; they stay with the account owner.
     * Start an upgrade to a higher plan.
     */
    async createBillingUpgrade(requestParameters: CreateBillingUpgradeRequest, initOverrides?: RequestInit): Promise<CreateBillingUpgradeResponse> {
        const response = await this.createBillingUpgradeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
