/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateNetworkPoolResponse,
    CreateNetworkPoolResponseFromJSON,
    CreateNetworkPoolResponseToJSON,
    DeleteNetworkPoolResponse,
    DeleteNetworkPoolResponseFromJSON,
    DeleteNetworkPoolResponseToJSON,
    GetNetworkPoolResponse,
    GetNetworkPoolResponseFromJSON,
    GetNetworkPoolResponseToJSON,
    GetNetworkPoolSizeResponse,
    GetNetworkPoolSizeResponseFromJSON,
    GetNetworkPoolSizeResponseToJSON,
    UpdateNetworkPoolResponse,
    UpdateNetworkPoolResponseFromJSON,
    UpdateNetworkPoolResponseToJSON,
    V1List,
    V1ListFromJSON,
    V1ListToJSON,
} from '../models';

export interface ListNetworkPoolLogRequest {
    limit?: number;
}

/**
 * 
 */
export class NetworkApi extends runtime.BaseAPI {

    /**
     * Join the Crossly Network reciprocal engagement pool.
     */
    async createNetworkPoolRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateNetworkPoolResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/network/pool`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateNetworkPoolResponseFromJSON(jsonValue));
    }

    /**
     * Join the Crossly Network reciprocal engagement pool.
     */
    async createNetworkPool(initOverrides?: RequestInit): Promise<CreateNetworkPoolResponse> {
        const response = await this.createNetworkPoolRaw(initOverrides);
        return await response.value();
    }

    /**
     * Leave the Crossly Network pool.
     */
    async deleteNetworkPoolRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<DeleteNetworkPoolResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/network/pool`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteNetworkPoolResponseFromJSON(jsonValue));
    }

    /**
     * Leave the Crossly Network pool.
     */
    async deleteNetworkPool(initOverrides?: RequestInit): Promise<DeleteNetworkPoolResponse> {
        const response = await this.deleteNetworkPoolRaw(initOverrides);
        return await response.value();
    }

    /**
     * The seller\'s Crossly Network pool membership row.
     */
    async getNetworkPoolRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetNetworkPoolResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/network/pool`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNetworkPoolResponseFromJSON(jsonValue));
    }

    /**
     * The seller\'s Crossly Network pool membership row.
     */
    async getNetworkPool(initOverrides?: RequestInit): Promise<GetNetworkPoolResponse> {
        const response = await this.getNetworkPoolRaw(initOverrides);
        return await response.value();
    }

    /**
     * Total members in the Crossly Network pool.
     */
    async getNetworkPoolSizeRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetNetworkPoolSizeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/network/pool/size`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetNetworkPoolSizeResponseFromJSON(jsonValue));
    }

    /**
     * Total members in the Crossly Network pool.
     */
    async getNetworkPoolSize(initOverrides?: RequestInit): Promise<GetNetworkPoolSizeResponse> {
        const response = await this.getNetworkPoolSizeRaw(initOverrides);
        return await response.value();
    }

    /**
     * Recent engagement history — both sent and received.
     */
    async listNetworkPoolLogRaw(requestParameters: ListNetworkPoolLogRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        const queryParameters: any = {};

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/network/pool/log`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * Recent engagement history — both sent and received.
     */
    async listNetworkPoolLog(requestParameters: ListNetworkPoolLogRequest = {}, initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listNetworkPoolLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update per-action toggles + platforms on pool membership.
     */
    async updateNetworkPoolRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<UpdateNetworkPoolResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/network/pool`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateNetworkPoolResponseFromJSON(jsonValue));
    }

    /**
     * Update per-action toggles + platforms on pool membership.
     */
    async updateNetworkPool(initOverrides?: RequestInit): Promise<UpdateNetworkPoolResponse> {
        const response = await this.updateNetworkPoolRaw(initOverrides);
        return await response.value();
    }

}
