/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateOfferRespondResponse,
    CreateOfferRespondResponseFromJSON,
    CreateOfferRespondResponseToJSON,
    GetOfferResponse,
    GetOfferResponseFromJSON,
    GetOfferResponseToJSON,
    InlineObject2,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
} from '../models';

export interface CreateOfferRespondRequest {
    id: string;
    inlineObject2: InlineObject2;
}

export interface GetOfferRequest {
    status?: GetOfferStatusEnum;
    limit?: number;
}

/**
 * 
 */
export class OffersApi extends runtime.BaseAPI {

    /**
     * Accept, decline, or counter a buyer offer on a Crossly marketplace listing.
     */
    async createOfferRespondRaw(requestParameters: CreateOfferRespondRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateOfferRespondResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling createOfferRespond.');
        }

        if (requestParameters.inlineObject2 === null || requestParameters.inlineObject2 === undefined) {
            throw new runtime.RequiredError('inlineObject2','Required parameter requestParameters.inlineObject2 was null or undefined when calling createOfferRespond.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/offers/{id}/respond`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject2ToJSON(requestParameters.inlineObject2),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateOfferRespondResponseFromJSON(jsonValue));
    }

    /**
     * Accept, decline, or counter a buyer offer on a Crossly marketplace listing.
     */
    async createOfferRespond(requestParameters: CreateOfferRespondRequest, initOverrides?: RequestInit): Promise<CreateOfferRespondResponse> {
        const response = await this.createOfferRespondRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List buyer offers on your Crossly marketplace listings, including bundles.
     */
    async getOfferRaw(requestParameters: GetOfferRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetOfferResponse>> {
        const queryParameters: any = {};

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/offers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetOfferResponseFromJSON(jsonValue));
    }

    /**
     * List buyer offers on your Crossly marketplace listings, including bundles.
     */
    async getOffer(requestParameters: GetOfferRequest = {}, initOverrides?: RequestInit): Promise<GetOfferResponse> {
        const response = await this.getOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum GetOfferStatusEnum {
    Pending = 'pending',
    Accepted = 'accepted',
    Declined = 'declined',
    Countered = 'countered',
    Expired = 'expired',
    Withdrawn = 'withdrawn'
}
