/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    UpdateMeResponse,
    UpdateMeResponseFromJSON,
    UpdateMeResponseToJSON,
} from '../models';

/**
 * 
 */
export class ProfileApi extends runtime.BaseAPI {

    /**
     * Update the authenticated user\'s profile (display name, etc).
     */
    async updateMeRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<UpdateMeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/me`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateMeResponseFromJSON(jsonValue));
    }

    /**
     * Update the authenticated user\'s profile (display name, etc).
     */
    async updateMe(initOverrides?: RequestInit): Promise<UpdateMeResponse> {
        const response = await this.updateMeRaw(initOverrides);
        return await response.value();
    }

}
