/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    GetBrandResponse,
    GetBrandResponseFromJSON,
    GetBrandResponseToJSON,
    GetCategoryResponse,
    GetCategoryResponseFromJSON,
    GetCategoryResponseToJSON,
    GetDepartmentResponse,
    GetDepartmentResponseFromJSON,
    GetDepartmentResponseToJSON,
    GetGenderResponse,
    GetGenderResponseFromJSON,
    GetGenderResponseToJSON,
    GetPatternResponse,
    GetPatternResponseFromJSON,
    GetPatternResponseToJSON,
    GetSizeSystemResponse,
    GetSizeSystemResponseFromJSON,
    GetSizeSystemResponseToJSON,
    GetStyleResponse,
    GetStyleResponseFromJSON,
    GetStyleResponseToJSON,
    GetTypeResponse,
    GetTypeResponseFromJSON,
    GetTypeResponseToJSON,
} from '../models';

/**
 * 
 */
export class ReferenceApi extends runtime.BaseAPI {

    /**
     * Search the Crossly brand index. Returns up to 50 matches.
     */
    async getBrandRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetBrandResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/brands`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBrandResponseFromJSON(jsonValue));
    }

    /**
     * Search the Crossly brand index. Returns up to 50 matches.
     */
    async getBrand(initOverrides?: RequestInit): Promise<GetBrandResponse> {
        const response = await this.getBrandRaw(initOverrides);
        return await response.value();
    }

    /**
     * List Crossly\'s canonical category tree.
     */
    async getCategoryRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetCategoryResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/categories`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetCategoryResponseFromJSON(jsonValue));
    }

    /**
     * List Crossly\'s canonical category tree.
     */
    async getCategory(initOverrides?: RequestInit): Promise<GetCategoryResponse> {
        const response = await this.getCategoryRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search the eBay-sourced \"Department\" item-specific values.
     */
    async getDepartmentRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetDepartmentResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/departments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDepartmentResponseFromJSON(jsonValue));
    }

    /**
     * Search the eBay-sourced \"Department\" item-specific values.
     */
    async getDepartment(initOverrides?: RequestInit): Promise<GetDepartmentResponse> {
        const response = await this.getDepartmentRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search the eBay-sourced \"Gender\" item-specific values.
     */
    async getGenderRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetGenderResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/genders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetGenderResponseFromJSON(jsonValue));
    }

    /**
     * Search the eBay-sourced \"Gender\" item-specific values.
     */
    async getGender(initOverrides?: RequestInit): Promise<GetGenderResponse> {
        const response = await this.getGenderRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search the eBay-sourced \"Pattern\" item-specific values.
     */
    async getPatternRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetPatternResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/patterns`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetPatternResponseFromJSON(jsonValue));
    }

    /**
     * Search the eBay-sourced \"Pattern\" item-specific values.
     */
    async getPattern(initOverrides?: RequestInit): Promise<GetPatternResponse> {
        const response = await this.getPatternRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search the Poshmark + Vestiaire size-system union (US/UK/EU/AU/FR/KR).
     */
    async getSizeSystemRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetSizeSystemResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/size-systems`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSizeSystemResponseFromJSON(jsonValue));
    }

    /**
     * Search the Poshmark + Vestiaire size-system union (US/UK/EU/AU/FR/KR).
     */
    async getSizeSystem(initOverrides?: RequestInit): Promise<GetSizeSystemResponse> {
        const response = await this.getSizeSystemRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search the eBay-sourced \"Style\" item-specific values.
     */
    async getStyleRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetStyleResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/styles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetStyleResponseFromJSON(jsonValue));
    }

    /**
     * Search the eBay-sourced \"Style\" item-specific values.
     */
    async getStyle(initOverrides?: RequestInit): Promise<GetStyleResponse> {
        const response = await this.getStyleRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search the eBay-sourced \"Type\" item-specific values.
     */
    async getTypeRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetTypeResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("PersonalAccessToken", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/types`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTypeResponseFromJSON(jsonValue));
    }

    /**
     * Search the eBay-sourced \"Type\" item-specific values.
     */
    async getType(initOverrides?: RequestInit): Promise<GetTypeResponse> {
        const response = await this.getTypeRaw(initOverrides);
        return await response.value();
    }

}
