/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ListListingsItemGrading,
    ListListingsItemGradingFromJSON,
    ListListingsItemGradingFromJSONTyped,
    ListListingsItemGradingToJSON,
} from './ListListingsItemGrading';

/**
 * 
 * @export
 * @interface CreateListingByIdResponseItems
 */
export interface CreateListingByIdResponseItems {
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveTitle: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    effectivePrice?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveDescription?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveImages: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveBrand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveCondition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveSize?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveSku?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveColor: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    effectiveTags: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof CreateListingByIdResponseItems
     */
    platformListings: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    inventoryItemId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    descriptionHtml?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    price?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    images?: Array<string> | null;
    /**
     * Optional single product video (R2/CDN URL). Shown on the Crossly buyer page.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    videoUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    condition?: string | null;
    /**
     * Third-party grading, when the item is slabbed. Migration 0277.
     * 
     * Separate from `condition` on purpose and never derived from it: a grade
     * is a claim about what a GRADING COMPANY certified, and inferring "PSA 10"
     * from a coarse condition would be a false authenticity claim. It is also
     * never filled from our own AI estimate (`bulk_market_items.grade`), which
     * carries an explicit "not a professional grade" disclaimer.
     * 
     * `gradeKey` is the canonical form from `gradeKey()` in
     * shared/constants/graders.ts; `grading` holds the full GradingInfo
     * including the cert number and whether a cert lookup verified it.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    gradeKey?: string | null;
    /**
     * 
     * @type {ListListingsItemGrading}
     * @memberof CreateListingByIdResponseItems
     */
    grading?: ListListingsItemGrading | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    brand?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    size?: string | null;
    /**
     * Migration 0179 — see the matching fields on inventory_items above.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    material?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    style?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    pattern?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    department?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    gender?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    itemType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    sizeSystem?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    color: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    sku?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateListingByIdResponseItems
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof CreateListingByIdResponseItems
     */
    quantityAvailable: number;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    weightLb?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    weightOz?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    dimensionLIn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    dimensionWIn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    dimensionHIn?: string | null;
    /**
     * Scheduled go-live time. When set on a draft, the listing-scheduler
     * worker waits until this passes then dispatches the crosspost to
     * scheduledPlatforms and flips status from 'draft' to 'active'.
     * @type {Date}
     * @memberof CreateListingByIdResponseItems
     */
    publishAt?: Date | null;
    /**
     * Which platforms to publish to when publishAt fires. JSON array of
     * platform ids. Null/empty = scheduler skips (listing won't auto-
     * publish, even after publishAt — gives the seller an escape hatch).
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    scheduledPlatforms?: Array<string> | null;
    /**
     * Parent listing when this row is a CHILD in a listing chain. Null =
     * standalone. What being a child means depends on the parent's
     * `groupKind` — see it.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    parentListingId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateListingByIdResponseItems
     */
    isBundle: boolean;
    /**
     * Per-listing automation overrides. See migration 0098.
     * 
     *  automationAssignedRuleIds  — force-include for these rules
     *  automationBlockedRuleIds   — exempt from these rules
     *  automationAssignedChainIds — force-include for these workflow chains
     *  automationBlockedChainIds  — exempt from these workflow chains
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    automationAssignedRuleIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    automationBlockedRuleIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    automationAssignedChainIds: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateListingByIdResponseItems
     */
    automationBlockedChainIds: Array<string>;
    /**
     * Harmonised System customs code — international shipping declarations.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    hsCode?: string | null;
    /**
     * Customs country of origin. Distinct from the seller's location.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    countryOfOrigin?: string | null;
    /**
     * Never let a repricing rule go below this. On the ITEM because it is a
     * fact about the thing owned, not about any one rule — "this jacket never
     * goes below $45" should apply to every rule, and before this it was
     * expressible only as one rule per jacket. Listings inherit when null.
     * @type {number}
     * @memberof CreateListingByIdResponseItems
     */
    priceFloorCents?: number | null;
    /**
     * When true the floor is a TAKE-HOME target, converted to a per-platform
     * gross at reprice time. A gross floor is four different promises across
     * four platforms; this is the one number a seller actually cares about.
     * @type {boolean}
     * @memberof CreateListingByIdResponseItems
     */
    floorIsNet: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CreateListingByIdResponseItems
     */
    delistedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateListingByIdResponseItems
     */
    soldAt?: Date | null;
    /**
     * Mirrors inventory_items.source. 'manual' for every seller-created
     * listing; external-stub.ts sets 'external_sale' on the synthetic
     * listing it fabricates for a sale detected on a platform id Crossly
     * never listed — those rows have no real photos/description of their
     * own (everything is lifted from the platform's sale payload) and are
     * otherwise indistinguishable from a real listing in the UI.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    source: string;
    /**
     * Set when import's bin-packing (see _import-one.ts) created THIS
     * listing to hold a same-platform straggler it couldn't fit onto an
     * existing candidate listing for the same physical item — points at
     * the primary/first candidate. Purely informational: this listing
     * is a real, independently listable/delistable row, not a shadow.
     * Null for every ordinarily-created listing.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    duplicateOfListingId?: string | null;
    /**
     * UUID minted on a seller's machine for a draft written offline.
     * 
     * The idempotency key for desktop sync. The failure it guards is a POST
     * that succeeds server-side whose reply is lost — the client cannot tell
     * that from a failure, retries, and one item becomes two live listings
     * against one piece of stock. Unique per user (partial index, migration
     * 0268); null for every listing that did not come from an offline draft.
     * @type {string}
     * @memberof CreateListingByIdResponseItems
     */
    clientDraftId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateListingByIdResponseItems
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateListingByIdResponseItems
     */
    updatedAt: Date;
}

export function CreateListingByIdResponseItemsFromJSON(json: any): CreateListingByIdResponseItems {
    return CreateListingByIdResponseItemsFromJSONTyped(json, false);
}

export function CreateListingByIdResponseItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateListingByIdResponseItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'effectiveTitle': json['effectiveTitle'],
        'effectivePrice': !exists(json, 'effectivePrice') ? undefined : json['effectivePrice'],
        'effectiveDescription': !exists(json, 'effectiveDescription') ? undefined : json['effectiveDescription'],
        'effectiveImages': json['effectiveImages'],
        'effectiveBrand': !exists(json, 'effectiveBrand') ? undefined : json['effectiveBrand'],
        'effectiveCondition': !exists(json, 'effectiveCondition') ? undefined : json['effectiveCondition'],
        'effectiveSize': !exists(json, 'effectiveSize') ? undefined : json['effectiveSize'],
        'effectiveSku': !exists(json, 'effectiveSku') ? undefined : json['effectiveSku'],
        'effectiveColor': json['effectiveColor'],
        'effectiveTags': json['effectiveTags'],
        'platformListings': json['platformListings'],
        'inventoryItemId': !exists(json, 'inventoryItemId') ? undefined : json['inventoryItemId'],
        'id': json['id'],
        'userId': json['userId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'descriptionHtml': !exists(json, 'descriptionHtml') ? undefined : json['descriptionHtml'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'images': !exists(json, 'images') ? undefined : json['images'],
        'videoUrl': !exists(json, 'videoUrl') ? undefined : json['videoUrl'],
        'status': json['status'],
        'condition': !exists(json, 'condition') ? undefined : json['condition'],
        'gradeKey': !exists(json, 'gradeKey') ? undefined : json['gradeKey'],
        'grading': !exists(json, 'grading') ? undefined : ListListingsItemGradingFromJSON(json['grading']),
        'brand': !exists(json, 'brand') ? undefined : json['brand'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'material': !exists(json, 'material') ? undefined : json['material'],
        'style': !exists(json, 'style') ? undefined : json['style'],
        'pattern': !exists(json, 'pattern') ? undefined : json['pattern'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'itemType': !exists(json, 'itemType') ? undefined : json['itemType'],
        'sizeSystem': !exists(json, 'sizeSystem') ? undefined : json['sizeSystem'],
        'color': json['color'],
        'tags': json['tags'],
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'quantity': json['quantity'],
        'quantityAvailable': json['quantityAvailable'],
        'weightLb': !exists(json, 'weightLb') ? undefined : json['weightLb'],
        'weightOz': !exists(json, 'weightOz') ? undefined : json['weightOz'],
        'dimensionLIn': !exists(json, 'dimensionLIn') ? undefined : json['dimensionLIn'],
        'dimensionWIn': !exists(json, 'dimensionWIn') ? undefined : json['dimensionWIn'],
        'dimensionHIn': !exists(json, 'dimensionHIn') ? undefined : json['dimensionHIn'],
        'publishAt': !exists(json, 'publishAt') ? undefined : (json['publishAt'] === null ? null : new Date(json['publishAt'])),
        'scheduledPlatforms': !exists(json, 'scheduledPlatforms') ? undefined : json['scheduledPlatforms'],
        'parentListingId': !exists(json, 'parentListingId') ? undefined : json['parentListingId'],
        'isBundle': json['isBundle'],
        'automationAssignedRuleIds': json['automationAssignedRuleIds'],
        'automationBlockedRuleIds': json['automationBlockedRuleIds'],
        'automationAssignedChainIds': json['automationAssignedChainIds'],
        'automationBlockedChainIds': json['automationBlockedChainIds'],
        'hsCode': !exists(json, 'hsCode') ? undefined : json['hsCode'],
        'countryOfOrigin': !exists(json, 'countryOfOrigin') ? undefined : json['countryOfOrigin'],
        'priceFloorCents': !exists(json, 'priceFloorCents') ? undefined : json['priceFloorCents'],
        'floorIsNet': json['floorIsNet'],
        'delistedAt': !exists(json, 'delistedAt') ? undefined : (json['delistedAt'] === null ? null : new Date(json['delistedAt'])),
        'soldAt': !exists(json, 'soldAt') ? undefined : (json['soldAt'] === null ? null : new Date(json['soldAt'])),
        'source': json['source'],
        'duplicateOfListingId': !exists(json, 'duplicateOfListingId') ? undefined : json['duplicateOfListingId'],
        'clientDraftId': !exists(json, 'clientDraftId') ? undefined : json['clientDraftId'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function CreateListingByIdResponseItemsToJSON(value?: CreateListingByIdResponseItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'effectiveTitle': value.effectiveTitle,
        'effectivePrice': value.effectivePrice,
        'effectiveDescription': value.effectiveDescription,
        'effectiveImages': value.effectiveImages,
        'effectiveBrand': value.effectiveBrand,
        'effectiveCondition': value.effectiveCondition,
        'effectiveSize': value.effectiveSize,
        'effectiveSku': value.effectiveSku,
        'effectiveColor': value.effectiveColor,
        'effectiveTags': value.effectiveTags,
        'platformListings': value.platformListings,
        'inventoryItemId': value.inventoryItemId,
        'id': value.id,
        'userId': value.userId,
        'name': value.name,
        'title': value.title,
        'description': value.description,
        'descriptionHtml': value.descriptionHtml,
        'price': value.price,
        'images': value.images,
        'videoUrl': value.videoUrl,
        'status': value.status,
        'condition': value.condition,
        'gradeKey': value.gradeKey,
        'grading': ListListingsItemGradingToJSON(value.grading),
        'brand': value.brand,
        'size': value.size,
        'material': value.material,
        'style': value.style,
        'pattern': value.pattern,
        'department': value.department,
        'gender': value.gender,
        'itemType': value.itemType,
        'sizeSystem': value.sizeSystem,
        'color': value.color,
        'tags': value.tags,
        'sku': value.sku,
        'quantity': value.quantity,
        'quantityAvailable': value.quantityAvailable,
        'weightLb': value.weightLb,
        'weightOz': value.weightOz,
        'dimensionLIn': value.dimensionLIn,
        'dimensionWIn': value.dimensionWIn,
        'dimensionHIn': value.dimensionHIn,
        'publishAt': value.publishAt === undefined ? undefined : (value.publishAt === null ? null : value.publishAt.toISOString()),
        'scheduledPlatforms': value.scheduledPlatforms,
        'parentListingId': value.parentListingId,
        'isBundle': value.isBundle,
        'automationAssignedRuleIds': value.automationAssignedRuleIds,
        'automationBlockedRuleIds': value.automationBlockedRuleIds,
        'automationAssignedChainIds': value.automationAssignedChainIds,
        'automationBlockedChainIds': value.automationBlockedChainIds,
        'hsCode': value.hsCode,
        'countryOfOrigin': value.countryOfOrigin,
        'priceFloorCents': value.priceFloorCents,
        'floorIsNet': value.floorIsNet,
        'delistedAt': value.delistedAt === undefined ? undefined : (value.delistedAt === null ? null : value.delistedAt.toISOString()),
        'soldAt': value.soldAt === undefined ? undefined : (value.soldAt === null ? null : value.soldAt.toISOString()),
        'source': value.source,
        'duplicateOfListingId': value.duplicateOfListingId,
        'clientDraftId': value.clientDraftId,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

