/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxWalletPaymentConfirmResponse
 */
export interface CreateCbxWalletPaymentConfirmResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    paymentId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    duplicate: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    releaseDecision: CreateCbxWalletPaymentConfirmResponseReleaseDecisionEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    releaseReason: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    baseUnits: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    valueCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    centsPerToken: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    payerAddress: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    riskLevel?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    riskExposures: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxWalletPaymentConfirmResponse
     */
    screeningProvider?: string | null;
}

/**
* @export
* @enum {string}
*/
export enum CreateCbxWalletPaymentConfirmResponseReleaseDecisionEnum {
    Review = 'review',
    Release = 'release',
    Refuse = 'refuse'
}

export function CreateCbxWalletPaymentConfirmResponseFromJSON(json: any): CreateCbxWalletPaymentConfirmResponse {
    return CreateCbxWalletPaymentConfirmResponseFromJSONTyped(json, false);
}

export function CreateCbxWalletPaymentConfirmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxWalletPaymentConfirmResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'],
        'duplicate': json['duplicate'],
        'releaseDecision': json['releaseDecision'],
        'releaseReason': json['releaseReason'],
        'baseUnits': json['baseUnits'],
        'valueCents': json['valueCents'],
        'centsPerToken': json['centsPerToken'],
        'payerAddress': json['payerAddress'],
        'riskLevel': !exists(json, 'riskLevel') ? undefined : json['riskLevel'],
        'riskExposures': json['riskExposures'],
        'screeningProvider': !exists(json, 'screeningProvider') ? undefined : json['screeningProvider'],
    };
}

export function CreateCbxWalletPaymentConfirmResponseToJSON(value?: CreateCbxWalletPaymentConfirmResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paymentId': value.paymentId,
        'duplicate': value.duplicate,
        'releaseDecision': value.releaseDecision,
        'releaseReason': value.releaseReason,
        'baseUnits': value.baseUnits,
        'valueCents': value.valueCents,
        'centsPerToken': value.centsPerToken,
        'payerAddress': value.payerAddress,
        'riskLevel': value.riskLevel,
        'riskExposures': value.riskExposures,
        'screeningProvider': value.screeningProvider,
    };
}

