/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxCampaignResponse
 */
export interface CreateCbxCampaignResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxCampaignResponse
     */
    campaignId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxCampaignResponse
     */
    status: string;
}

export function CreateCbxCampaignResponseFromJSON(json: any): CreateCbxCampaignResponse {
    return CreateCbxCampaignResponseFromJSONTyped(json, false);
}

export function CreateCbxCampaignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxCampaignResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'campaignId': json['campaignId'],
        'status': json['status'],
    };
}

export function CreateCbxCampaignResponseToJSON(value?: CreateCbxCampaignResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'campaignId': value.campaignId,
        'status': value.status,
    };
}

