/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMeTemplateImportResponse
 */
export interface CreateMeTemplateImportResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateMeTemplateImportResponse
     */
    imported: number;
    /**
     * 
     * @type {number}
     * @memberof CreateMeTemplateImportResponse
     */
    skipped: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMeTemplateImportResponse
     */
    ids: Array<string>;
}

export function CreateMeTemplateImportResponseFromJSON(json: any): CreateMeTemplateImportResponse {
    return CreateMeTemplateImportResponseFromJSONTyped(json, false);
}

export function CreateMeTemplateImportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMeTemplateImportResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imported': json['imported'],
        'skipped': json['skipped'],
        'ids': json['ids'],
    };
}

export function CreateMeTemplateImportResponseToJSON(value?: CreateMeTemplateImportResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'imported': value.imported,
        'skipped': value.skipped,
        'ids': value.ids,
    };
}

