/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateBuyerOfferResponseData,
    CreateBuyerOfferResponseDataFromJSON,
    CreateBuyerOfferResponseDataFromJSONTyped,
    CreateBuyerOfferResponseDataToJSON,
} from './CreateBuyerOfferResponseData';

/**
 * 
 * @export
 * @interface CreateBuyerOfferResponse
 */
export interface CreateBuyerOfferResponse {
    /**
     * 
     * @type {CreateBuyerOfferResponseData}
     * @memberof CreateBuyerOfferResponse
     */
    data: CreateBuyerOfferResponseData;
}

export function CreateBuyerOfferResponseFromJSON(json: any): CreateBuyerOfferResponse {
    return CreateBuyerOfferResponseFromJSONTyped(json, false);
}

export function CreateBuyerOfferResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBuyerOfferResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': CreateBuyerOfferResponseDataFromJSON(json['data']),
    };
}

export function CreateBuyerOfferResponseToJSON(value?: CreateBuyerOfferResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': CreateBuyerOfferResponseDataToJSON(value.data),
    };
}

