/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMeTemplateRenderResponse
 */
export interface CreateMeTemplateRenderResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateMeTemplateRenderResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMeTemplateRenderResponse
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMeTemplateRenderResponse
     */
    tokensUsed: Array<CreateMeTemplateRenderResponseTokensUsedEnum>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateMeTemplateRenderResponse
     */
    missingTokens: Array<CreateMeTemplateRenderResponseMissingTokensEnum>;
}

/**
* @export
* @enum {string}
*/
export enum CreateMeTemplateRenderResponseTokensUsedEnum {
    Date = 'date',
    Brand = 'brand',
    Sku = 'sku',
    Condition = 'condition',
    Size = 'size',
    Material = 'material',
    Style = 'style',
    Color = 'color',
    Price = 'price',
    Category = 'category',
    Year = 'year',
    Model = 'model',
    ItemName = 'item_name',
    Month = 'month'
}/**
* @export
* @enum {string}
*/
export enum CreateMeTemplateRenderResponseMissingTokensEnum {
    Date = 'date',
    Brand = 'brand',
    Sku = 'sku',
    Condition = 'condition',
    Size = 'size',
    Material = 'material',
    Style = 'style',
    Color = 'color',
    Price = 'price',
    Category = 'category',
    Year = 'year',
    Model = 'model',
    ItemName = 'item_name',
    Month = 'month'
}

export function CreateMeTemplateRenderResponseFromJSON(json: any): CreateMeTemplateRenderResponse {
    return CreateMeTemplateRenderResponseFromJSONTyped(json, false);
}

export function CreateMeTemplateRenderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMeTemplateRenderResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'tokensUsed': json['tokensUsed'],
        'missingTokens': json['missingTokens'],
    };
}

export function CreateMeTemplateRenderResponseToJSON(value?: CreateMeTemplateRenderResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'tokensUsed': value.tokensUsed,
        'missingTokens': value.missingTokens,
    };
}

