/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxCreditFreezeResponse
 */
export interface CreateCbxCreditFreezeResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxCreditFreezeResponse
     */
    frozen: boolean;
}

export function CreateCbxCreditFreezeResponseFromJSON(json: any): CreateCbxCreditFreezeResponse {
    return CreateCbxCreditFreezeResponseFromJSONTyped(json, false);
}

export function CreateCbxCreditFreezeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxCreditFreezeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'frozen': json['frozen'],
    };
}

export function CreateCbxCreditFreezeResponseToJSON(value?: CreateCbxCreditFreezeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'frozen': value.frozen,
    };
}

