/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxRedemptionResponse
 */
export interface CreateCbxRedemptionResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRedemptionResponse
     */
    redemptionId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxRedemptionResponse
     */
    duplicate: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRedemptionResponse
     */
    baseUnits: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxRedemptionResponse
     */
    chargedCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxRedemptionResponse
     */
    discountBps: number;
}

export function CreateCbxRedemptionResponseFromJSON(json: any): CreateCbxRedemptionResponse {
    return CreateCbxRedemptionResponseFromJSONTyped(json, false);
}

export function CreateCbxRedemptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxRedemptionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'redemptionId': json['redemptionId'],
        'duplicate': json['duplicate'],
        'baseUnits': json['baseUnits'],
        'chargedCents': json['chargedCents'],
        'discountBps': json['discountBps'],
    };
}

export function CreateCbxRedemptionResponseToJSON(value?: CreateCbxRedemptionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'redemptionId': value.redemptionId,
        'duplicate': value.duplicate,
        'baseUnits': value.baseUnits,
        'chargedCents': value.chargedCents,
        'discountBps': value.discountBps,
    };
}

