/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAccountLogoutAllResponse
 */
export interface CreateAccountLogoutAllResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateAccountLogoutAllResponse
     */
    ok: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateAccountLogoutAllResponse
     */
    revokedCount: number;
}

export function CreateAccountLogoutAllResponseFromJSON(json: any): CreateAccountLogoutAllResponse {
    return CreateAccountLogoutAllResponseFromJSONTyped(json, false);
}

export function CreateAccountLogoutAllResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAccountLogoutAllResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
        'revokedCount': json['revokedCount'],
    };
}

export function CreateAccountLogoutAllResponseToJSON(value?: CreateAccountLogoutAllResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
        'revokedCount': value.revokedCount,
    };
}

