/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBillingUpgradeResponse
 */
export interface CreateBillingUpgradeResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateBillingUpgradeResponse
     */
    checkoutUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateBillingUpgradeResponse
     */
    tier: CreateBillingUpgradeResponseTierEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateBillingUpgradeResponse
     */
    interval: CreateBillingUpgradeResponseIntervalEnum;
    /**
     * 
     * @type {boolean}
     * @memberof CreateBillingUpgradeResponse
     */
    charged: boolean;
}

/**
* @export
* @enum {string}
*/
export enum CreateBillingUpgradeResponseTierEnum {
    Starter = 'starter',
    Pro = 'pro',
    Unlimited = 'unlimited'
}/**
* @export
* @enum {string}
*/
export enum CreateBillingUpgradeResponseIntervalEnum {
    Monthly = 'monthly',
    Yearly = 'yearly'
}

export function CreateBillingUpgradeResponseFromJSON(json: any): CreateBillingUpgradeResponse {
    return CreateBillingUpgradeResponseFromJSONTyped(json, false);
}

export function CreateBillingUpgradeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBillingUpgradeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkoutUrl': !exists(json, 'checkoutUrl') ? undefined : json['checkoutUrl'],
        'tier': json['tier'],
        'interval': json['interval'],
        'charged': json['charged'],
    };
}

export function CreateBillingUpgradeResponseToJSON(value?: CreateBillingUpgradeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkoutUrl': value.checkoutUrl,
        'tier': value.tier,
        'interval': value.interval,
        'charged': value.charged,
    };
}

