/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBuyerWishlistItemResponse
 */
export interface CreateBuyerWishlistItemResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateBuyerWishlistItemResponse
     */
    id: string;
}

export function CreateBuyerWishlistItemResponseFromJSON(json: any): CreateBuyerWishlistItemResponse {
    return CreateBuyerWishlistItemResponseFromJSONTyped(json, false);
}

export function CreateBuyerWishlistItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBuyerWishlistItemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateBuyerWishlistItemResponseToJSON(value?: CreateBuyerWishlistItemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

