/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxSpendReverseResponse
 */
export interface CreateCbxSpendReverseResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxSpendReverseResponse
     */
    reversed: boolean;
}

export function CreateCbxSpendReverseResponseFromJSON(json: any): CreateCbxSpendReverseResponse {
    return CreateCbxSpendReverseResponseFromJSONTyped(json, false);
}

export function CreateCbxSpendReverseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxSpendReverseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reversed': json['reversed'],
    };
}

export function CreateCbxSpendReverseResponseToJSON(value?: CreateCbxSpendReverseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reversed': value.reversed,
    };
}

