/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAiEnhanceListingResponse
 */
export interface CreateAiEnhanceListingResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateAiEnhanceListingResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateAiEnhanceListingResponse
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateAiEnhanceListingResponse
     */
    tags: Array<string>;
}

export function CreateAiEnhanceListingResponseFromJSON(json: any): CreateAiEnhanceListingResponse {
    return CreateAiEnhanceListingResponseFromJSONTyped(json, false);
}

export function CreateAiEnhanceListingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAiEnhanceListingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'tags': json['tags'],
    };
}

export function CreateAiEnhanceListingResponseToJSON(value?: CreateAiEnhanceListingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'description': value.description,
        'tags': value.tags,
    };
}

