/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateInboxConversationBulkAiRespondResponseResults,
    CreateInboxConversationBulkAiRespondResponseResultsFromJSON,
    CreateInboxConversationBulkAiRespondResponseResultsFromJSONTyped,
    CreateInboxConversationBulkAiRespondResponseResultsToJSON,
} from './CreateInboxConversationBulkAiRespondResponseResults';

/**
 * 
 * @export
 * @interface CreateInboxConversationBulkAiRespondResponse
 */
export interface CreateInboxConversationBulkAiRespondResponse {
    /**
     * 
     * @type {Array<CreateInboxConversationBulkAiRespondResponseResults>}
     * @memberof CreateInboxConversationBulkAiRespondResponse
     */
    results: Array<CreateInboxConversationBulkAiRespondResponseResults>;
}

export function CreateInboxConversationBulkAiRespondResponseFromJSON(json: any): CreateInboxConversationBulkAiRespondResponse {
    return CreateInboxConversationBulkAiRespondResponseFromJSONTyped(json, false);
}

export function CreateInboxConversationBulkAiRespondResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInboxConversationBulkAiRespondResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'results': ((json['results'] as Array<any>).map(CreateInboxConversationBulkAiRespondResponseResultsFromJSON)),
    };
}

export function CreateInboxConversationBulkAiRespondResponseToJSON(value?: CreateInboxConversationBulkAiRespondResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'results': ((value.results as Array<any>).map(CreateInboxConversationBulkAiRespondResponseResultsToJSON)),
    };
}

