/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxAccrualPurchaseResponse
 */
export interface CreateCbxAccrualPurchaseResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxAccrualPurchaseResponse
     */
    accrualId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxAccrualPurchaseResponse
     */
    duplicate: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAccrualPurchaseResponse
     */
    cents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAccrualPurchaseResponse
     */
    rateBps?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxAccrualPurchaseResponse
     */
    maturesAt?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxAccrualPurchaseResponse
     */
    boostBudgetExhausted: boolean;
}

export function CreateCbxAccrualPurchaseResponseFromJSON(json: any): CreateCbxAccrualPurchaseResponse {
    return CreateCbxAccrualPurchaseResponseFromJSONTyped(json, false);
}

export function CreateCbxAccrualPurchaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxAccrualPurchaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accrualId': !exists(json, 'accrualId') ? undefined : json['accrualId'],
        'duplicate': json['duplicate'],
        'cents': json['cents'],
        'rateBps': !exists(json, 'rateBps') ? undefined : json['rateBps'],
        'maturesAt': !exists(json, 'maturesAt') ? undefined : json['maturesAt'],
        'boostBudgetExhausted': json['boostBudgetExhausted'],
    };
}

export function CreateCbxAccrualPurchaseResponseToJSON(value?: CreateCbxAccrualPurchaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accrualId': value.accrualId,
        'duplicate': value.duplicate,
        'cents': value.cents,
        'rateBps': value.rateBps,
        'maturesAt': value.maturesAt,
        'boostBudgetExhausted': value.boostBudgetExhausted,
    };
}

