/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMagicScanResponsePossibleDuplicates
 */
export interface CreateMagicScanResponsePossibleDuplicates {
    /**
     * The seller's existing listing this scan probably duplicates (null if the
     * match landed only on an inventory item with no listing row).
     * @type {string}
     * @memberof CreateMagicScanResponsePossibleDuplicates
     */
    listingId?: string | null;
    /**
     * The inventory item behind that listing, when linked. Drives the
     * "View inventory" button.
     * @type {string}
     * @memberof CreateMagicScanResponsePossibleDuplicates
     */
    inventoryItemId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMagicScanResponsePossibleDuplicates
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMagicScanResponsePossibleDuplicates
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMagicScanResponsePossibleDuplicates
     */
    matchType: CreateMagicScanResponsePossibleDuplicatesMatchTypeEnum;
    /**
     * 0–1 confidence. Image matches report 1; title matches the similarity.
     * @type {number}
     * @memberof CreateMagicScanResponsePossibleDuplicates
     */
    score: number;
    /**
     * The variation group the matched listing already belongs to, if any.
     * 
     * This is what turns "you already have this" into something useful for a
     * seller scanning a size run. Scan the Medium, scan the Large, and the
     * second scan lands here — the honest answer is usually neither "it's the
     * same one" nor "it's different", it's "it's another size of that". Which
     * of the two offers to make depends entirely on this field:
     * 
     *   null      → offer to CREATE a group from the match and the new listing
     *   set       → offer to ADD the new listing to the group that exists
     * 
     * Without it the UI would have to guess, and guessing wrong means either a
     * second group beside the first or a silent no-op.
     * @type {string}
     * @memberof CreateMagicScanResponsePossibleDuplicates
     */
    variationGroupId?: string | null;
}

/**
* @export
* @enum {string}
*/
export enum CreateMagicScanResponsePossibleDuplicatesMatchTypeEnum {
    Title = 'title',
    Image = 'image'
}

export function CreateMagicScanResponsePossibleDuplicatesFromJSON(json: any): CreateMagicScanResponsePossibleDuplicates {
    return CreateMagicScanResponsePossibleDuplicatesFromJSONTyped(json, false);
}

export function CreateMagicScanResponsePossibleDuplicatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMagicScanResponsePossibleDuplicates {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listingId': !exists(json, 'listingId') ? undefined : json['listingId'],
        'inventoryItemId': !exists(json, 'inventoryItemId') ? undefined : json['inventoryItemId'],
        'title': json['title'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'matchType': json['matchType'],
        'score': json['score'],
        'variationGroupId': !exists(json, 'variationGroupId') ? undefined : json['variationGroupId'],
    };
}

export function CreateMagicScanResponsePossibleDuplicatesToJSON(value?: CreateMagicScanResponsePossibleDuplicates | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listingId': value.listingId,
        'inventoryItemId': value.inventoryItemId,
        'title': value.title,
        'imageUrl': value.imageUrl,
        'matchType': value.matchType,
        'score': value.score,
        'variationGroupId': value.variationGroupId,
    };
}

