/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxWalletPaymentResolveResponse
 */
export interface CreateCbxWalletPaymentResolveResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxWalletPaymentResolveResponse
     */
    resolved: boolean;
}

export function CreateCbxWalletPaymentResolveResponseFromJSON(json: any): CreateCbxWalletPaymentResolveResponse {
    return CreateCbxWalletPaymentResolveResponseFromJSONTyped(json, false);
}

export function CreateCbxWalletPaymentResolveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxWalletPaymentResolveResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'resolved': json['resolved'],
    };
}

export function CreateCbxWalletPaymentResolveResponseToJSON(value?: CreateCbxWalletPaymentResolveResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'resolved': value.resolved,
    };
}

