/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderLabelResponse
 */
export interface CreateOrderLabelResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateOrderLabelResponse
     */
    trackingNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderLabelResponse
     */
    labelUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderLabelResponse
     */
    carrier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderLabelResponse
     */
    service?: string | null;
}

export function CreateOrderLabelResponseFromJSON(json: any): CreateOrderLabelResponse {
    return CreateOrderLabelResponseFromJSONTyped(json, false);
}

export function CreateOrderLabelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderLabelResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trackingNumber': !exists(json, 'trackingNumber') ? undefined : json['trackingNumber'],
        'labelUrl': !exists(json, 'labelUrl') ? undefined : json['labelUrl'],
        'carrier': !exists(json, 'carrier') ? undefined : json['carrier'],
        'service': !exists(json, 'service') ? undefined : json['service'],
    };
}

export function CreateOrderLabelResponseToJSON(value?: CreateOrderLabelResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'trackingNumber': value.trackingNumber,
        'labelUrl': value.labelUrl,
        'carrier': value.carrier,
        'service': value.service,
    };
}

