/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxDisbursementRuleResponse
 */
export interface CreateCbxDisbursementRuleResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxDisbursementRuleResponse
     */
    ruleId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxDisbursementRuleResponse
     */
    isActive: boolean;
}

export function CreateCbxDisbursementRuleResponseFromJSON(json: any): CreateCbxDisbursementRuleResponse {
    return CreateCbxDisbursementRuleResponseFromJSONTyped(json, false);
}

export function CreateCbxDisbursementRuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxDisbursementRuleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ruleId': json['ruleId'],
        'isActive': json['isActive'],
    };
}

export function CreateCbxDisbursementRuleResponseToJSON(value?: CreateCbxDisbursementRuleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ruleId': value.ruleId,
        'isActive': value.isActive,
    };
}

