/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Null,
    NullFromJSON,
    NullFromJSONTyped,
    NullToJSON,
} from './Null';

/**
 * 
 * @export
 * @interface CreateListingBulkCheckStatusResponse
 */
export interface CreateListingBulkCheckStatusResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateListingBulkCheckStatusResponse
     */
    message: string;
    /**
     * 
     * @type {Null}
     * @memberof CreateListingBulkCheckStatusResponse
     */
    bulkJobId: Null;
}

export function CreateListingBulkCheckStatusResponseFromJSON(json: any): CreateListingBulkCheckStatusResponse {
    return CreateListingBulkCheckStatusResponseFromJSONTyped(json, false);
}

export function CreateListingBulkCheckStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateListingBulkCheckStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'bulkJobId': NullFromJSON(json['bulkJobId']),
    };
}

export function CreateListingBulkCheckStatusResponseToJSON(value?: CreateListingBulkCheckStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'bulkJobId': NullToJSON(value.bulkJobId),
    };
}

