/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateAiGenerateListingResponsePriceRangeValue
 */
export interface CreateAiGenerateListingResponsePriceRangeValue {
    /**
     * 
     * @type {number}
     * @memberof CreateAiGenerateListingResponsePriceRangeValue
     */
    low: number;
    /**
     * 
     * @type {number}
     * @memberof CreateAiGenerateListingResponsePriceRangeValue
     */
    high: number;
}

export function CreateAiGenerateListingResponsePriceRangeValueFromJSON(json: any): CreateAiGenerateListingResponsePriceRangeValue {
    return CreateAiGenerateListingResponsePriceRangeValueFromJSONTyped(json, false);
}

export function CreateAiGenerateListingResponsePriceRangeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateAiGenerateListingResponsePriceRangeValue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'low': json['low'],
        'high': json['high'],
    };
}

export function CreateAiGenerateListingResponsePriceRangeValueToJSON(value?: CreateAiGenerateListingResponsePriceRangeValue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'low': value.low,
        'high': value.high,
    };
}

