/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderBulkMarkDisputedResponse
 */
export interface CreateOrderBulkMarkDisputedResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateOrderBulkMarkDisputedResponse
     */
    updated: number;
}

export function CreateOrderBulkMarkDisputedResponseFromJSON(json: any): CreateOrderBulkMarkDisputedResponse {
    return CreateOrderBulkMarkDisputedResponseFromJSONTyped(json, false);
}

export function CreateOrderBulkMarkDisputedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderBulkMarkDisputedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updated': json['updated'],
    };
}

export function CreateOrderBulkMarkDisputedResponseToJSON(value?: CreateOrderBulkMarkDisputedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updated': value.updated,
    };
}

