/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxClaimResponse
 */
export interface CreateCbxClaimResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimResponse
     */
    claimId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimResponse
     */
    requestedBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimResponse
     */
    serviceFeeBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimResponse
     */
    networkFeeBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimResponse
     */
    netBaseUnits: string;
}

export function CreateCbxClaimResponseFromJSON(json: any): CreateCbxClaimResponse {
    return CreateCbxClaimResponseFromJSONTyped(json, false);
}

export function CreateCbxClaimResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxClaimResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'claimId': json['claimId'],
        'status': json['status'],
        'requestedBaseUnits': json['requestedBaseUnits'],
        'serviceFeeBaseUnits': json['serviceFeeBaseUnits'],
        'networkFeeBaseUnits': json['networkFeeBaseUnits'],
        'netBaseUnits': json['netBaseUnits'],
    };
}

export function CreateCbxClaimResponseToJSON(value?: CreateCbxClaimResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'claimId': value.claimId,
        'status': value.status,
        'requestedBaseUnits': value.requestedBaseUnits,
        'serviceFeeBaseUnits': value.serviceFeeBaseUnits,
        'networkFeeBaseUnits': value.networkFeeBaseUnits,
        'netBaseUnits': value.netBaseUnits,
    };
}

