/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePlatformAccountRefreshStatusResponseResults
 */
export interface CreatePlatformAccountRefreshStatusResponseResults {
    /**
     * 
     * @type {string}
     * @memberof CreatePlatformAccountRefreshStatusResponseResults
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePlatformAccountRefreshStatusResponseResults
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePlatformAccountRefreshStatusResponseResults
     */
    status: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePlatformAccountRefreshStatusResponseResults
     */
    checked: boolean;
}

export function CreatePlatformAccountRefreshStatusResponseResultsFromJSON(json: any): CreatePlatformAccountRefreshStatusResponseResults {
    return CreatePlatformAccountRefreshStatusResponseResultsFromJSONTyped(json, false);
}

export function CreatePlatformAccountRefreshStatusResponseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePlatformAccountRefreshStatusResponseResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'platform': json['platform'],
        'status': json['status'],
        'checked': json['checked'],
    };
}

export function CreatePlatformAccountRefreshStatusResponseResultsToJSON(value?: CreatePlatformAccountRefreshStatusResponseResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'platform': value.platform,
        'status': value.status,
        'checked': value.checked,
    };
}

