/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInboxMessageTriageResponse
 */
export interface CreateInboxMessageTriageResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateInboxMessageTriageResponse
     */
    aiIntent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateInboxMessageTriageResponse
     */
    aiUrgency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateInboxMessageTriageResponse
     */
    aiScamScore?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateInboxMessageTriageResponse
     */
    aiSuggestedReply?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CreateInboxMessageTriageResponse
     */
    aiTriagedAt?: Date | null;
}

export function CreateInboxMessageTriageResponseFromJSON(json: any): CreateInboxMessageTriageResponse {
    return CreateInboxMessageTriageResponseFromJSONTyped(json, false);
}

export function CreateInboxMessageTriageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInboxMessageTriageResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'aiIntent': !exists(json, 'aiIntent') ? undefined : json['aiIntent'],
        'aiUrgency': !exists(json, 'aiUrgency') ? undefined : json['aiUrgency'],
        'aiScamScore': !exists(json, 'aiScamScore') ? undefined : json['aiScamScore'],
        'aiSuggestedReply': !exists(json, 'aiSuggestedReply') ? undefined : json['aiSuggestedReply'],
        'aiTriagedAt': !exists(json, 'aiTriagedAt') ? undefined : (json['aiTriagedAt'] === null ? null : new Date(json['aiTriagedAt'])),
    };
}

export function CreateInboxMessageTriageResponseToJSON(value?: CreateInboxMessageTriageResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'aiIntent': value.aiIntent,
        'aiUrgency': value.aiUrgency,
        'aiScamScore': value.aiScamScore,
        'aiSuggestedReply': value.aiSuggestedReply,
        'aiTriagedAt': value.aiTriagedAt === undefined ? undefined : (value.aiTriagedAt === null ? null : value.aiTriagedAt.toISOString()),
    };
}

