/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateOrderDisputeResponseError,
    CreateOrderDisputeResponseErrorFromJSON,
    CreateOrderDisputeResponseErrorFromJSONTyped,
    CreateOrderDisputeResponseErrorToJSON,
} from './CreateOrderDisputeResponseError';

/**
 * 
 * @export
 * @interface DeleteInboxCannedResponsResponse
 */
export interface DeleteInboxCannedResponsResponse {
    /**
     * 
     * @type {CreateOrderDisputeResponseError}
     * @memberof DeleteInboxCannedResponsResponse
     */
    error: CreateOrderDisputeResponseError;
}

export function DeleteInboxCannedResponsResponseFromJSON(json: any): DeleteInboxCannedResponsResponse {
    return DeleteInboxCannedResponsResponseFromJSONTyped(json, false);
}

export function DeleteInboxCannedResponsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteInboxCannedResponsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': CreateOrderDisputeResponseErrorFromJSON(json['error']),
    };
}

export function DeleteInboxCannedResponsResponseToJSON(value?: DeleteInboxCannedResponsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': CreateOrderDisputeResponseErrorToJSON(value.error),
    };
}

