/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateListingResponseJobs,
    CreateListingResponseJobsFromJSON,
    CreateListingResponseJobsFromJSONTyped,
    CreateListingResponseJobsToJSON,
} from './CreateListingResponseJobs';

/**
 * 
 * @export
 * @interface DeleteListingResponse
 */
export interface DeleteListingResponse {
    /**
     * 
     * @type {Array<CreateListingResponseJobs>}
     * @memberof DeleteListingResponse
     */
    jobs: Array<CreateListingResponseJobs>;
}

export function DeleteListingResponseFromJSON(json: any): DeleteListingResponse {
    return DeleteListingResponseFromJSONTyped(json, false);
}

export function DeleteListingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteListingResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(CreateListingResponseJobsFromJSON)),
    };
}

export function DeleteListingResponseToJSON(value?: DeleteListingResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobs': ((value.jobs as Array<any>).map(CreateListingResponseJobsToJSON)),
    };
}

