/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAnalyticDashboardResponseRevenue
 */
export interface GetAnalyticDashboardResponseRevenue {
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseRevenue
     */
    current: number;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseRevenue
     */
    previous: number;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseRevenue
     */
    pctChange?: number | null;
}

export function GetAnalyticDashboardResponseRevenueFromJSON(json: any): GetAnalyticDashboardResponseRevenue {
    return GetAnalyticDashboardResponseRevenueFromJSONTyped(json, false);
}

export function GetAnalyticDashboardResponseRevenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticDashboardResponseRevenue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'current': json['current'],
        'previous': json['previous'],
        'pctChange': !exists(json, 'pctChange') ? undefined : json['pctChange'],
    };
}

export function GetAnalyticDashboardResponseRevenueToJSON(value?: GetAnalyticDashboardResponseRevenue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current': value.current,
        'previous': value.previous,
        'pctChange': value.pctChange,
    };
}

