/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetAnalyticItemResponseItems,
    GetAnalyticItemResponseItemsFromJSON,
    GetAnalyticItemResponseItemsFromJSONTyped,
    GetAnalyticItemResponseItemsToJSON,
} from './GetAnalyticItemResponseItems';

/**
 * 
 * @export
 * @interface GetAnalyticItemResponse
 */
export interface GetAnalyticItemResponse {
    /**
     * 
     * @type {Array<GetAnalyticItemResponseItems>}
     * @memberof GetAnalyticItemResponse
     */
    items: Array<GetAnalyticItemResponseItems>;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticItemResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticItemResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticItemResponse
     */
    limit: number;
}

export function GetAnalyticItemResponseFromJSON(json: any): GetAnalyticItemResponse {
    return GetAnalyticItemResponseFromJSONTyped(json, false);
}

export function GetAnalyticItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticItemResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GetAnalyticItemResponseItemsFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'limit': json['limit'],
    };
}

export function GetAnalyticItemResponseToJSON(value?: GetAnalyticItemResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(GetAnalyticItemResponseItemsToJSON)),
        'total': value.total,
        'page': value.page,
        'limit': value.limit,
    };
}

