/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAnalyticDashboardResponseTopCategories
 */
export interface GetAnalyticDashboardResponseTopCategories {
    /**
     * 
     * @type {string}
     * @memberof GetAnalyticDashboardResponseTopCategories
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseTopCategories
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseTopCategories
     */
    revenue: number;
}

export function GetAnalyticDashboardResponseTopCategoriesFromJSON(json: any): GetAnalyticDashboardResponseTopCategories {
    return GetAnalyticDashboardResponseTopCategoriesFromJSONTyped(json, false);
}

export function GetAnalyticDashboardResponseTopCategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticDashboardResponseTopCategories {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'count': json['count'],
        'revenue': json['revenue'],
    };
}

export function GetAnalyticDashboardResponseTopCategoriesToJSON(value?: GetAnalyticDashboardResponseTopCategories | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'count': value.count,
        'revenue': value.revenue,
    };
}

