/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Community-library metadata. Server ignores; UI may render.
 * @export
 * @interface GetAutomationRuleExportResponseMetadata
 */
export interface GetAutomationRuleExportResponseMetadata {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAutomationRuleExportResponseMetadata
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof GetAutomationRuleExportResponseMetadata
     */
    sourceUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAutomationRuleExportResponseMetadata
     */
    author?: string | null;
}

export function GetAutomationRuleExportResponseMetadataFromJSON(json: any): GetAutomationRuleExportResponseMetadata {
    return GetAutomationRuleExportResponseMetadataFromJSONTyped(json, false);
}

export function GetAutomationRuleExportResponseMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAutomationRuleExportResponseMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'sourceUrl': !exists(json, 'sourceUrl') ? undefined : json['sourceUrl'],
        'author': !exists(json, 'author') ? undefined : json['author'],
    };
}

export function GetAutomationRuleExportResponseMetadataToJSON(value?: GetAutomationRuleExportResponseMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags,
        'sourceUrl': value.sourceUrl,
        'author': value.author,
    };
}

