/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdOffsiteReportResponse
 */
export interface GetAdOffsiteReportResponse {
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    spendCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    mediaCostCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    managementFeeCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    impressions: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    clicks: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    conversions: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    attributedRevenueCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    spilloverConversions: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    spilloverRevenueCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteReportResponse
     */
    returnBps: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetAdOffsiteReportResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetAdOffsiteReportResponse
     */
    autoPausedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAdOffsiteReportResponse
     */
    autoPausedReason?: string | null;
}

export function GetAdOffsiteReportResponseFromJSON(json: any): GetAdOffsiteReportResponse {
    return GetAdOffsiteReportResponseFromJSONTyped(json, false);
}

export function GetAdOffsiteReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdOffsiteReportResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spendCents': json['spendCents'],
        'mediaCostCents': json['mediaCostCents'],
        'managementFeeCents': json['managementFeeCents'],
        'impressions': json['impressions'],
        'clicks': json['clicks'],
        'conversions': json['conversions'],
        'attributedRevenueCents': json['attributedRevenueCents'],
        'spilloverConversions': json['spilloverConversions'],
        'spilloverRevenueCents': json['spilloverRevenueCents'],
        'returnBps': json['returnBps'],
        'enabled': json['enabled'],
        'autoPausedAt': !exists(json, 'autoPausedAt') ? undefined : json['autoPausedAt'],
        'autoPausedReason': !exists(json, 'autoPausedReason') ? undefined : json['autoPausedReason'],
    };
}

export function GetAdOffsiteReportResponseToJSON(value?: GetAdOffsiteReportResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spendCents': value.spendCents,
        'mediaCostCents': value.mediaCostCents,
        'managementFeeCents': value.managementFeeCents,
        'impressions': value.impressions,
        'clicks': value.clicks,
        'conversions': value.conversions,
        'attributedRevenueCents': value.attributedRevenueCents,
        'spilloverConversions': value.spilloverConversions,
        'spilloverRevenueCents': value.spilloverRevenueCents,
        'returnBps': value.returnBps,
        'enabled': value.enabled,
        'autoPausedAt': value.autoPausedAt,
        'autoPausedReason': value.autoPausedReason,
    };
}

