/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetAnalyticTodayResponseChecklist,
    GetAnalyticTodayResponseChecklistFromJSON,
    GetAnalyticTodayResponseChecklistFromJSONTyped,
    GetAnalyticTodayResponseChecklistToJSON,
} from './GetAnalyticTodayResponseChecklist';
import {
    GetAnalyticTodayResponseStreak,
    GetAnalyticTodayResponseStreakFromJSON,
    GetAnalyticTodayResponseStreakFromJSONTyped,
    GetAnalyticTodayResponseStreakToJSON,
} from './GetAnalyticTodayResponseStreak';

/**
 * 
 * @export
 * @interface GetAnalyticTodayResponse
 */
export interface GetAnalyticTodayResponse {
    /**
     * 
     * @type {GetAnalyticTodayResponseChecklist}
     * @memberof GetAnalyticTodayResponse
     */
    checklist: GetAnalyticTodayResponseChecklist;
    /**
     * 
     * @type {GetAnalyticTodayResponseStreak}
     * @memberof GetAnalyticTodayResponse
     */
    streak: GetAnalyticTodayResponseStreak;
    /**
     * 
     * @type {Array<number>}
     * @memberof GetAnalyticTodayResponse
     */
    activitySparkline: Array<number>;
}

export function GetAnalyticTodayResponseFromJSON(json: any): GetAnalyticTodayResponse {
    return GetAnalyticTodayResponseFromJSONTyped(json, false);
}

export function GetAnalyticTodayResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticTodayResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checklist': GetAnalyticTodayResponseChecklistFromJSON(json['checklist']),
        'streak': GetAnalyticTodayResponseStreakFromJSON(json['streak']),
        'activitySparkline': json['activitySparkline'],
    };
}

export function GetAnalyticTodayResponseToJSON(value?: GetAnalyticTodayResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checklist': GetAnalyticTodayResponseChecklistToJSON(value.checklist),
        'streak': GetAnalyticTodayResponseStreakToJSON(value.streak),
        'activitySparkline': value.activitySparkline,
    };
}

