/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetAdOffsiteResponseTerms,
    GetAdOffsiteResponseTermsFromJSON,
    GetAdOffsiteResponseTermsFromJSONTyped,
    GetAdOffsiteResponseTermsToJSON,
} from './GetAdOffsiteResponseTerms';

/**
 * 
 * @export
 * @interface GetAdOffsiteResponse
 */
export interface GetAdOffsiteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetAdOffsiteResponse
     */
    enabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteResponse
     */
    maxOffsiteShareBps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteResponse
     */
    minReturnBps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteResponse
     */
    returnWindowDays?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAdOffsiteResponse
     */
    allowedNetworks?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof GetAdOffsiteResponse
     */
    autoPausedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAdOffsiteResponse
     */
    autoPausedReason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAdOffsiteResponse
     */
    optedInAt?: string | null;
    /**
     * 
     * @type {GetAdOffsiteResponseTerms}
     * @memberof GetAdOffsiteResponse
     */
    terms: GetAdOffsiteResponseTerms;
    /**
     * 
     * @type {boolean}
     * @memberof GetAdOffsiteResponse
     */
    networkWired: boolean;
}

export function GetAdOffsiteResponseFromJSON(json: any): GetAdOffsiteResponse {
    return GetAdOffsiteResponseFromJSONTyped(json, false);
}

export function GetAdOffsiteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdOffsiteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'enabled': json['enabled'],
        'maxOffsiteShareBps': !exists(json, 'maxOffsiteShareBps') ? undefined : json['maxOffsiteShareBps'],
        'minReturnBps': !exists(json, 'minReturnBps') ? undefined : json['minReturnBps'],
        'returnWindowDays': !exists(json, 'returnWindowDays') ? undefined : json['returnWindowDays'],
        'allowedNetworks': !exists(json, 'allowedNetworks') ? undefined : json['allowedNetworks'],
        'autoPausedAt': !exists(json, 'autoPausedAt') ? undefined : json['autoPausedAt'],
        'autoPausedReason': !exists(json, 'autoPausedReason') ? undefined : json['autoPausedReason'],
        'optedInAt': !exists(json, 'optedInAt') ? undefined : json['optedInAt'],
        'terms': GetAdOffsiteResponseTermsFromJSON(json['terms']),
        'networkWired': json['networkWired'],
    };
}

export function GetAdOffsiteResponseToJSON(value?: GetAdOffsiteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'enabled': value.enabled,
        'maxOffsiteShareBps': value.maxOffsiteShareBps,
        'minReturnBps': value.minReturnBps,
        'returnWindowDays': value.returnWindowDays,
        'allowedNetworks': value.allowedNetworks,
        'autoPausedAt': value.autoPausedAt,
        'autoPausedReason': value.autoPausedReason,
        'optedInAt': value.optedInAt,
        'terms': GetAdOffsiteResponseTermsToJSON(value.terms),
        'networkWired': value.networkWired,
    };
}

