/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetAnalyticTimeseryResponseSeries,
    GetAnalyticTimeseryResponseSeriesFromJSON,
    GetAnalyticTimeseryResponseSeriesFromJSONTyped,
    GetAnalyticTimeseryResponseSeriesToJSON,
} from './GetAnalyticTimeseryResponseSeries';

/**
 * 
 * @export
 * @interface GetAnalyticTimeseryResponse
 */
export interface GetAnalyticTimeseryResponse {
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticTimeseryResponse
     */
    days: number;
    /**
     * 
     * @type {Array<GetAnalyticTimeseryResponseSeries>}
     * @memberof GetAnalyticTimeseryResponse
     */
    series: Array<GetAnalyticTimeseryResponseSeries>;
}

export function GetAnalyticTimeseryResponseFromJSON(json: any): GetAnalyticTimeseryResponse {
    return GetAnalyticTimeseryResponseFromJSONTyped(json, false);
}

export function GetAnalyticTimeseryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticTimeseryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'days': json['days'],
        'series': ((json['series'] as Array<any>).map(GetAnalyticTimeseryResponseSeriesFromJSON)),
    };
}

export function GetAnalyticTimeseryResponseToJSON(value?: GetAnalyticTimeseryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'days': value.days,
        'series': ((value.series as Array<any>).map(GetAnalyticTimeseryResponseSeriesToJSON)),
    };
}

