/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBuyerProfileResponse
 */
export interface GetBuyerProfileResponse {
    /**
     * 
     * @type {string}
     * @memberof GetBuyerProfileResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerProfileResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerProfileResponse
     */
    displayName?: string | null;
    /**
     * 
     * @type {object}
     * @memberof GetBuyerProfileResponse
     */
    shippingAddress?: object | null;
    /**
     * 
     * @type {number}
     * @memberof GetBuyerProfileResponse
     */
    bucksBalanceCents: number;
}

export function GetBuyerProfileResponseFromJSON(json: any): GetBuyerProfileResponse {
    return GetBuyerProfileResponseFromJSONTyped(json, false);
}

export function GetBuyerProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBuyerProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'shippingAddress': !exists(json, 'shippingAddress') ? undefined : json['shippingAddress'],
        'bucksBalanceCents': json['bucksBalanceCents'],
    };
}

export function GetBuyerProfileResponseToJSON(value?: GetBuyerProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'email': value.email,
        'displayName': value.displayName,
        'shippingAddress': value.shippingAddress,
        'bucksBalanceCents': value.bucksBalanceCents,
    };
}

