/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetBuyerScanSessionResponseIdentifier,
    GetBuyerScanSessionResponseIdentifierFromJSON,
    GetBuyerScanSessionResponseIdentifierFromJSONTyped,
    GetBuyerScanSessionResponseIdentifierToJSON,
} from './GetBuyerScanSessionResponseIdentifier';

/**
 * 
 * @export
 * @interface GetBuyerScanSessionResponseCaptures
 */
export interface GetBuyerScanSessionResponseCaptures {
    /**
     * 
     * @type {string}
     * @memberof GetBuyerScanSessionResponseCaptures
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerScanSessionResponseCaptures
     */
    matchMethod: string;
    /**
     * 
     * @type {GetBuyerScanSessionResponseIdentifier}
     * @memberof GetBuyerScanSessionResponseCaptures
     */
    identifier?: GetBuyerScanSessionResponseIdentifier | null;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerScanSessionResponseCaptures
     */
    verdict: string;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerScanSessionResponseCaptures
     */
    displayLine?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetBuyerScanSessionResponseCaptures
     */
    savingCents?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerScanSessionResponseCaptures
     */
    createdAt: string;
}

export function GetBuyerScanSessionResponseCapturesFromJSON(json: any): GetBuyerScanSessionResponseCaptures {
    return GetBuyerScanSessionResponseCapturesFromJSONTyped(json, false);
}

export function GetBuyerScanSessionResponseCapturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBuyerScanSessionResponseCaptures {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'matchMethod': json['matchMethod'],
        'identifier': !exists(json, 'identifier') ? undefined : GetBuyerScanSessionResponseIdentifierFromJSON(json['identifier']),
        'verdict': json['verdict'],
        'displayLine': !exists(json, 'displayLine') ? undefined : json['displayLine'],
        'savingCents': !exists(json, 'savingCents') ? undefined : json['savingCents'],
        'createdAt': json['createdAt'],
    };
}

export function GetBuyerScanSessionResponseCapturesToJSON(value?: GetBuyerScanSessionResponseCaptures | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'matchMethod': value.matchMethod,
        'identifier': GetBuyerScanSessionResponseIdentifierToJSON(value.identifier),
        'verdict': value.verdict,
        'displayLine': value.displayLine,
        'savingCents': value.savingCents,
        'createdAt': value.createdAt,
    };
}

