/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCbxSubjectWalletResponse
 */
export interface GetCbxSubjectWalletResponse {
    /**
     * 
     * @type {string}
     * @memberof GetCbxSubjectWalletResponse
     */
    walletId: string;
    /**
     * 
     * @type {string}
     * @memberof GetCbxSubjectWalletResponse
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof GetCbxSubjectWalletResponse
     */
    chain: string;
    /**
     * 
     * @type {Date}
     * @memberof GetCbxSubjectWalletResponse
     */
    verifiedAt?: Date | null;
}

export function GetCbxSubjectWalletResponseFromJSON(json: any): GetCbxSubjectWalletResponse {
    return GetCbxSubjectWalletResponseFromJSONTyped(json, false);
}

export function GetCbxSubjectWalletResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCbxSubjectWalletResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'walletId': json['walletId'],
        'address': json['address'],
        'chain': json['chain'],
        'verifiedAt': !exists(json, 'verifiedAt') ? undefined : (json['verifiedAt'] === null ? null : new Date(json['verifiedAt'])),
    };
}

export function GetCbxSubjectWalletResponseToJSON(value?: GetCbxSubjectWalletResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'walletId': value.walletId,
        'address': value.address,
        'chain': value.chain,
        'verifiedAt': value.verifiedAt === undefined ? undefined : (value.verifiedAt === null ? null : value.verifiedAt.toISOString()),
    };
}

