/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetConnectionEmailResponseData
 */
export interface GetConnectionEmailResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetConnectionEmailResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionEmailResponseData
     */
    type: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetConnectionEmailResponseData
     */
    isConnected: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionEmailResponseData
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionEmailResponseData
     */
    host?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetConnectionEmailResponseData
     */
    port?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof GetConnectionEmailResponseData
     */
    lastSyncedAt?: Date | null;
}

export function GetConnectionEmailResponseDataFromJSON(json: any): GetConnectionEmailResponseData {
    return GetConnectionEmailResponseDataFromJSONTyped(json, false);
}

export function GetConnectionEmailResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConnectionEmailResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'isConnected': json['isConnected'],
        'email': json['email'],
        'host': !exists(json, 'host') ? undefined : json['host'],
        'port': !exists(json, 'port') ? undefined : json['port'],
        'lastSyncedAt': !exists(json, 'lastSyncedAt') ? undefined : (json['lastSyncedAt'] === null ? null : new Date(json['lastSyncedAt'])),
    };
}

export function GetConnectionEmailResponseDataToJSON(value?: GetConnectionEmailResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'isConnected': value.isConnected,
        'email': value.email,
        'host': value.host,
        'port': value.port,
        'lastSyncedAt': value.lastSyncedAt === undefined ? undefined : (value.lastSyncedAt === null ? null : value.lastSyncedAt.toISOString()),
    };
}

