/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetCatalogLookupResponseCatalog,
    GetCatalogLookupResponseCatalogFromJSON,
    GetCatalogLookupResponseCatalogFromJSONTyped,
    GetCatalogLookupResponseCatalogToJSON,
} from './GetCatalogLookupResponseCatalog';

/**
 * 
 * @export
 * @interface GetCatalogLookupResponseOffers
 */
export interface GetCatalogLookupResponseOffers {
    /**
     * 
     * @type {string}
     * @memberof GetCatalogLookupResponseOffers
     */
    kind: GetCatalogLookupResponseOffersKindEnum;
    /**
     * 
     * @type {number}
     * @memberof GetCatalogLookupResponseOffers
     */
    priceCents: number;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogLookupResponseOffers
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogLookupResponseOffers
     */
    condition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogLookupResponseOffers
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogLookupResponseOffers
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetCatalogLookupResponseOffers
     */
    url: string;
    /**
     * Null on an order-book ask, which is a price rather than a
purchasable listing.
     * @type {string}
     * @memberof GetCatalogLookupResponseOffers
     */
    listingSlug?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetCatalogLookupResponseOffers
     */
    available?: number | null;
    /**
     * 
     * @type {GetCatalogLookupResponseCatalog}
     * @memberof GetCatalogLookupResponseOffers
     */
    catalog?: GetCatalogLookupResponseCatalog | null;
}

/**
* @export
* @enum {string}
*/
export enum GetCatalogLookupResponseOffersKindEnum {
    Listing = 'listing',
    Ask = 'ask'
}

export function GetCatalogLookupResponseOffersFromJSON(json: any): GetCatalogLookupResponseOffers {
    return GetCatalogLookupResponseOffersFromJSONTyped(json, false);
}

export function GetCatalogLookupResponseOffersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCatalogLookupResponseOffers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kind': json['kind'],
        'priceCents': json['priceCents'],
        'currency': json['currency'],
        'condition': !exists(json, 'condition') ? undefined : json['condition'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'url': json['url'],
        'listingSlug': !exists(json, 'listingSlug') ? undefined : json['listingSlug'],
        'available': !exists(json, 'available') ? undefined : json['available'],
        'catalog': !exists(json, 'catalog') ? undefined : GetCatalogLookupResponseCatalogFromJSON(json['catalog']),
    };
}

export function GetCatalogLookupResponseOffersToJSON(value?: GetCatalogLookupResponseOffers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'kind': value.kind,
        'priceCents': value.priceCents,
        'currency': value.currency,
        'condition': value.condition,
        'title': value.title,
        'imageUrl': value.imageUrl,
        'url': value.url,
        'listingSlug': value.listingSlug,
        'available': value.available,
        'catalog': GetCatalogLookupResponseCatalogToJSON(value.catalog),
    };
}

