/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCbxCreditResponse
 */
export interface GetCbxCreditResponse {
    /**
     * 
     * @type {number}
     * @memberof GetCbxCreditResponse
     */
    totalLimitCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetCbxCreditResponse
     */
    drawnCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetCbxCreditResponse
     */
    availableCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetCbxCreditResponse
     */
    rateBps: number;
    /**
     * 
     * @type {number}
     * @memberof GetCbxCreditResponse
     */
    termDays: number;
    /**
     * 
     * @type {string}
     * @memberof GetCbxCreditResponse
     */
    status: string;
}

export function GetCbxCreditResponseFromJSON(json: any): GetCbxCreditResponse {
    return GetCbxCreditResponseFromJSONTyped(json, false);
}

export function GetCbxCreditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCbxCreditResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalLimitCents': json['totalLimitCents'],
        'drawnCents': json['drawnCents'],
        'availableCents': json['availableCents'],
        'rateBps': json['rateBps'],
        'termDays': json['termDays'],
        'status': json['status'],
    };
}

export function GetCbxCreditResponseToJSON(value?: GetCbxCreditResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalLimitCents': value.totalLimitCents,
        'drawnCents': value.drawnCents,
        'availableCents': value.availableCents,
        'rateBps': value.rateBps,
        'termDays': value.termDays,
        'status': value.status,
    };
}

