/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetConnectionHealthResponseAnchors
 */
export interface GetConnectionHealthResponseAnchors {
    /**
     * What we were looking for. Empty ⇒ this platform is unmonitored.
     * @type {Array<string>}
     * @memberof GetConnectionHealthResponseAnchors
     */
    expected: Array<string>;
    /**
     * 
     * @type {Array<object>}
     * @memberof GetConnectionHealthResponseAnchors
     */
    observations: Array<object>;
    /**
     * Name found carrying a non-empty value — the only honest "logged in".
     * @type {Array<string>}
     * @memberof GetConnectionHealthResponseAnchors
     */
    present: Array<string>;
    /**
     * Name found, value is the empty string. The Whatnot class.
     * @type {Array<string>}
     * @memberof GetConnectionHealthResponseAnchors
     */
    empty: Array<string>;
    /**
     * Name not in the jar at all.
     * @type {Array<string>}
     * @memberof GetConnectionHealthResponseAnchors
     */
    missing: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GetConnectionHealthResponseAnchors
     */
    cookieCount: number;
    /**
     * Cookie names actually in the jar, truncated. This is the payload that turns
"anchors missing" into a diagnosis: if the jar holds 30 cookies and none
are ours, a rename is the likely story; if it holds three device cookies,
the browser is signed out. NAMES ONLY — never values.
     * @type {Array<string>}
     * @memberof GetConnectionHealthResponseAnchors
     */
    observedCookieNames: Array<string>;
}

export function GetConnectionHealthResponseAnchorsFromJSON(json: any): GetConnectionHealthResponseAnchors {
    return GetConnectionHealthResponseAnchorsFromJSONTyped(json, false);
}

export function GetConnectionHealthResponseAnchorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConnectionHealthResponseAnchors {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expected': json['expected'],
        'observations': json['observations'],
        'present': json['present'],
        'empty': json['empty'],
        'missing': json['missing'],
        'cookieCount': json['cookieCount'],
        'observedCookieNames': json['observedCookieNames'],
    };
}

export function GetConnectionHealthResponseAnchorsToJSON(value?: GetConnectionHealthResponseAnchors | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expected': value.expected,
        'observations': value.observations,
        'present': value.present,
        'empty': value.empty,
        'missing': value.missing,
        'cookieCount': value.cookieCount,
        'observedCookieNames': value.observedCookieNames,
    };
}

