/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCbxTreasuryResponse
 */
export interface GetCbxTreasuryResponse {
    /**
     * 
     * @type {Date}
     * @memberof GetCbxTreasuryResponse
     */
    takenAt: Date;
    /**
     * 
     * @type {number}
     * @memberof GetCbxTreasuryResponse
     */
    coverageBps: number;
    /**
     * 
     * @type {boolean}
     * @memberof GetCbxTreasuryResponse
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof GetCbxTreasuryResponse
     */
    reserveBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof GetCbxTreasuryResponse
     */
    outstandingBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof GetCbxTreasuryResponse
     */
    inFlightClaimBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof GetCbxTreasuryResponse
     */
    notes?: string | null;
}

export function GetCbxTreasuryResponseFromJSON(json: any): GetCbxTreasuryResponse {
    return GetCbxTreasuryResponseFromJSONTyped(json, false);
}

export function GetCbxTreasuryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCbxTreasuryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'takenAt': (new Date(json['takenAt'])),
        'coverageBps': json['coverageBps'],
        'ok': json['ok'],
        'reserveBaseUnits': json['reserveBaseUnits'],
        'outstandingBaseUnits': json['outstandingBaseUnits'],
        'inFlightClaimBaseUnits': json['inFlightClaimBaseUnits'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
    };
}

export function GetCbxTreasuryResponseToJSON(value?: GetCbxTreasuryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'takenAt': (value.takenAt.toISOString()),
        'coverageBps': value.coverageBps,
        'ok': value.ok,
        'reserveBaseUnits': value.reserveBaseUnits,
        'outstandingBaseUnits': value.outstandingBaseUnits,
        'inFlightClaimBaseUnits': value.inFlightClaimBaseUnits,
        'notes': value.notes,
    };
}

