/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetCategoryResponseMain,
    GetCategoryResponseMainFromJSON,
    GetCategoryResponseMainFromJSONTyped,
    GetCategoryResponseMainToJSON,
} from './GetCategoryResponseMain';

/**
 * 
 * @export
 * @interface GetCategoryResponse
 */
export interface GetCategoryResponse {
    /**
     * 
     * @type {GetCategoryResponseMain}
     * @memberof GetCategoryResponse
     */
    main: GetCategoryResponseMain;
    /**
     * 
     * @type {object}
     * @memberof GetCategoryResponse
     */
    sub: object;
}

export function GetCategoryResponseFromJSON(json: any): GetCategoryResponse {
    return GetCategoryResponseFromJSONTyped(json, false);
}

export function GetCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCategoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'main': GetCategoryResponseMainFromJSON(json['main']),
        'sub': json['sub'],
    };
}

export function GetCategoryResponseToJSON(value?: GetCategoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'main': GetCategoryResponseMainToJSON(value.main),
        'sub': value.sub,
    };
}

