/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCbxAdCreditResponse
 */
export interface GetCbxAdCreditResponse {
    /**
     * 
     * @type {number}
     * @memberof GetCbxAdCreditResponse
     */
    balanceCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetCbxAdCreditResponse
     */
    poolShareBps: number;
}

export function GetCbxAdCreditResponseFromJSON(json: any): GetCbxAdCreditResponse {
    return GetCbxAdCreditResponseFromJSONTyped(json, false);
}

export function GetCbxAdCreditResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCbxAdCreditResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'balanceCents': json['balanceCents'],
        'poolShareBps': json['poolShareBps'],
    };
}

export function GetCbxAdCreditResponseToJSON(value?: GetCbxAdCreditResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'balanceCents': value.balanceCents,
        'poolShareBps': value.poolShareBps,
    };
}

