/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetInventoryLabelStatResponseLabels,
    GetInventoryLabelStatResponseLabelsFromJSON,
    GetInventoryLabelStatResponseLabelsFromJSONTyped,
    GetInventoryLabelStatResponseLabelsToJSON,
} from './GetInventoryLabelStatResponseLabels';

/**
 * 
 * @export
 * @interface GetInventoryLabelStatResponse
 */
export interface GetInventoryLabelStatResponse {
    /**
     * 
     * @type {Array<GetInventoryLabelStatResponseLabels>}
     * @memberof GetInventoryLabelStatResponse
     */
    labels: Array<GetInventoryLabelStatResponseLabels>;
}

export function GetInventoryLabelStatResponseFromJSON(json: any): GetInventoryLabelStatResponse {
    return GetInventoryLabelStatResponseFromJSONTyped(json, false);
}

export function GetInventoryLabelStatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInventoryLabelStatResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'labels': ((json['labels'] as Array<any>).map(GetInventoryLabelStatResponseLabelsFromJSON)),
    };
}

export function GetInventoryLabelStatResponseToJSON(value?: GetInventoryLabelStatResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'labels': ((value.labels as Array<any>).map(GetInventoryLabelStatResponseLabelsToJSON)),
    };
}

