/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetListingVariationGroupResponseGroup,
    GetListingVariationGroupResponseGroupFromJSON,
    GetListingVariationGroupResponseGroupFromJSONTyped,
    GetListingVariationGroupResponseGroupToJSON,
} from './GetListingVariationGroupResponseGroup';

/**
 * 
 * @export
 * @interface GetListingVariationGroupResponse
 */
export interface GetListingVariationGroupResponse {
    /**
     * 
     * @type {GetListingVariationGroupResponseGroup}
     * @memberof GetListingVariationGroupResponse
     */
    group?: GetListingVariationGroupResponseGroup | null;
}

export function GetListingVariationGroupResponseFromJSON(json: any): GetListingVariationGroupResponse {
    return GetListingVariationGroupResponseFromJSONTyped(json, false);
}

export function GetListingVariationGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetListingVariationGroupResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'group': !exists(json, 'group') ? undefined : GetListingVariationGroupResponseGroupFromJSON(json['group']),
    };
}

export function GetListingVariationGroupResponseToJSON(value?: GetListingVariationGroupResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group': GetListingVariationGroupResponseGroupToJSON(value.group),
    };
}

