/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMarketVariantBookResponseBids
 */
export interface GetMarketVariantBookResponseBids {
    /**
     * 
     * @type {number}
     * @memberof GetMarketVariantBookResponseBids
     */
    priceCents: number;
    /**
     * 
     * @type {number}
     * @memberof GetMarketVariantBookResponseBids
     */
    count: number;
}

export function GetMarketVariantBookResponseBidsFromJSON(json: any): GetMarketVariantBookResponseBids {
    return GetMarketVariantBookResponseBidsFromJSONTyped(json, false);
}

export function GetMarketVariantBookResponseBidsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMarketVariantBookResponseBids {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'priceCents': json['priceCents'],
        'count': json['count'],
    };
}

export function GetMarketVariantBookResponseBidsToJSON(value?: GetMarketVariantBookResponseBids | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'priceCents': value.priceCents,
        'count': value.count,
    };
}

