/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    GetOauthInitResponseOneOf,
    GetOauthInitResponseOneOfFromJSON,
    GetOauthInitResponseOneOfFromJSONTyped,
    GetOauthInitResponseOneOfToJSON,
} from './GetOauthInitResponseOneOf';
import {
    GetOauthInitResponseOneOf1,
    GetOauthInitResponseOneOf1FromJSON,
    GetOauthInitResponseOneOf1FromJSONTyped,
    GetOauthInitResponseOneOf1ToJSON,
} from './GetOauthInitResponseOneOf1';
import {
    GetOauthInitResponseOneOf2,
    GetOauthInitResponseOneOf2FromJSON,
    GetOauthInitResponseOneOf2FromJSONTyped,
    GetOauthInitResponseOneOf2ToJSON,
} from './GetOauthInitResponseOneOf2';
import {
    GetOauthInitResponseOneOf3,
    GetOauthInitResponseOneOf3FromJSON,
    GetOauthInitResponseOneOf3FromJSONTyped,
    GetOauthInitResponseOneOf3ToJSON,
} from './GetOauthInitResponseOneOf3';

/**
 * @type GetOauthInitResponse
 * 
 * @export
 */
export type GetOauthInitResponse = GetOauthInitResponseOneOf | GetOauthInitResponseOneOf1 | GetOauthInitResponseOneOf2 | GetOauthInitResponseOneOf3;

export function GetOauthInitResponseFromJSON(json: any): GetOauthInitResponse {
    return GetOauthInitResponseFromJSONTyped(json, false);
}

export function GetOauthInitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOauthInitResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...GetOauthInitResponseOneOfFromJSONTyped(json, true), ...GetOauthInitResponseOneOf1FromJSONTyped(json, true), ...GetOauthInitResponseOneOf2FromJSONTyped(json, true), ...GetOauthInitResponseOneOf3FromJSONTyped(json, true) };
}

export function GetOauthInitResponseToJSON(value?: GetOauthInitResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...GetOauthInitResponseOneOfToJSON(value), ...GetOauthInitResponseOneOf1ToJSON(value), ...GetOauthInitResponseOneOf2ToJSON(value), ...GetOauthInitResponseOneOf3ToJSON(value) };
}

