/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOauthInitResponseOneOf1
 */
export interface GetOauthInitResponseOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof GetOauthInitResponseOneOf1
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof GetOauthInitResponseOneOf1
     */
    correlationId: string;
}

export function GetOauthInitResponseOneOf1FromJSON(json: any): GetOauthInitResponseOneOf1 {
    return GetOauthInitResponseOneOf1FromJSONTyped(json, false);
}

export function GetOauthInitResponseOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOauthInitResponseOneOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'correlationId': json['correlationId'],
    };
}

export function GetOauthInitResponseOneOf1ToJSON(value?: GetOauthInitResponseOneOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'correlationId': value.correlationId,
    };
}

