/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetOrderEvidenceResponseSealAssessment,
    GetOrderEvidenceResponseSealAssessmentFromJSON,
    GetOrderEvidenceResponseSealAssessmentFromJSONTyped,
    GetOrderEvidenceResponseSealAssessmentToJSON,
} from './GetOrderEvidenceResponseSealAssessment';

/**
 * 
 * @export
 * @interface GetOrderEvidenceResponseSeal
 */
export interface GetOrderEvidenceResponseSeal {
    /**
     * 
     * @type {GetOrderEvidenceResponseSealAssessment}
     * @memberof GetOrderEvidenceResponseSeal
     */
    assessment: GetOrderEvidenceResponseSealAssessment;
    /**
     * How many packing frames were searched to find the dispatch frame shot
closest to the arrival angle. Null when the dispatch reading was simply
the frame the recorder ended on.

Surfaced rather than kept internal: "the best of eighteen frames
matched" is a weaker claim than "the frame we took matched", and a
reviewer has to be able to tell them apart. See frame-match.ts.
     * @type {number}
     * @memberof GetOrderEvidenceResponseSeal
     */
    dispatchSearchedFrames?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderEvidenceResponseSeal
     */
    hasDispatch: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetOrderEvidenceResponseSeal
     */
    hasArrival: boolean;
    /**
     * A courier photo exists, even if the seal was not legible in it.
     * @type {boolean}
     * @memberof GetOrderEvidenceResponseSeal
     */
    hasCourierPhoto: boolean;
}

export function GetOrderEvidenceResponseSealFromJSON(json: any): GetOrderEvidenceResponseSeal {
    return GetOrderEvidenceResponseSealFromJSONTyped(json, false);
}

export function GetOrderEvidenceResponseSealFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrderEvidenceResponseSeal {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assessment': GetOrderEvidenceResponseSealAssessmentFromJSON(json['assessment']),
        'dispatchSearchedFrames': !exists(json, 'dispatchSearchedFrames') ? undefined : json['dispatchSearchedFrames'],
        'hasDispatch': json['hasDispatch'],
        'hasArrival': json['hasArrival'],
        'hasCourierPhoto': json['hasCourierPhoto'],
    };
}

export function GetOrderEvidenceResponseSealToJSON(value?: GetOrderEvidenceResponseSeal | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assessment': GetOrderEvidenceResponseSealAssessmentToJSON(value.assessment),
        'dispatchSearchedFrames': value.dispatchSearchedFrames,
        'hasDispatch': value.hasDispatch,
        'hasArrival': value.hasArrival,
        'hasCourierPhoto': value.hasCourierPhoto,
    };
}

