/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Only the count. `capitalCents` is the seller's spend and never leaves.
 * @export
 * @interface GetSpatialPublicResponseStats
 */
export interface GetSpatialPublicResponseStats {
    /**
     * 
     * @type {number}
     * @memberof GetSpatialPublicResponseStats
     */
    itemCount: number;
}

export function GetSpatialPublicResponseStatsFromJSON(json: any): GetSpatialPublicResponseStats {
    return GetSpatialPublicResponseStatsFromJSONTyped(json, false);
}

export function GetSpatialPublicResponseStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpatialPublicResponseStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemCount': json['itemCount'],
    };
}

export function GetSpatialPublicResponseStatsToJSON(value?: GetSpatialPublicResponseStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'itemCount': value.itemCount,
    };
}

