/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetTaxScheduleCResponseCounts,
    GetTaxScheduleCResponseCountsFromJSON,
    GetTaxScheduleCResponseCountsFromJSONTyped,
    GetTaxScheduleCResponseCountsToJSON,
} from './GetTaxScheduleCResponseCounts';
import {
    GetTaxScheduleCResponseExpenses,
    GetTaxScheduleCResponseExpensesFromJSON,
    GetTaxScheduleCResponseExpensesFromJSONTyped,
    GetTaxScheduleCResponseExpensesToJSON,
} from './GetTaxScheduleCResponseExpenses';

/**
 * 
 * @export
 * @interface GetTaxScheduleCResponse
 */
export interface GetTaxScheduleCResponse {
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponse
     */
    year: number;
    /**
     * 
     * @type {string}
     * @memberof GetTaxScheduleCResponse
     */
    businessName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetTaxScheduleCResponse
     */
    ein?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetTaxScheduleCResponse
     */
    address?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponse
     */
    grossReceipts: number;
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponse
     */
    returnsAndAllowances: number;
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponse
     */
    netSales: number;
    /**
     * 
     * @type {GetTaxScheduleCResponseExpenses}
     * @memberof GetTaxScheduleCResponse
     */
    expenses: GetTaxScheduleCResponseExpenses;
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponse
     */
    netProfit: number;
    /**
     * 
     * @type {GetTaxScheduleCResponseCounts}
     * @memberof GetTaxScheduleCResponse
     */
    counts: GetTaxScheduleCResponseCounts;
}

export function GetTaxScheduleCResponseFromJSON(json: any): GetTaxScheduleCResponse {
    return GetTaxScheduleCResponseFromJSONTyped(json, false);
}

export function GetTaxScheduleCResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTaxScheduleCResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'year': json['year'],
        'businessName': !exists(json, 'businessName') ? undefined : json['businessName'],
        'ein': !exists(json, 'ein') ? undefined : json['ein'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'grossReceipts': json['grossReceipts'],
        'returnsAndAllowances': json['returnsAndAllowances'],
        'netSales': json['netSales'],
        'expenses': GetTaxScheduleCResponseExpensesFromJSON(json['expenses']),
        'netProfit': json['netProfit'],
        'counts': GetTaxScheduleCResponseCountsFromJSON(json['counts']),
    };
}

export function GetTaxScheduleCResponseToJSON(value?: GetTaxScheduleCResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'year': value.year,
        'businessName': value.businessName,
        'ein': value.ein,
        'address': value.address,
        'grossReceipts': value.grossReceipts,
        'returnsAndAllowances': value.returnsAndAllowances,
        'netSales': value.netSales,
        'expenses': GetTaxScheduleCResponseExpensesToJSON(value.expenses),
        'netProfit': value.netProfit,
        'counts': GetTaxScheduleCResponseCountsToJSON(value.counts),
    };
}

