/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBuyerMonitorMatchesItem
 */
export interface ListBuyerMonitorMatchesItem {
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorMatchesItem
     */
    listingSlug: string;
    /**
     * 
     * @type {number}
     * @memberof ListBuyerMonitorMatchesItem
     */
    triggerPriceCents: number;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorMatchesItem
     */
    deliveredAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorMatchesItem
     */
    createdAt: string;
}

export function ListBuyerMonitorMatchesItemFromJSON(json: any): ListBuyerMonitorMatchesItem {
    return ListBuyerMonitorMatchesItemFromJSONTyped(json, false);
}

export function ListBuyerMonitorMatchesItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBuyerMonitorMatchesItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listingSlug': json['listingSlug'],
        'triggerPriceCents': json['triggerPriceCents'],
        'deliveredAt': !exists(json, 'deliveredAt') ? undefined : json['deliveredAt'],
        'createdAt': json['createdAt'],
    };
}

export function ListBuyerMonitorMatchesItemToJSON(value?: ListBuyerMonitorMatchesItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listingSlug': value.listingSlug,
        'triggerPriceCents': value.triggerPriceCents,
        'deliveredAt': value.deliveredAt,
        'createdAt': value.createdAt,
    };
}

