/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListImportsItemFilters
 */
export interface ListImportsItemFilters {
    /**
     * 
     * @type {string}
     * @memberof ListImportsItemFilters
     */
    listedAfter?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListImportsItemFilters
     */
    listedBefore?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListImportsItemFilters
     */
    minPrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ListImportsItemFilters
     */
    maxPrice?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListImportsItemFilters
     */
    conditionIncludes?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof ListImportsItemFilters
     */
    maxImport?: number | null;
}

export function ListImportsItemFiltersFromJSON(json: any): ListImportsItemFilters {
    return ListImportsItemFiltersFromJSONTyped(json, false);
}

export function ListImportsItemFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListImportsItemFilters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listedAfter': !exists(json, 'listedAfter') ? undefined : json['listedAfter'],
        'listedBefore': !exists(json, 'listedBefore') ? undefined : json['listedBefore'],
        'minPrice': !exists(json, 'minPrice') ? undefined : json['minPrice'],
        'maxPrice': !exists(json, 'maxPrice') ? undefined : json['maxPrice'],
        'conditionIncludes': !exists(json, 'conditionIncludes') ? undefined : json['conditionIncludes'],
        'maxImport': !exists(json, 'maxImport') ? undefined : json['maxImport'],
    };
}

export function ListImportsItemFiltersToJSON(value?: ListImportsItemFilters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listedAfter': value.listedAfter,
        'listedBefore': value.listedBefore,
        'minPrice': value.minPrice,
        'maxPrice': value.maxPrice,
        'conditionIncludes': value.conditionIncludes,
        'maxImport': value.maxImport,
    };
}

