/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCbxEarnTiersItem
 */
export interface ListCbxEarnTiersItem {
    /**
     * 
     * @type {string}
     * @memberof ListCbxEarnTiersItem
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxEarnTiersItem
     */
    label: string;
    /**
     * 
     * @type {number}
     * @memberof ListCbxEarnTiersItem
     */
    maturationDays: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxEarnTiersItem
     */
    earnRateBps: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListCbxEarnTiersItem
     */
    isDefault: boolean;
}

export function ListCbxEarnTiersItemFromJSON(json: any): ListCbxEarnTiersItem {
    return ListCbxEarnTiersItemFromJSONTyped(json, false);
}

export function ListCbxEarnTiersItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCbxEarnTiersItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'label': json['label'],
        'maturationDays': json['maturationDays'],
        'earnRateBps': json['earnRateBps'],
        'isDefault': json['isDefault'],
    };
}

export function ListCbxEarnTiersItemToJSON(value?: ListCbxEarnTiersItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'label': value.label,
        'maturationDays': value.maturationDays,
        'earnRateBps': value.earnRateBps,
        'isDefault': value.isDefault,
    };
}

