/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListInsightByPlatformItem
 */
export interface ListInsightByPlatformItem {
    /**
     * 
     * @type {string}
     * @memberof ListInsightByPlatformItem
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof ListInsightByPlatformItem
     */
    sales: string;
    /**
     * 
     * @type {string}
     * @memberof ListInsightByPlatformItem
     */
    grossCents: string;
    /**
     * 
     * @type {number}
     * @memberof ListInsightByPlatformItem
     */
    avgDaysToSale: number;
    /**
     * 
     * @type {number}
     * @memberof ListInsightByPlatformItem
     */
    avgSaleCents: number;
    /**
     * 
     * @type {string}
     * @memberof ListInsightByPlatformItem
     */
    netCents: string;
}

export function ListInsightByPlatformItemFromJSON(json: any): ListInsightByPlatformItem {
    return ListInsightByPlatformItemFromJSONTyped(json, false);
}

export function ListInsightByPlatformItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInsightByPlatformItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'platform': json['platform'],
        'sales': json['sales'],
        'grossCents': json['gross_cents'],
        'avgDaysToSale': json['avg_days_to_sale'],
        'avgSaleCents': json['avg_sale_cents'],
        'netCents': json['net_cents'],
    };
}

export function ListInsightByPlatformItemToJSON(value?: ListInsightByPlatformItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'platform': value.platform,
        'sales': value.sales,
        'gross_cents': value.grossCents,
        'avg_days_to_sale': value.avgDaysToSale,
        'avg_sale_cents': value.avgSaleCents,
        'net_cents': value.netCents,
    };
}

