/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListConnectedAppsItem
 */
export interface ListConnectedAppsItem {
    /**
     * 
     * @type {string}
     * @memberof ListConnectedAppsItem
     */
    grantId: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListConnectedAppsItem
     */
    scopes: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ListConnectedAppsItem
     */
    connectedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ListConnectedAppsItem
     */
    lastUsedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ListConnectedAppsItem
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof ListConnectedAppsItem
     */
    appName: string;
    /**
     * 
     * @type {string}
     * @memberof ListConnectedAppsItem
     */
    appDescription?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListConnectedAppsItem
     */
    homepageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListConnectedAppsItem
     */
    developerName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListConnectedAppsItem
     */
    developerEmail: string;
}

export function ListConnectedAppsItemFromJSON(json: any): ListConnectedAppsItem {
    return ListConnectedAppsItemFromJSONTyped(json, false);
}

export function ListConnectedAppsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectedAppsItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'grantId': json['grantId'],
        'scopes': json['scopes'],
        'connectedAt': (new Date(json['connectedAt'])),
        'lastUsedAt': !exists(json, 'lastUsedAt') ? undefined : (json['lastUsedAt'] === null ? null : new Date(json['lastUsedAt'])),
        'appId': json['appId'],
        'appName': json['appName'],
        'appDescription': !exists(json, 'appDescription') ? undefined : json['appDescription'],
        'homepageUrl': !exists(json, 'homepageUrl') ? undefined : json['homepageUrl'],
        'developerName': !exists(json, 'developerName') ? undefined : json['developerName'],
        'developerEmail': json['developerEmail'],
    };
}

export function ListConnectedAppsItemToJSON(value?: ListConnectedAppsItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'grantId': value.grantId,
        'scopes': value.scopes,
        'connectedAt': (value.connectedAt.toISOString()),
        'lastUsedAt': value.lastUsedAt === undefined ? undefined : (value.lastUsedAt === null ? null : value.lastUsedAt.toISOString()),
        'appId': value.appId,
        'appName': value.appName,
        'appDescription': value.appDescription,
        'homepageUrl': value.homepageUrl,
        'developerName': value.developerName,
        'developerEmail': value.developerEmail,
    };
}

