/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListWorkflowChainsItemSteps
 */
export interface ListWorkflowChainsItemSteps {
    /**
     * 
     * @type {string}
     * @memberof ListWorkflowChainsItemSteps
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ListWorkflowChainsItemSteps
     */
    position: number;
    /**
     * 
     * @type {string}
     * @memberof ListWorkflowChainsItemSteps
     */
    chainId: string;
    /**
     * 
     * @type {string}
     * @memberof ListWorkflowChainsItemSteps
     */
    stepType: string;
    /**
     * 
     * @type {string}
     * @memberof ListWorkflowChainsItemSteps
     */
    actionId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListWorkflowChainsItemSteps
     */
    waitMs?: number | null;
}

export function ListWorkflowChainsItemStepsFromJSON(json: any): ListWorkflowChainsItemSteps {
    return ListWorkflowChainsItemStepsFromJSONTyped(json, false);
}

export function ListWorkflowChainsItemStepsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWorkflowChainsItemSteps {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'position': json['position'],
        'chainId': json['chainId'],
        'stepType': json['stepType'],
        'actionId': !exists(json, 'actionId') ? undefined : json['actionId'],
        'waitMs': !exists(json, 'waitMs') ? undefined : json['waitMs'],
    };
}

export function ListWorkflowChainsItemStepsToJSON(value?: ListWorkflowChainsItemSteps | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'position': value.position,
        'chainId': value.chainId,
        'stepType': value.stepType,
        'actionId': value.actionId,
        'waitMs': value.waitMs,
    };
}

