/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCbxStakeTiersItem
 */
export interface ListCbxStakeTiersItem {
    /**
     * 
     * @type {string}
     * @memberof ListCbxStakeTiersItem
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxStakeTiersItem
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxStakeTiersItem
     */
    minBaseUnits: string;
    /**
     * 
     * @type {number}
     * @memberof ListCbxStakeTiersItem
     */
    feeDiscountBps: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxStakeTiersItem
     */
    earnBoostBps: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxStakeTiersItem
     */
    cooldownDays: number;
}

export function ListCbxStakeTiersItemFromJSON(json: any): ListCbxStakeTiersItem {
    return ListCbxStakeTiersItemFromJSONTyped(json, false);
}

export function ListCbxStakeTiersItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCbxStakeTiersItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'label': json['label'],
        'minBaseUnits': json['minBaseUnits'],
        'feeDiscountBps': json['feeDiscountBps'],
        'earnBoostBps': json['earnBoostBps'],
        'cooldownDays': json['cooldownDays'],
    };
}

export function ListCbxStakeTiersItemToJSON(value?: ListCbxStakeTiersItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'label': value.label,
        'minBaseUnits': value.minBaseUnits,
        'feeDiscountBps': value.feeDiscountBps,
        'earnBoostBps': value.earnBoostBps,
        'cooldownDays': value.cooldownDays,
    };
}

