/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBuyerCartItem
 */
export interface ListBuyerCartItem {
    /**
     * 
     * @type {boolean}
     * @memberof ListBuyerCartItem
     */
    available: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerCartItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerCartItem
     */
    platformListingId: string;
    /**
     * 
     * @type {number}
     * @memberof ListBuyerCartItem
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof ListBuyerCartItem
     */
    unitPriceCents: number;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerCartItem
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerCartItem
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerCartItem
     */
    listingStatus?: string | null;
}

export function ListBuyerCartItemFromJSON(json: any): ListBuyerCartItem {
    return ListBuyerCartItemFromJSONTyped(json, false);
}

export function ListBuyerCartItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBuyerCartItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'available': json['available'],
        'id': json['id'],
        'platformListingId': json['platformListingId'],
        'quantity': json['quantity'],
        'unitPriceCents': json['unitPriceCents'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'listingStatus': !exists(json, 'listingStatus') ? undefined : json['listingStatus'],
    };
}

export function ListBuyerCartItemToJSON(value?: ListBuyerCartItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'available': value.available,
        'id': value.id,
        'platformListingId': value.platformListingId,
        'quantity': value.quantity,
        'unitPriceCents': value.unitPriceCents,
        'slug': value.slug,
        'title': value.title,
        'listingStatus': value.listingStatus,
    };
}

