/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCbxSubjectLedgerItem
 */
export interface ListCbxSubjectLedgerItem {
    /**
     * 
     * @type {string}
     * @memberof ListCbxSubjectLedgerItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxSubjectLedgerItem
     */
    deltaBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxSubjectLedgerItem
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxSubjectLedgerItem
     */
    memo?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListCbxSubjectLedgerItem
     */
    createdAt: Date;
}

export function ListCbxSubjectLedgerItemFromJSON(json: any): ListCbxSubjectLedgerItem {
    return ListCbxSubjectLedgerItemFromJSONTyped(json, false);
}

export function ListCbxSubjectLedgerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCbxSubjectLedgerItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'deltaBaseUnits': json['deltaBaseUnits'],
        'kind': json['kind'],
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ListCbxSubjectLedgerItemToJSON(value?: ListCbxSubjectLedgerItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'deltaBaseUnits': value.deltaBaseUnits,
        'kind': value.kind,
        'memo': value.memo,
        'createdAt': (value.createdAt.toISOString()),
    };
}

