/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListConnectionsItem
 */
export interface ListConnectionsItem {
    /**
     * 
     * @type {string}
     * @memberof ListConnectionsItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListConnectionsItem
     */
    platform: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListConnectionsItem
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListConnectionsItem
     */
    shopUrl?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListConnectionsItem
     */
    lastSeenActive?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListConnectionsItem
     */
    tokenExpiresAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListConnectionsItem
     */
    createdAt?: Date | null;
}

export function ListConnectionsItemFromJSON(json: any): ListConnectionsItem {
    return ListConnectionsItemFromJSONTyped(json, false);
}

export function ListConnectionsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListConnectionsItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'platform': json['platform'],
        'isActive': json['isActive'],
        'shopUrl': !exists(json, 'shopUrl') ? undefined : json['shopUrl'],
        'lastSeenActive': !exists(json, 'lastSeenActive') ? undefined : (json['lastSeenActive'] === null ? null : new Date(json['lastSeenActive'])),
        'tokenExpiresAt': !exists(json, 'tokenExpiresAt') ? undefined : (json['tokenExpiresAt'] === null ? null : new Date(json['tokenExpiresAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (json['createdAt'] === null ? null : new Date(json['createdAt'])),
    };
}

export function ListConnectionsItemToJSON(value?: ListConnectionsItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'platform': value.platform,
        'isActive': value.isActive,
        'shopUrl': value.shopUrl,
        'lastSeenActive': value.lastSeenActive === undefined ? undefined : (value.lastSeenActive === null ? null : value.lastSeenActive.toISOString()),
        'tokenExpiresAt': value.tokenExpiresAt === undefined ? undefined : (value.tokenExpiresAt === null ? null : value.tokenExpiresAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt === null ? null : value.createdAt.toISOString()),
    };
}

