/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSavedViewResponse
 */
export interface UpdateSavedViewResponse {
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedViewResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedViewResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedViewResponse
     */
    resource: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedViewResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedViewResponse
     */
    viewMode?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSavedViewResponse
     */
    isDefault: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpdateSavedViewResponse
     */
    sortOrder: number;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSavedViewResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSavedViewResponse
     */
    updatedAt: Date;
}

export function UpdateSavedViewResponseFromJSON(json: any): UpdateSavedViewResponse {
    return UpdateSavedViewResponseFromJSONTyped(json, false);
}

export function UpdateSavedViewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSavedViewResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'userId': json['userId'],
        'resource': json['resource'],
        'name': json['name'],
        'viewMode': !exists(json, 'viewMode') ? undefined : json['viewMode'],
        'isDefault': json['isDefault'],
        'sortOrder': json['sortOrder'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function UpdateSavedViewResponseToJSON(value?: UpdateSavedViewResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'resource': value.resource,
        'name': value.name,
        'viewMode': value.viewMode,
        'isDefault': value.isDefault,
        'sortOrder': value.sortOrder,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
    };
}

