/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ListInventoryItemCategory,
    ListInventoryItemCategoryFromJSON,
    ListInventoryItemCategoryFromJSONTyped,
    ListInventoryItemCategoryToJSON,
} from './ListInventoryItemCategory';

/**
 * 
 * @export
 * @interface CreateInventoryResponse
 */
export interface CreateInventoryResponse {
    /**
     * 
     * @type {ListInventoryItemCategory}
     * @memberof CreateInventoryResponse
     */
    category?: ListInventoryItemCategory | null;
}

export function CreateInventoryResponseFromJSON(json: any): CreateInventoryResponse {
    return CreateInventoryResponseFromJSONTyped(json, false);
}

export function CreateInventoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInventoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'category': !exists(json, 'category') ? undefined : ListInventoryItemCategoryFromJSON(json['category']),
    };
}

export function CreateInventoryResponseToJSON(value?: CreateInventoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'category': ListInventoryItemCategoryToJSON(value.category),
    };
}

