/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxSubjectStakeUnstakeResponse
 */
export interface CreateCbxSubjectStakeUnstakeResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxSubjectStakeUnstakeResponse
     */
    unlocksAt: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxSubjectStakeUnstakeResponse
     */
    cooldownDays: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxSubjectStakeUnstakeResponse
     */
    baseUnits: string;
}

export function CreateCbxSubjectStakeUnstakeResponseFromJSON(json: any): CreateCbxSubjectStakeUnstakeResponse {
    return CreateCbxSubjectStakeUnstakeResponseFromJSONTyped(json, false);
}

export function CreateCbxSubjectStakeUnstakeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxSubjectStakeUnstakeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'unlocksAt': json['unlocksAt'],
        'cooldownDays': json['cooldownDays'],
        'baseUnits': json['baseUnits'],
    };
}

export function CreateCbxSubjectStakeUnstakeResponseToJSON(value?: CreateCbxSubjectStakeUnstakeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'unlocksAt': value.unlocksAt,
        'cooldownDays': value.cooldownDays,
        'baseUnits': value.baseUnits,
    };
}

