/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxClaimQuoteResponse
 */
export interface CreateCbxClaimQuoteResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimQuoteResponse
     */
    requestedBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimQuoteResponse
     */
    serviceFeeBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimQuoteResponse
     */
    networkFeeBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimQuoteResponse
     */
    netBaseUnits: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxClaimQuoteResponse
     */
    requestedCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxClaimQuoteResponse
     */
    serviceFeeCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxClaimQuoteResponse
     */
    networkFeeCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxClaimQuoteResponse
     */
    netCents: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxClaimQuoteResponse
     */
    appliedBound: string;
}

export function CreateCbxClaimQuoteResponseFromJSON(json: any): CreateCbxClaimQuoteResponse {
    return CreateCbxClaimQuoteResponseFromJSONTyped(json, false);
}

export function CreateCbxClaimQuoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxClaimQuoteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'requestedBaseUnits': json['requestedBaseUnits'],
        'serviceFeeBaseUnits': json['serviceFeeBaseUnits'],
        'networkFeeBaseUnits': json['networkFeeBaseUnits'],
        'netBaseUnits': json['netBaseUnits'],
        'requestedCents': json['requestedCents'],
        'serviceFeeCents': json['serviceFeeCents'],
        'networkFeeCents': json['networkFeeCents'],
        'netCents': json['netCents'],
        'appliedBound': json['appliedBound'],
    };
}

export function CreateCbxClaimQuoteResponseToJSON(value?: CreateCbxClaimQuoteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'requestedBaseUnits': value.requestedBaseUnits,
        'serviceFeeBaseUnits': value.serviceFeeBaseUnits,
        'networkFeeBaseUnits': value.networkFeeBaseUnits,
        'netBaseUnits': value.netBaseUnits,
        'requestedCents': value.requestedCents,
        'serviceFeeCents': value.serviceFeeCents,
        'networkFeeCents': value.networkFeeCents,
        'netCents': value.netCents,
        'appliedBound': value.appliedBound,
    };
}

