/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateEmbedKeyResponse
 */
export interface CreateEmbedKeyResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateEmbedKeyResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmbedKeyResponse
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmbedKeyResponse
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateEmbedKeyResponse
     */
    allowedOrigins: Array<string>;
}

export function CreateEmbedKeyResponseFromJSON(json: any): CreateEmbedKeyResponse {
    return CreateEmbedKeyResponseFromJSONTyped(json, false);
}

export function CreateEmbedKeyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEmbedKeyResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'key': json['key'],
        'name': json['name'],
        'allowedOrigins': json['allowedOrigins'],
    };
}

export function CreateEmbedKeyResponseToJSON(value?: CreateEmbedKeyResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'key': value.key,
        'name': value.name,
        'allowedOrigins': value.allowedOrigins,
    };
}

