/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateConnectionEmailImapTestResponse
 */
export interface CreateConnectionEmailImapTestResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateConnectionEmailImapTestResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateConnectionEmailImapTestResponse
     */
    message: string;
}

export function CreateConnectionEmailImapTestResponseFromJSON(json: any): CreateConnectionEmailImapTestResponse {
    return CreateConnectionEmailImapTestResponseFromJSONTyped(json, false);
}

export function CreateConnectionEmailImapTestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateConnectionEmailImapTestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
    };
}

export function CreateConnectionEmailImapTestResponseToJSON(value?: CreateConnectionEmailImapTestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
    };
}

