/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateListingImportByUrlResponseListing,
    CreateListingImportByUrlResponseListingFromJSON,
    CreateListingImportByUrlResponseListingFromJSONTyped,
    CreateListingImportByUrlResponseListingToJSON,
} from './CreateListingImportByUrlResponseListing';

/**
 * 
 * @export
 * @interface CreateListingImportByUrlResponse
 */
export interface CreateListingImportByUrlResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateListingImportByUrlResponse
     */
    outcome: string;
    /**
     * 
     * @type {CreateListingImportByUrlResponseListing}
     * @memberof CreateListingImportByUrlResponse
     */
    listing?: CreateListingImportByUrlResponseListing | null;
}

export function CreateListingImportByUrlResponseFromJSON(json: any): CreateListingImportByUrlResponse {
    return CreateListingImportByUrlResponseFromJSONTyped(json, false);
}

export function CreateListingImportByUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateListingImportByUrlResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'outcome': json['outcome'],
        'listing': !exists(json, 'listing') ? undefined : CreateListingImportByUrlResponseListingFromJSON(json['listing']),
    };
}

export function CreateListingImportByUrlResponseToJSON(value?: CreateListingImportByUrlResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'outcome': value.outcome,
        'listing': CreateListingImportByUrlResponseListingToJSON(value.listing),
    };
}

