/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateBuyerIdentifyResponseIdentifier
 */
export interface CreateBuyerIdentifyResponseIdentifier {
    /**
     * 
     * @type {string}
     * @memberof CreateBuyerIdentifyResponseIdentifier
     */
    ns: CreateBuyerIdentifyResponseIdentifierNsEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateBuyerIdentifyResponseIdentifier
     */
    value: string;
}

/**
* @export
* @enum {string}
*/
export enum CreateBuyerIdentifyResponseIdentifierNsEnum {
    StyleCode = 'style_code',
    Gtin = 'gtin',
    LegoSet = 'lego_set',
    Tcgplayer = 'tcgplayer',
    Discogs = 'discogs',
    Asin = 'asin'
}

export function CreateBuyerIdentifyResponseIdentifierFromJSON(json: any): CreateBuyerIdentifyResponseIdentifier {
    return CreateBuyerIdentifyResponseIdentifierFromJSONTyped(json, false);
}

export function CreateBuyerIdentifyResponseIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateBuyerIdentifyResponseIdentifier {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ns': json['ns'],
        'value': json['value'],
    };
}

export function CreateBuyerIdentifyResponseIdentifierToJSON(value?: CreateBuyerIdentifyResponseIdentifier | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ns': value.ns,
        'value': value.value,
    };
}

