/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateCbxSubjectSpendPlanResponseLegs,
    CreateCbxSubjectSpendPlanResponseLegsFromJSON,
    CreateCbxSubjectSpendPlanResponseLegsFromJSONTyped,
    CreateCbxSubjectSpendPlanResponseLegsToJSON,
} from './CreateCbxSubjectSpendPlanResponseLegs';

/**
 * 
 * @export
 * @interface CreateCbxSubjectSpendPlanResponse
 */
export interface CreateCbxSubjectSpendPlanResponse {
    /**
     * 
     * @type {Array<CreateCbxSubjectSpendPlanResponseLegs>}
     * @memberof CreateCbxSubjectSpendPlanResponse
     */
    legs: Array<CreateCbxSubjectSpendPlanResponseLegs>;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxSubjectSpendPlanResponse
     */
    shortfallBaseUnits: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxSubjectSpendPlanResponse
     */
    fullyFunded: boolean;
}

export function CreateCbxSubjectSpendPlanResponseFromJSON(json: any): CreateCbxSubjectSpendPlanResponse {
    return CreateCbxSubjectSpendPlanResponseFromJSONTyped(json, false);
}

export function CreateCbxSubjectSpendPlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxSubjectSpendPlanResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'legs': ((json['legs'] as Array<any>).map(CreateCbxSubjectSpendPlanResponseLegsFromJSON)),
        'shortfallBaseUnits': json['shortfallBaseUnits'],
        'fullyFunded': json['fullyFunded'],
    };
}

export function CreateCbxSubjectSpendPlanResponseToJSON(value?: CreateCbxSubjectSpendPlanResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'legs': ((value.legs as Array<any>).map(CreateCbxSubjectSpendPlanResponseLegsToJSON)),
        'shortfallBaseUnits': value.shortfallBaseUnits,
        'fullyFunded': value.fullyFunded,
    };
}

