/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxAdCreditSpendResponse
 */
export interface CreateCbxAdCreditSpendResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAdCreditSpendResponse
     */
    spentCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAdCreditSpendResponse
     */
    shortfallCents: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAdCreditSpendResponse
     */
    balanceCents: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxAdCreditSpendResponse
     */
    poolBaseUnits: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxAdCreditSpendResponse
     */
    duplicate: boolean;
}

export function CreateCbxAdCreditSpendResponseFromJSON(json: any): CreateCbxAdCreditSpendResponse {
    return CreateCbxAdCreditSpendResponseFromJSONTyped(json, false);
}

export function CreateCbxAdCreditSpendResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxAdCreditSpendResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spentCents': json['spentCents'],
        'shortfallCents': json['shortfallCents'],
        'balanceCents': json['balanceCents'],
        'poolBaseUnits': json['poolBaseUnits'],
        'duplicate': json['duplicate'],
    };
}

export function CreateCbxAdCreditSpendResponseToJSON(value?: CreateCbxAdCreditSpendResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spentCents': value.spentCents,
        'shortfallCents': value.shortfallCents,
        'balanceCents': value.balanceCents,
        'poolBaseUnits': value.poolBaseUnits,
        'duplicate': value.duplicate,
    };
}

