/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxAdCreditPurchaseResponse
 */
export interface CreateCbxAdCreditPurchaseResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAdCreditPurchaseResponse
     */
    creditCents: number;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxAdCreditPurchaseResponse
     */
    baseUnitsPaid: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAdCreditPurchaseResponse
     */
    centsPerToken: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCbxAdCreditPurchaseResponse
     */
    balanceCents: number;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxAdCreditPurchaseResponse
     */
    duplicate: boolean;
}

export function CreateCbxAdCreditPurchaseResponseFromJSON(json: any): CreateCbxAdCreditPurchaseResponse {
    return CreateCbxAdCreditPurchaseResponseFromJSONTyped(json, false);
}

export function CreateCbxAdCreditPurchaseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxAdCreditPurchaseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'creditCents': json['creditCents'],
        'baseUnitsPaid': json['baseUnitsPaid'],
        'centsPerToken': json['centsPerToken'],
        'balanceCents': json['balanceCents'],
        'duplicate': json['duplicate'],
    };
}

export function CreateCbxAdCreditPurchaseResponseToJSON(value?: CreateCbxAdCreditPurchaseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'creditCents': value.creditCents,
        'baseUnitsPaid': value.baseUnitsPaid,
        'centsPerToken': value.centsPerToken,
        'balanceCents': value.balanceCents,
        'duplicate': value.duplicate,
    };
}

