/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxRevenueSweepResponseBreakdown
 */
export interface CreateCbxRevenueSweepResponseBreakdown {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRevenueSweepResponseBreakdown
     */
    reserveBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRevenueSweepResponseBreakdown
     */
    outstandingBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRevenueSweepResponseBreakdown
     */
    inFlightBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRevenueSweepResponseBreakdown
     */
    poolBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRevenueSweepResponseBreakdown
     */
    accruedRevenueBaseUnits: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxRevenueSweepResponseBreakdown
     */
    freeBaseUnits: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxRevenueSweepResponseBreakdown
     */
    shortfall: boolean;
}

export function CreateCbxRevenueSweepResponseBreakdownFromJSON(json: any): CreateCbxRevenueSweepResponseBreakdown {
    return CreateCbxRevenueSweepResponseBreakdownFromJSONTyped(json, false);
}

export function CreateCbxRevenueSweepResponseBreakdownFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxRevenueSweepResponseBreakdown {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reserveBaseUnits': json['reserveBaseUnits'],
        'outstandingBaseUnits': json['outstandingBaseUnits'],
        'inFlightBaseUnits': json['inFlightBaseUnits'],
        'poolBaseUnits': json['poolBaseUnits'],
        'accruedRevenueBaseUnits': json['accruedRevenueBaseUnits'],
        'freeBaseUnits': json['freeBaseUnits'],
        'shortfall': json['shortfall'],
    };
}

export function CreateCbxRevenueSweepResponseBreakdownToJSON(value?: CreateCbxRevenueSweepResponseBreakdown | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reserveBaseUnits': value.reserveBaseUnits,
        'outstandingBaseUnits': value.outstandingBaseUnits,
        'inFlightBaseUnits': value.inFlightBaseUnits,
        'poolBaseUnits': value.poolBaseUnits,
        'accruedRevenueBaseUnits': value.accruedRevenueBaseUnits,
        'freeBaseUnits': value.freeBaseUnits,
        'shortfall': value.shortfall,
    };
}

