/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSavedViewResponse
 */
export interface CreateSavedViewResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateSavedViewResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedViewResponse
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateSavedViewResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateSavedViewResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedViewResponse
     */
    userId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSavedViewResponse
     */
    isDefault: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateSavedViewResponse
     */
    sortOrder: number;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedViewResponse
     */
    resource: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedViewResponse
     */
    viewMode?: string | null;
}

export function CreateSavedViewResponseFromJSON(json: any): CreateSavedViewResponse {
    return CreateSavedViewResponseFromJSONTyped(json, false);
}

export function CreateSavedViewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSavedViewResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'userId': json['userId'],
        'isDefault': json['isDefault'],
        'sortOrder': json['sortOrder'],
        'resource': json['resource'],
        'viewMode': !exists(json, 'viewMode') ? undefined : json['viewMode'],
    };
}

export function CreateSavedViewResponseToJSON(value?: CreateSavedViewResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'createdAt': (value.createdAt.toISOString()),
        'updatedAt': (value.updatedAt.toISOString()),
        'userId': value.userId,
        'isDefault': value.isDefault,
        'sortOrder': value.sortOrder,
        'resource': value.resource,
        'viewMode': value.viewMode,
    };
}

