/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxBoostPauseResponse
 */
export interface CreateCbxBoostPauseResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateCbxBoostPauseResponse
     */
    paused: boolean;
}

export function CreateCbxBoostPauseResponseFromJSON(json: any): CreateCbxBoostPauseResponse {
    return CreateCbxBoostPauseResponseFromJSONTyped(json, false);
}

export function CreateCbxBoostPauseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxBoostPauseResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paused': json['paused'],
    };
}

export function CreateCbxBoostPauseResponseToJSON(value?: CreateCbxBoostPauseResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paused': value.paused,
    };
}

