/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMobilePushTokenResponse
 */
export interface CreateMobilePushTokenResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateMobilePushTokenResponse
     */
    ok: boolean;
}

export function CreateMobilePushTokenResponseFromJSON(json: any): CreateMobilePushTokenResponse {
    return CreateMobilePushTokenResponseFromJSONTyped(json, false);
}

export function CreateMobilePushTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMobilePushTokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ok': json['ok'],
    };
}

export function CreateMobilePushTokenResponseToJSON(value?: CreateMobilePushTokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ok': value.ok,
    };
}

