/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCbxSubjectSpendPlanResponseLegs
 */
export interface CreateCbxSubjectSpendPlanResponseLegs {
    /**
     * 
     * @type {string}
     * @memberof CreateCbxSubjectSpendPlanResponseLegs
     */
    source: CreateCbxSubjectSpendPlanResponseLegsSourceEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateCbxSubjectSpendPlanResponseLegs
     */
    baseUnits: string;
}

/**
* @export
* @enum {string}
*/
export enum CreateCbxSubjectSpendPlanResponseLegsSourceEnum {
    Connected = 'connected',
    Granted = 'granted',
    Earned = 'earned'
}

export function CreateCbxSubjectSpendPlanResponseLegsFromJSON(json: any): CreateCbxSubjectSpendPlanResponseLegs {
    return CreateCbxSubjectSpendPlanResponseLegsFromJSONTyped(json, false);
}

export function CreateCbxSubjectSpendPlanResponseLegsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCbxSubjectSpendPlanResponseLegs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'source': json['source'],
        'baseUnits': json['baseUnits'],
    };
}

export function CreateCbxSubjectSpendPlanResponseLegsToJSON(value?: CreateCbxSubjectSpendPlanResponseLegs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'source': value.source,
        'baseUnits': value.baseUnits,
    };
}

