/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Null,
    NullFromJSON,
    NullFromJSONTyped,
    NullToJSON,
} from './Null';

/**
 * 
 * @export
 * @interface CreateListingBulkDeleteResponse
 */
export interface CreateListingBulkDeleteResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateListingBulkDeleteResponse
     */
    message: string;
    /**
     * 
     * @type {Null}
     * @memberof CreateListingBulkDeleteResponse
     */
    bulkJobId: Null;
}

export function CreateListingBulkDeleteResponseFromJSON(json: any): CreateListingBulkDeleteResponse {
    return CreateListingBulkDeleteResponseFromJSONTyped(json, false);
}

export function CreateListingBulkDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateListingBulkDeleteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'bulkJobId': NullFromJSON(json['bulkJobId']),
    };
}

export function CreateListingBulkDeleteResponseToJSON(value?: CreateListingBulkDeleteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'bulkJobId': NullToJSON(value.bulkJobId),
    };
}

