/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInboxConversationBulkAiRespondResponseResults
 */
export interface CreateInboxConversationBulkAiRespondResponseResults {
    /**
     * 
     * @type {string}
     * @memberof CreateInboxConversationBulkAiRespondResponseResults
     */
    conversationId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateInboxConversationBulkAiRespondResponseResults
     */
    ok: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateInboxConversationBulkAiRespondResponseResults
     */
    suggestion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateInboxConversationBulkAiRespondResponseResults
     */
    error?: string | null;
}

export function CreateInboxConversationBulkAiRespondResponseResultsFromJSON(json: any): CreateInboxConversationBulkAiRespondResponseResults {
    return CreateInboxConversationBulkAiRespondResponseResultsFromJSONTyped(json, false);
}

export function CreateInboxConversationBulkAiRespondResponseResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInboxConversationBulkAiRespondResponseResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'conversationId': json['conversationId'],
        'ok': json['ok'],
        'suggestion': !exists(json, 'suggestion') ? undefined : json['suggestion'],
        'error': !exists(json, 'error') ? undefined : json['error'],
    };
}

export function CreateInboxConversationBulkAiRespondResponseResultsToJSON(value?: CreateInboxConversationBulkAiRespondResponseResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'conversationId': value.conversationId,
        'ok': value.ok,
        'suggestion': value.suggestion,
        'error': value.error,
    };
}

