/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInventoryBulkDeleteResponse
 */
export interface CreateInventoryBulkDeleteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateInventoryBulkDeleteResponse
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateInventoryBulkDeleteResponse
     */
    deleted: number;
    /**
     * 
     * @type {string}
     * @memberof CreateInventoryBulkDeleteResponse
     */
    bulkJobId: string;
}

export function CreateInventoryBulkDeleteResponseFromJSON(json: any): CreateInventoryBulkDeleteResponse {
    return CreateInventoryBulkDeleteResponseFromJSONTyped(json, false);
}

export function CreateInventoryBulkDeleteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInventoryBulkDeleteResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'deleted': json['deleted'],
        'bulkJobId': json['bulkJobId'],
    };
}

export function CreateInventoryBulkDeleteResponseToJSON(value?: CreateInventoryBulkDeleteResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'deleted': value.deleted,
        'bulkJobId': value.bulkJobId,
    };
}

