/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Category path — split into [main, sub, sub2] when present. eBay
 * categoryPath is the cleanest source.
 * @export
 * @interface CreateMagicScanSynthesizeResponsePayloadCategory
 */
export interface CreateMagicScanSynthesizeResponsePayloadCategory {
    /**
     * 
     * @type {string}
     * @memberof CreateMagicScanSynthesizeResponsePayloadCategory
     */
    main?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMagicScanSynthesizeResponsePayloadCategory
     */
    sub?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMagicScanSynthesizeResponsePayloadCategory
     */
    sub2?: string | null;
}

export function CreateMagicScanSynthesizeResponsePayloadCategoryFromJSON(json: any): CreateMagicScanSynthesizeResponsePayloadCategory {
    return CreateMagicScanSynthesizeResponsePayloadCategoryFromJSONTyped(json, false);
}

export function CreateMagicScanSynthesizeResponsePayloadCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMagicScanSynthesizeResponsePayloadCategory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'main': !exists(json, 'main') ? undefined : json['main'],
        'sub': !exists(json, 'sub') ? undefined : json['sub'],
        'sub2': !exists(json, 'sub2') ? undefined : json['sub2'],
    };
}

export function CreateMagicScanSynthesizeResponsePayloadCategoryToJSON(value?: CreateMagicScanSynthesizeResponsePayloadCategory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'main': value.main,
        'sub': value.sub,
        'sub2': value.sub2,
    };
}

