/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetAdOffsiteResponseTermsNetworks,
    GetAdOffsiteResponseTermsNetworksFromJSON,
    GetAdOffsiteResponseTermsNetworksFromJSONTyped,
    GetAdOffsiteResponseTermsNetworksToJSON,
} from './GetAdOffsiteResponseTermsNetworks';

/**
 * 
 * @export
 * @interface GetAdOffsiteResponseTerms
 */
export interface GetAdOffsiteResponseTerms {
    /**
     * 
     * @type {number}
     * @memberof GetAdOffsiteResponseTerms
     */
    managementFeeBps: number;
    /**
     * 
     * @type {GetAdOffsiteResponseTermsNetworks}
     * @memberof GetAdOffsiteResponseTerms
     */
    networks: GetAdOffsiteResponseTermsNetworks;
}

export function GetAdOffsiteResponseTermsFromJSON(json: any): GetAdOffsiteResponseTerms {
    return GetAdOffsiteResponseTermsFromJSONTyped(json, false);
}

export function GetAdOffsiteResponseTermsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdOffsiteResponseTerms {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'managementFeeBps': json['managementFeeBps'],
        'networks': GetAdOffsiteResponseTermsNetworksFromJSON(json['networks']),
    };
}

export function GetAdOffsiteResponseTermsToJSON(value?: GetAdOffsiteResponseTerms | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'managementFeeBps': value.managementFeeBps,
        'networks': GetAdOffsiteResponseTermsNetworksToJSON(value.networks),
    };
}

