/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAdOffsiteEligibilityResponse
 */
export interface GetAdOffsiteEligibilityResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GetAdOffsiteEligibilityResponse
     */
    eligible: boolean;
}

export function GetAdOffsiteEligibilityResponseFromJSON(json: any): GetAdOffsiteEligibilityResponse {
    return GetAdOffsiteEligibilityResponseFromJSONTyped(json, false);
}

export function GetAdOffsiteEligibilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAdOffsiteEligibilityResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eligible': json['eligible'],
    };
}

export function GetAdOffsiteEligibilityResponseToJSON(value?: GetAdOffsiteEligibilityResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eligible': value.eligible,
    };
}

