/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAnalyticDashboardResponseCancelRate
 */
export interface GetAnalyticDashboardResponseCancelRate {
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseCancelRate
     */
    current: number;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseCancelRate
     */
    previous: number;
}

export function GetAnalyticDashboardResponseCancelRateFromJSON(json: any): GetAnalyticDashboardResponseCancelRate {
    return GetAnalyticDashboardResponseCancelRateFromJSONTyped(json, false);
}

export function GetAnalyticDashboardResponseCancelRateFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticDashboardResponseCancelRate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'current': json['current'],
        'previous': json['previous'],
    };
}

export function GetAnalyticDashboardResponseCancelRateToJSON(value?: GetAnalyticDashboardResponseCancelRate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'current': value.current,
        'previous': value.previous,
    };
}

