/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAnalyticDashboardResponseTopCategories
 */
export interface GetAnalyticDashboardResponseTopCategories {
    /**
     * 
     * @type {string}
     * @memberof GetAnalyticDashboardResponseTopCategories
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseTopCategories
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseTopCategories
     */
    revenue: number;
}

export function GetAnalyticDashboardResponseTopCategoriesFromJSON(json: any): GetAnalyticDashboardResponseTopCategories {
    return GetAnalyticDashboardResponseTopCategoriesFromJSONTyped(json, false);
}

export function GetAnalyticDashboardResponseTopCategoriesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticDashboardResponseTopCategories {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'count': json['count'],
        'revenue': json['revenue'],
    };
}

export function GetAnalyticDashboardResponseTopCategoriesToJSON(value?: GetAnalyticDashboardResponseTopCategories | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'count': value.count,
        'revenue': value.revenue,
    };
}

