/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAutomationRuleExportResponseAction
 */
export interface GetAutomationRuleExportResponseAction {
    /**
     * 
     * @type {string}
     * @memberof GetAutomationRuleExportResponseAction
     */
    type: string;
    /**
     * 
     * @type {object}
     * @memberof GetAutomationRuleExportResponseAction
     */
    config: object;
}

export function GetAutomationRuleExportResponseActionFromJSON(json: any): GetAutomationRuleExportResponseAction {
    return GetAutomationRuleExportResponseActionFromJSONTyped(json, false);
}

export function GetAutomationRuleExportResponseActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAutomationRuleExportResponseAction {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': json['type'],
        'config': json['config'],
    };
}

export function GetAutomationRuleExportResponseActionToJSON(value?: GetAutomationRuleExportResponseAction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'config': value.config,
    };
}

