/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAnalyticDashboardResponseTop5ItemsByRevenue
 */
export interface GetAnalyticDashboardResponseTop5ItemsByRevenue {
    /**
     * 
     * @type {string}
     * @memberof GetAnalyticDashboardResponseTop5ItemsByRevenue
     */
    saleId: string;
    /**
     * 
     * @type {string}
     * @memberof GetAnalyticDashboardResponseTop5ItemsByRevenue
     */
    platform: string;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseTop5ItemsByRevenue
     */
    salePrice?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetAnalyticDashboardResponseTop5ItemsByRevenue
     */
    netProfit?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof GetAnalyticDashboardResponseTop5ItemsByRevenue
     */
    detectedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetAnalyticDashboardResponseTop5ItemsByRevenue
     */
    itemTitle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetAnalyticDashboardResponseTop5ItemsByRevenue
     */
    itemImage: string;
}

export function GetAnalyticDashboardResponseTop5ItemsByRevenueFromJSON(json: any): GetAnalyticDashboardResponseTop5ItemsByRevenue {
    return GetAnalyticDashboardResponseTop5ItemsByRevenueFromJSONTyped(json, false);
}

export function GetAnalyticDashboardResponseTop5ItemsByRevenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAnalyticDashboardResponseTop5ItemsByRevenue {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'saleId': json['saleId'],
        'platform': json['platform'],
        'salePrice': !exists(json, 'salePrice') ? undefined : json['salePrice'],
        'netProfit': !exists(json, 'netProfit') ? undefined : json['netProfit'],
        'detectedAt': (new Date(json['detectedAt'])),
        'itemTitle': !exists(json, 'itemTitle') ? undefined : json['itemTitle'],
        'itemImage': json['itemImage'],
    };
}

export function GetAnalyticDashboardResponseTop5ItemsByRevenueToJSON(value?: GetAnalyticDashboardResponseTop5ItemsByRevenue | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'saleId': value.saleId,
        'platform': value.platform,
        'salePrice': value.salePrice,
        'netProfit': value.netProfit,
        'detectedAt': (value.detectedAt.toISOString()),
        'itemTitle': value.itemTitle,
        'itemImage': value.itemImage,
    };
}

