/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetAutomationRuleExportResponseAction,
    GetAutomationRuleExportResponseActionFromJSON,
    GetAutomationRuleExportResponseActionFromJSONTyped,
    GetAutomationRuleExportResponseActionToJSON,
} from './GetAutomationRuleExportResponseAction';
import {
    GetAutomationRuleExportResponseCondition,
    GetAutomationRuleExportResponseConditionFromJSON,
    GetAutomationRuleExportResponseConditionFromJSONTyped,
    GetAutomationRuleExportResponseConditionToJSON,
} from './GetAutomationRuleExportResponseCondition';
import {
    GetAutomationRuleExportResponseMetadata,
    GetAutomationRuleExportResponseMetadataFromJSON,
    GetAutomationRuleExportResponseMetadataFromJSONTyped,
    GetAutomationRuleExportResponseMetadataToJSON,
} from './GetAutomationRuleExportResponseMetadata';

/**
 * 
 * @export
 * @interface GetAutomationRuleExportByIdResponse
 */
export interface GetAutomationRuleExportByIdResponse {
    /**
     * 
     * @type {string}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    name: string;
    /**
     * 
     * @type {GetAutomationRuleExportResponseAction}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    action: GetAutomationRuleExportResponseAction;
    /**
     * 
     * @type {GetAutomationRuleExportResponseAction}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    trigger: GetAutomationRuleExportResponseAction;
    /**
     * 
     * @type {number}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    schemaVersion: number;
    /**
     * 
     * @type {GetAutomationRuleExportResponseCondition}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    condition?: GetAutomationRuleExportResponseCondition | null;
    /**
     * 
     * @type {GetAutomationRuleExportResponseMetadata}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    metadata?: GetAutomationRuleExportResponseMetadata | null;
    /**
     * 
     * @type {string}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    platforms?: Array<string> | null;
    /**
     * Optional reference to the public schema URL — purely cosmetic.
     * @type {string}
     * @memberof GetAutomationRuleExportByIdResponse
     */
    $schema?: string | null;
}

export function GetAutomationRuleExportByIdResponseFromJSON(json: any): GetAutomationRuleExportByIdResponse {
    return GetAutomationRuleExportByIdResponseFromJSONTyped(json, false);
}

export function GetAutomationRuleExportByIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAutomationRuleExportByIdResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'action': GetAutomationRuleExportResponseActionFromJSON(json['action']),
        'trigger': GetAutomationRuleExportResponseActionFromJSON(json['trigger']),
        'schemaVersion': json['schemaVersion'],
        'condition': !exists(json, 'condition') ? undefined : GetAutomationRuleExportResponseConditionFromJSON(json['condition']),
        'metadata': !exists(json, 'metadata') ? undefined : GetAutomationRuleExportResponseMetadataFromJSON(json['metadata']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'platforms': !exists(json, 'platforms') ? undefined : json['platforms'],
        '$schema': !exists(json, '$schema') ? undefined : json['$schema'],
    };
}

export function GetAutomationRuleExportByIdResponseToJSON(value?: GetAutomationRuleExportByIdResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'action': GetAutomationRuleExportResponseActionToJSON(value.action),
        'trigger': GetAutomationRuleExportResponseActionToJSON(value.trigger),
        'schemaVersion': value.schemaVersion,
        'condition': GetAutomationRuleExportResponseConditionToJSON(value.condition),
        'metadata': GetAutomationRuleExportResponseMetadataToJSON(value.metadata),
        'description': value.description,
        'platforms': value.platforms,
        '$schema': value.$schema,
    };
}

