/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetBuyerCatalogListingAvailabilityResponse
 */
export interface GetBuyerCatalogListingAvailabilityResponse {
    /**
     * 
     * @type {string}
     * @memberof GetBuyerCatalogListingAvailabilityResponse
     */
    slug: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetBuyerCatalogListingAvailabilityResponse
     */
    available: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetBuyerCatalogListingAvailabilityResponse
     */
    quantityAvailable: number;
    /**
     * 
     * @type {number}
     * @memberof GetBuyerCatalogListingAvailabilityResponse
     */
    priceCents: number;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerCatalogListingAvailabilityResponse
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof GetBuyerCatalogListingAvailabilityResponse
     */
    status: string;
}

export function GetBuyerCatalogListingAvailabilityResponseFromJSON(json: any): GetBuyerCatalogListingAvailabilityResponse {
    return GetBuyerCatalogListingAvailabilityResponseFromJSONTyped(json, false);
}

export function GetBuyerCatalogListingAvailabilityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetBuyerCatalogListingAvailabilityResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'available': json['available'],
        'quantityAvailable': json['quantityAvailable'],
        'priceCents': json['priceCents'],
        'currency': json['currency'],
        'status': json['status'],
    };
}

export function GetBuyerCatalogListingAvailabilityResponseToJSON(value?: GetBuyerCatalogListingAvailabilityResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'available': value.available,
        'quantityAvailable': value.quantityAvailable,
        'priceCents': value.priceCents,
        'currency': value.currency,
        'status': value.status,
    };
}

