/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCbxSubjectBalanceResponse
 */
export interface GetCbxSubjectBalanceResponse {
    /**
     * 
     * @type {string}
     * @memberof GetCbxSubjectBalanceResponse
     */
    subjectId: string;
    /**
     * 
     * @type {string}
     * @memberof GetCbxSubjectBalanceResponse
     */
    availableBaseUnits: string;
    /**
     * 
     * @type {number}
     * @memberof GetCbxSubjectBalanceResponse
     */
    pendingCents: number;
}

export function GetCbxSubjectBalanceResponseFromJSON(json: any): GetCbxSubjectBalanceResponse {
    return GetCbxSubjectBalanceResponseFromJSONTyped(json, false);
}

export function GetCbxSubjectBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCbxSubjectBalanceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subjectId': json['subjectId'],
        'availableBaseUnits': json['availableBaseUnits'],
        'pendingCents': json['pendingCents'],
    };
}

export function GetCbxSubjectBalanceResponseToJSON(value?: GetCbxSubjectBalanceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subjectId': value.subjectId,
        'availableBaseUnits': value.availableBaseUnits,
        'pendingCents': value.pendingCents,
    };
}

