/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCbxSubjectSpentResponse
 */
export interface GetCbxSubjectSpentResponse {
    /**
     * 
     * @type {string}
     * @memberof GetCbxSubjectSpentResponse
     */
    spentBaseUnits: string;
}

export function GetCbxSubjectSpentResponseFromJSON(json: any): GetCbxSubjectSpentResponse {
    return GetCbxSubjectSpentResponseFromJSONTyped(json, false);
}

export function GetCbxSubjectSpentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCbxSubjectSpentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'spentBaseUnits': json['spentBaseUnits'],
    };
}

export function GetCbxSubjectSpentResponseToJSON(value?: GetCbxSubjectSpentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spentBaseUnits': value.spentBaseUnits,
    };
}

