/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetConnectionHealthResponseAnchors,
    GetConnectionHealthResponseAnchorsFromJSON,
    GetConnectionHealthResponseAnchorsFromJSONTyped,
    GetConnectionHealthResponseAnchorsToJSON,
} from './GetConnectionHealthResponseAnchors';
import {
    GetConnectionHealthResponseBrowser,
    GetConnectionHealthResponseBrowserFromJSON,
    GetConnectionHealthResponseBrowserFromJSONTyped,
    GetConnectionHealthResponseBrowserToJSON,
} from './GetConnectionHealthResponseBrowser';
import {
    GetConnectionHealthResponseLiveness,
    GetConnectionHealthResponseLivenessFromJSON,
    GetConnectionHealthResponseLivenessFromJSONTyped,
    GetConnectionHealthResponseLivenessToJSON,
} from './GetConnectionHealthResponseLiveness';

/**
 * 
 * @export
 * @interface GetConnectionHealthResponseAccounts
 */
export interface GetConnectionHealthResponseAccounts {
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    platformName: string;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    accountId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetConnectionHealthResponseAccounts
     */
    accountSlot?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    label?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    platformUsername?: string | null;
    /**
     * Plain-English "what is true" + "what to do". Never empty.
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    action: string;
    /**
     * 
     * @type {GetConnectionHealthResponseLiveness}
     * @memberof GetConnectionHealthResponseAccounts
     */
    liveness: GetConnectionHealthResponseLiveness;
    /**
     * 
     * @type {GetConnectionHealthResponseBrowser}
     * @memberof GetConnectionHealthResponseAccounts
     */
    browser?: GetConnectionHealthResponseBrowser | null;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    state: GetConnectionHealthResponseAccountsStateEnum;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    severity: GetConnectionHealthResponseAccountsSeverityEnum;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseAccounts
     */
    audience: GetConnectionHealthResponseAccountsAudienceEnum;
    /**
     * 
     * @type {GetConnectionHealthResponseAnchors}
     * @memberof GetConnectionHealthResponseAccounts
     */
    anchors?: GetConnectionHealthResponseAnchors | null;
    /**
     * Secondary observations that do not change the verdict but change the
debugging. Always safe to show; never the only thing shown.
     * @type {Array<string>}
     * @memberof GetConnectionHealthResponseAccounts
     */
    notes: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum GetConnectionHealthResponseAccountsStateEnum {
    Unknown = 'unknown',
    Unmonitored = 'unmonitored',
    Disconnected = 'disconnected',
    Healthy = 'healthy',
    Stale = 'stale',
    PartialBlank = 'partial_blank',
    BlankCredential = 'blank_credential',
    SignedOut = 'signed_out',
    AnchorDrift = 'anchor_drift',
    NoCookies = 'no_cookies'
}/**
* @export
* @enum {string}
*/
export enum GetConnectionHealthResponseAccountsSeverityEnum {
    Error = 'error',
    Ok = 'ok',
    Unknown = 'unknown',
    Info = 'info',
    Warn = 'warn'
}/**
* @export
* @enum {string}
*/
export enum GetConnectionHealthResponseAccountsAudienceEnum {
    Seller = 'seller',
    Crossly = 'crossly',
    Nobody = 'nobody'
}

export function GetConnectionHealthResponseAccountsFromJSON(json: any): GetConnectionHealthResponseAccounts {
    return GetConnectionHealthResponseAccountsFromJSONTyped(json, false);
}

export function GetConnectionHealthResponseAccountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConnectionHealthResponseAccounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'platformName': json['platformName'],
        'accountId': !exists(json, 'accountId') ? undefined : json['accountId'],
        'accountSlot': !exists(json, 'accountSlot') ? undefined : json['accountSlot'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'platformUsername': !exists(json, 'platformUsername') ? undefined : json['platformUsername'],
        'summary': json['summary'],
        'action': json['action'],
        'liveness': GetConnectionHealthResponseLivenessFromJSON(json['liveness']),
        'browser': !exists(json, 'browser') ? undefined : GetConnectionHealthResponseBrowserFromJSON(json['browser']),
        'platform': json['platform'],
        'state': json['state'],
        'severity': json['severity'],
        'audience': json['audience'],
        'anchors': !exists(json, 'anchors') ? undefined : GetConnectionHealthResponseAnchorsFromJSON(json['anchors']),
        'notes': json['notes'],
    };
}

export function GetConnectionHealthResponseAccountsToJSON(value?: GetConnectionHealthResponseAccounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'platformName': value.platformName,
        'accountId': value.accountId,
        'accountSlot': value.accountSlot,
        'label': value.label,
        'platformUsername': value.platformUsername,
        'summary': value.summary,
        'action': value.action,
        'liveness': GetConnectionHealthResponseLivenessToJSON(value.liveness),
        'browser': GetConnectionHealthResponseBrowserToJSON(value.browser),
        'platform': value.platform,
        'state': value.state,
        'severity': value.severity,
        'audience': value.audience,
        'anchors': GetConnectionHealthResponseAnchorsToJSON(value.anchors),
        'notes': value.notes,
    };
}

