/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetConnectionHealthResponseExtension
 */
export interface GetConnectionHealthResponseExtension {
    /**
     * Heartbeat within the last 15 minutes. False is NOT proof of breakage —
a closed browser looks the same — so it is always paired with the
durable timestamp below.
     * @type {boolean}
     * @memberof GetConnectionHealthResponseExtension
     */
    online: boolean;
    /**
     * Newest browser push across every account. The durable answer to "when
did the extension last do anything", surviving a Redis flush.
     * @type {string}
     * @memberof GetConnectionHealthResponseExtension
     */
    lastBrowserPushAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetConnectionHealthResponseExtension
     */
    lastBrowserPushAgo: string;
    /**
     * Highest version any platform's browser report carried, or null when the
extension has never told us (it does not send one today — see the
service README notes in routes/extension-health.ts).
     * @type {string}
     * @memberof GetConnectionHealthResponseExtension
     */
    reportedVersion?: string | null;
}

export function GetConnectionHealthResponseExtensionFromJSON(json: any): GetConnectionHealthResponseExtension {
    return GetConnectionHealthResponseExtensionFromJSONTyped(json, false);
}

export function GetConnectionHealthResponseExtensionFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConnectionHealthResponseExtension {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'online': json['online'],
        'lastBrowserPushAt': !exists(json, 'lastBrowserPushAt') ? undefined : json['lastBrowserPushAt'],
        'lastBrowserPushAgo': json['lastBrowserPushAgo'],
        'reportedVersion': !exists(json, 'reportedVersion') ? undefined : json['reportedVersion'],
    };
}

export function GetConnectionHealthResponseExtensionToJSON(value?: GetConnectionHealthResponseExtension | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'online': value.online,
        'lastBrowserPushAt': value.lastBrowserPushAt,
        'lastBrowserPushAgo': value.lastBrowserPushAgo,
        'reportedVersion': value.reportedVersion,
    };
}

