/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ListImportsItemFilters,
    ListImportsItemFiltersFromJSON,
    ListImportsItemFiltersFromJSONTyped,
    ListImportsItemFiltersToJSON,
} from './ListImportsItemFilters';

/**
 * 
 * @export
 * @interface GetImportResponse
 */
export interface GetImportResponse {
    /**
     * 
     * @type {string}
     * @memberof GetImportResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof GetImportResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetImportResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof GetImportResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof GetImportResponse
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof GetImportResponse
     */
    lastError?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetImportResponse
     */
    startedAt?: Date | null;
    /**
     * 
     * @type {ListImportsItemFilters}
     * @memberof GetImportResponse
     */
    filters?: ListImportsItemFilters | null;
    /**
     * 
     * @type {Date}
     * @memberof GetImportResponse
     */
    finishedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GetImportResponse
     */
    batchId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetImportResponse
     */
    importMode: string;
    /**
     * 
     * @type {boolean}
     * @memberof GetImportResponse
     */
    includeInactive: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetImportResponse
     */
    mergeIntoExistingListing: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GetImportResponse
     */
    mergeIntoExistingInventory: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetImportResponse
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof GetImportResponse
     */
    importedCount: number;
    /**
     * 
     * @type {number}
     * @memberof GetImportResponse
     */
    skippedCount: number;
    /**
     * 
     * @type {number}
     * @memberof GetImportResponse
     */
    errorCount: number;
}

export function GetImportResponseFromJSON(json: any): GetImportResponse {
    return GetImportResponseFromJSONTyped(json, false);
}

export function GetImportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetImportResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'userId': json['userId'],
        'status': json['status'],
        'platform': json['platform'],
        'lastError': !exists(json, 'lastError') ? undefined : json['lastError'],
        'startedAt': !exists(json, 'startedAt') ? undefined : (json['startedAt'] === null ? null : new Date(json['startedAt'])),
        'filters': !exists(json, 'filters') ? undefined : ListImportsItemFiltersFromJSON(json['filters']),
        'finishedAt': !exists(json, 'finishedAt') ? undefined : (json['finishedAt'] === null ? null : new Date(json['finishedAt'])),
        'batchId': !exists(json, 'batchId') ? undefined : json['batchId'],
        'importMode': json['importMode'],
        'includeInactive': json['includeInactive'],
        'mergeIntoExistingListing': json['mergeIntoExistingListing'],
        'mergeIntoExistingInventory': json['mergeIntoExistingInventory'],
        'totalCount': json['totalCount'],
        'importedCount': json['importedCount'],
        'skippedCount': json['skippedCount'],
        'errorCount': json['errorCount'],
    };
}

export function GetImportResponseToJSON(value?: GetImportResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'userId': value.userId,
        'status': value.status,
        'platform': value.platform,
        'lastError': value.lastError,
        'startedAt': value.startedAt === undefined ? undefined : (value.startedAt === null ? null : value.startedAt.toISOString()),
        'filters': ListImportsItemFiltersToJSON(value.filters),
        'finishedAt': value.finishedAt === undefined ? undefined : (value.finishedAt === null ? null : value.finishedAt.toISOString()),
        'batchId': value.batchId,
        'importMode': value.importMode,
        'includeInactive': value.includeInactive,
        'mergeIntoExistingListing': value.mergeIntoExistingListing,
        'mergeIntoExistingInventory': value.mergeIntoExistingInventory,
        'totalCount': value.totalCount,
        'importedCount': value.importedCount,
        'skippedCount': value.skippedCount,
        'errorCount': value.errorCount,
    };
}

