/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetInventoryResponsePlatformListings,
    GetInventoryResponsePlatformListingsFromJSON,
    GetInventoryResponsePlatformListingsFromJSONTyped,
    GetInventoryResponsePlatformListingsToJSON,
} from './GetInventoryResponsePlatformListings';
import {
    ListInventoryItemCategory,
    ListInventoryItemCategoryFromJSON,
    ListInventoryItemCategoryFromJSONTyped,
    ListInventoryItemCategoryToJSON,
} from './ListInventoryItemCategory';

/**
 * 
 * @export
 * @interface GetInventoryResponse
 */
export interface GetInventoryResponse {
    /**
     * 
     * @type {Array<GetInventoryResponsePlatformListings>}
     * @memberof GetInventoryResponse
     */
    platformListings: Array<GetInventoryResponsePlatformListings>;
    /**
     * 
     * @type {ListInventoryItemCategory}
     * @memberof GetInventoryResponse
     */
    category?: ListInventoryItemCategory | null;
}

export function GetInventoryResponseFromJSON(json: any): GetInventoryResponse {
    return GetInventoryResponseFromJSONTyped(json, false);
}

export function GetInventoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInventoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'platformListings': ((json['platformListings'] as Array<any>).map(GetInventoryResponsePlatformListingsFromJSON)),
        'category': !exists(json, 'category') ? undefined : ListInventoryItemCategoryFromJSON(json['category']),
    };
}

export function GetInventoryResponseToJSON(value?: GetInventoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'platformListings': ((value.platformListings as Array<any>).map(GetInventoryResponsePlatformListingsToJSON)),
        'category': ListInventoryItemCategoryToJSON(value.category),
    };
}

