/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetInboxConversationMessageResponseMessages
 */
export interface GetInboxConversationMessageResponseMessages {
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    conversationId: string;
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    platformMessageId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    sender: string;
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    body?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    attachments?: Array<string> | null;
    /**
     * 
     * @type {Date}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    sentAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    syncedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    aiIntent?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    aiUrgency?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    aiScamScore?: number | null;
    /**
     * 
     * @type {string}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    aiSuggestedReply?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GetInboxConversationMessageResponseMessages
     */
    aiTriagedAt?: Date | null;
}

export function GetInboxConversationMessageResponseMessagesFromJSON(json: any): GetInboxConversationMessageResponseMessages {
    return GetInboxConversationMessageResponseMessagesFromJSONTyped(json, false);
}

export function GetInboxConversationMessageResponseMessagesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInboxConversationMessageResponseMessages {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'conversationId': json['conversationId'],
        'platformMessageId': !exists(json, 'platformMessageId') ? undefined : json['platformMessageId'],
        'sender': json['sender'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'attachments': !exists(json, 'attachments') ? undefined : json['attachments'],
        'sentAt': (new Date(json['sentAt'])),
        'syncedAt': !exists(json, 'syncedAt') ? undefined : (json['syncedAt'] === null ? null : new Date(json['syncedAt'])),
        'aiIntent': !exists(json, 'aiIntent') ? undefined : json['aiIntent'],
        'aiUrgency': !exists(json, 'aiUrgency') ? undefined : json['aiUrgency'],
        'aiScamScore': !exists(json, 'aiScamScore') ? undefined : json['aiScamScore'],
        'aiSuggestedReply': !exists(json, 'aiSuggestedReply') ? undefined : json['aiSuggestedReply'],
        'aiTriagedAt': !exists(json, 'aiTriagedAt') ? undefined : (json['aiTriagedAt'] === null ? null : new Date(json['aiTriagedAt'])),
    };
}

export function GetInboxConversationMessageResponseMessagesToJSON(value?: GetInboxConversationMessageResponseMessages | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'conversationId': value.conversationId,
        'platformMessageId': value.platformMessageId,
        'sender': value.sender,
        'body': value.body,
        'attachments': value.attachments,
        'sentAt': (value.sentAt.toISOString()),
        'syncedAt': value.syncedAt === undefined ? undefined : (value.syncedAt === null ? null : value.syncedAt.toISOString()),
        'aiIntent': value.aiIntent,
        'aiUrgency': value.aiUrgency,
        'aiScamScore': value.aiScamScore,
        'aiSuggestedReply': value.aiSuggestedReply,
        'aiTriagedAt': value.aiTriagedAt === undefined ? undefined : (value.aiTriagedAt === null ? null : value.aiTriagedAt.toISOString()),
    };
}

