/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetInboxCannedResponsResponseCannedResponses,
    GetInboxCannedResponsResponseCannedResponsesFromJSON,
    GetInboxCannedResponsResponseCannedResponsesFromJSONTyped,
    GetInboxCannedResponsResponseCannedResponsesToJSON,
} from './GetInboxCannedResponsResponseCannedResponses';

/**
 * 
 * @export
 * @interface GetInboxCannedResponsResponse
 */
export interface GetInboxCannedResponsResponse {
    /**
     * 
     * @type {Array<GetInboxCannedResponsResponseCannedResponses>}
     * @memberof GetInboxCannedResponsResponse
     */
    cannedResponses: Array<GetInboxCannedResponsResponseCannedResponses>;
}

export function GetInboxCannedResponsResponseFromJSON(json: any): GetInboxCannedResponsResponse {
    return GetInboxCannedResponsResponseFromJSONTyped(json, false);
}

export function GetInboxCannedResponsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInboxCannedResponsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cannedResponses': ((json['cannedResponses'] as Array<any>).map(GetInboxCannedResponsResponseCannedResponsesFromJSON)),
    };
}

export function GetInboxCannedResponsResponseToJSON(value?: GetInboxCannedResponsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cannedResponses': ((value.cannedResponses as Array<any>).map(GetInboxCannedResponsResponseCannedResponsesToJSON)),
    };
}

