/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetInventoryFacetResponse
 */
export interface GetInventoryFacetResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetInventoryFacetResponse
     */
    brands: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof GetInventoryFacetResponse
     */
    categories: Array<string>;
}

export function GetInventoryFacetResponseFromJSON(json: any): GetInventoryFacetResponse {
    return GetInventoryFacetResponseFromJSONTyped(json, false);
}

export function GetInventoryFacetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInventoryFacetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'brands': json['brands'],
        'categories': json['categories'],
    };
}

export function GetInventoryFacetResponseToJSON(value?: GetInventoryFacetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'brands': value.brands,
        'categories': value.categories,
    };
}

