/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetOrderShipmentResponseData,
    GetOrderShipmentResponseDataFromJSON,
    GetOrderShipmentResponseDataFromJSONTyped,
    GetOrderShipmentResponseDataToJSON,
} from './GetOrderShipmentResponseData';

/**
 * 
 * @export
 * @interface GetOrderShipmentResponse
 */
export interface GetOrderShipmentResponse {
    /**
     * 
     * @type {Array<GetOrderShipmentResponseData>}
     * @memberof GetOrderShipmentResponse
     */
    data: Array<GetOrderShipmentResponseData>;
    /**
     * 
     * @type {number}
     * @memberof GetOrderShipmentResponse
     */
    totalLabelCostCents: number;
}

export function GetOrderShipmentResponseFromJSON(json: any): GetOrderShipmentResponse {
    return GetOrderShipmentResponseFromJSONTyped(json, false);
}

export function GetOrderShipmentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrderShipmentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(GetOrderShipmentResponseDataFromJSON)),
        'totalLabelCostCents': json['totalLabelCostCents'],
    };
}

export function GetOrderShipmentResponseToJSON(value?: GetOrderShipmentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(GetOrderShipmentResponseDataToJSON)),
        'totalLabelCostCents': value.totalLabelCostCents,
    };
}

