/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPatternResponse
 */
export interface GetPatternResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetPatternResponse
     */
    patterns: Array<string>;
}

export function GetPatternResponseFromJSON(json: any): GetPatternResponse {
    return GetPatternResponseFromJSONTyped(json, false);
}

export function GetPatternResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPatternResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patterns': json['patterns'],
    };
}

export function GetPatternResponseToJSON(value?: GetPatternResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patterns': value.patterns,
    };
}

