/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetPlatformLimitResponseEbay,
    GetPlatformLimitResponseEbayFromJSON,
    GetPlatformLimitResponseEbayFromJSONTyped,
    GetPlatformLimitResponseEbayToJSON,
} from './GetPlatformLimitResponseEbay';
import {
    GetPlatformLimitResponseEtsy,
    GetPlatformLimitResponseEtsyFromJSON,
    GetPlatformLimitResponseEtsyFromJSONTyped,
    GetPlatformLimitResponseEtsyToJSON,
} from './GetPlatformLimitResponseEtsy';

/**
 * 
 * @export
 * @interface GetPlatformLimitResponse
 */
export interface GetPlatformLimitResponse {
    /**
     * 
     * @type {GetPlatformLimitResponseEbay}
     * @memberof GetPlatformLimitResponse
     */
    ebay?: GetPlatformLimitResponseEbay | null;
    /**
     * 
     * @type {GetPlatformLimitResponseEtsy}
     * @memberof GetPlatformLimitResponse
     */
    etsy?: GetPlatformLimitResponseEtsy | null;
}

export function GetPlatformLimitResponseFromJSON(json: any): GetPlatformLimitResponse {
    return GetPlatformLimitResponseFromJSONTyped(json, false);
}

export function GetPlatformLimitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPlatformLimitResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ebay': !exists(json, 'ebay') ? undefined : GetPlatformLimitResponseEbayFromJSON(json['ebay']),
        'etsy': !exists(json, 'etsy') ? undefined : GetPlatformLimitResponseEtsyFromJSON(json['etsy']),
    };
}

export function GetPlatformLimitResponseToJSON(value?: GetPlatformLimitResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ebay': GetPlatformLimitResponseEbayToJSON(value.ebay),
        'etsy': GetPlatformLimitResponseEtsyToJSON(value.etsy),
    };
}

