/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSpatialPublicResponseScene
 */
export interface GetSpatialPublicResponseScene {
    /**
     * 
     * @type {string}
     * @memberof GetSpatialPublicResponseScene
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetSpatialPublicResponseScene
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof GetSpatialPublicResponseScene
     */
    categorySlug?: string | null;
}

export function GetSpatialPublicResponseSceneFromJSON(json: any): GetSpatialPublicResponseScene {
    return GetSpatialPublicResponseSceneFromJSONTyped(json, false);
}

export function GetSpatialPublicResponseSceneFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpatialPublicResponseScene {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'kind': json['kind'],
        'categorySlug': !exists(json, 'categorySlug') ? undefined : json['categorySlug'],
    };
}

export function GetSpatialPublicResponseSceneToJSON(value?: GetSpatialPublicResponseScene | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'kind': value.kind,
        'categorySlug': value.categorySlug,
    };
}

