/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GetSpatialPublicResponseProfile,
    GetSpatialPublicResponseProfileFromJSON,
    GetSpatialPublicResponseProfileFromJSONTyped,
    GetSpatialPublicResponseProfileToJSON,
} from './GetSpatialPublicResponseProfile';
import {
    GetSpatialPublicResponseSolved,
    GetSpatialPublicResponseSolvedFromJSON,
    GetSpatialPublicResponseSolvedFromJSONTyped,
    GetSpatialPublicResponseSolvedToJSON,
} from './GetSpatialPublicResponseSolved';
import {
    GetSpatialSceneResponseBreakdowns,
    GetSpatialSceneResponseBreakdownsFromJSON,
    GetSpatialSceneResponseBreakdownsFromJSONTyped,
    GetSpatialSceneResponseBreakdownsToJSON,
} from './GetSpatialSceneResponseBreakdowns';
import {
    GetSpatialSceneResponseItems,
    GetSpatialSceneResponseItemsFromJSON,
    GetSpatialSceneResponseItemsFromJSONTyped,
    GetSpatialSceneResponseItemsToJSON,
} from './GetSpatialSceneResponseItems';
import {
    GetSpatialSceneResponseScene,
    GetSpatialSceneResponseSceneFromJSON,
    GetSpatialSceneResponseSceneFromJSONTyped,
    GetSpatialSceneResponseSceneToJSON,
} from './GetSpatialSceneResponseScene';
import {
    GetSpatialSceneResponseStats,
    GetSpatialSceneResponseStatsFromJSON,
    GetSpatialSceneResponseStatsFromJSONTyped,
    GetSpatialSceneResponseStatsToJSON,
} from './GetSpatialSceneResponseStats';

/**
 * 
 * @export
 * @interface GetSpatialSceneResponse
 */
export interface GetSpatialSceneResponse {
    /**
     * Facets that would actually split this collection, most-dividing first.
     * Drives the breakdown picker — see availableBreakdowns.
     * @type {Array<GetSpatialSceneResponseBreakdowns>}
     * @memberof GetSpatialSceneResponse
     */
    breakdowns: Array<GetSpatialSceneResponseBreakdowns>;
    /**
     * 
     * @type {GetSpatialSceneResponseScene}
     * @memberof GetSpatialSceneResponse
     */
    scene: GetSpatialSceneResponseScene;
    /**
     * 
     * @type {GetSpatialPublicResponseProfile}
     * @memberof GetSpatialSceneResponse
     */
    profile: GetSpatialPublicResponseProfile;
    /**
     * 
     * @type {GetSpatialPublicResponseSolved}
     * @memberof GetSpatialSceneResponse
     */
    solved: GetSpatialPublicResponseSolved;
    /**
     * 
     * @type {Array<GetSpatialSceneResponseItems>}
     * @memberof GetSpatialSceneResponse
     */
    items: Array<GetSpatialSceneResponseItems>;
    /**
     * 
     * @type {GetSpatialSceneResponseStats}
     * @memberof GetSpatialSceneResponse
     */
    stats: GetSpatialSceneResponseStats;
}

export function GetSpatialSceneResponseFromJSON(json: any): GetSpatialSceneResponse {
    return GetSpatialSceneResponseFromJSONTyped(json, false);
}

export function GetSpatialSceneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSpatialSceneResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'breakdowns': ((json['breakdowns'] as Array<any>).map(GetSpatialSceneResponseBreakdownsFromJSON)),
        'scene': GetSpatialSceneResponseSceneFromJSON(json['scene']),
        'profile': GetSpatialPublicResponseProfileFromJSON(json['profile']),
        'solved': GetSpatialPublicResponseSolvedFromJSON(json['solved']),
        'items': ((json['items'] as Array<any>).map(GetSpatialSceneResponseItemsFromJSON)),
        'stats': GetSpatialSceneResponseStatsFromJSON(json['stats']),
    };
}

export function GetSpatialSceneResponseToJSON(value?: GetSpatialSceneResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'breakdowns': ((value.breakdowns as Array<any>).map(GetSpatialSceneResponseBreakdownsToJSON)),
        'scene': GetSpatialSceneResponseSceneToJSON(value.scene),
        'profile': GetSpatialPublicResponseProfileToJSON(value.profile),
        'solved': GetSpatialPublicResponseSolvedToJSON(value.solved),
        'items': ((value.items as Array<any>).map(GetSpatialSceneResponseItemsToJSON)),
        'stats': GetSpatialSceneResponseStatsToJSON(value.stats),
    };
}

