/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetTaxScheduleCResponseCounts
 */
export interface GetTaxScheduleCResponseCounts {
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponseCounts
     */
    sales: number;
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponseCounts
     */
    refunds: number;
    /**
     * 
     * @type {number}
     * @memberof GetTaxScheduleCResponseCounts
     */
    mileageEntries: number;
}

export function GetTaxScheduleCResponseCountsFromJSON(json: any): GetTaxScheduleCResponseCounts {
    return GetTaxScheduleCResponseCountsFromJSONTyped(json, false);
}

export function GetTaxScheduleCResponseCountsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTaxScheduleCResponseCounts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sales': json['sales'],
        'refunds': json['refunds'],
        'mileageEntries': json['mileageEntries'],
    };
}

export function GetTaxScheduleCResponseCountsToJSON(value?: GetTaxScheduleCResponseCounts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sales': value.sales,
        'refunds': value.refunds,
        'mileageEntries': value.mileageEntries,
    };
}

