/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetVariationGroupPublishPlanResponsePlans
 */
export interface GetVariationGroupPublishPlanResponsePlans {
    /**
     * 
     * @type {string}
     * @memberof GetVariationGroupPublishPlanResponsePlans
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof GetVariationGroupPublishPlanResponsePlans
     */
    mode: GetVariationGroupPublishPlanResponsePlansModeEnum;
    /**
     * How many marketplace listings this produces. One when grouped; one per
     * option when separate — the number the seller should see before they
     * commit, not after.
     * @type {number}
     * @memberof GetVariationGroupPublishPlanResponsePlans
     */
    listingsProduced: number;
    /**
     * Plain-language, shown in the publish dialog.
     * @type {string}
     * @memberof GetVariationGroupPublishPlanResponsePlans
     */
    explanation: string;
}

/**
* @export
* @enum {string}
*/
export enum GetVariationGroupPublishPlanResponsePlansModeEnum {
    Grouped = 'grouped',
    Separate = 'separate'
}

export function GetVariationGroupPublishPlanResponsePlansFromJSON(json: any): GetVariationGroupPublishPlanResponsePlans {
    return GetVariationGroupPublishPlanResponsePlansFromJSONTyped(json, false);
}

export function GetVariationGroupPublishPlanResponsePlansFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetVariationGroupPublishPlanResponsePlans {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'platform': json['platform'],
        'mode': json['mode'],
        'listingsProduced': json['listingsProduced'],
        'explanation': json['explanation'],
    };
}

export function GetVariationGroupPublishPlanResponsePlansToJSON(value?: GetVariationGroupPublishPlanResponsePlans | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'platform': value.platform,
        'mode': value.mode,
        'listingsProduced': value.listingsProduced,
        'explanation': value.explanation,
    };
}

