/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    subscriptionTier?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    subscriptionStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    patPrefix?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse200
     */
    scopes?: Array<string>;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'subscriptionTier': !exists(json, 'subscriptionTier') ? undefined : json['subscriptionTier'],
        'subscriptionStatus': !exists(json, 'subscriptionStatus') ? undefined : json['subscriptionStatus'],
        'patPrefix': !exists(json, 'patPrefix') ? undefined : json['patPrefix'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'email': value.email,
        'displayName': value.displayName,
        'subscriptionTier': value.subscriptionTier,
        'subscriptionStatus': value.subscriptionStatus,
        'patPrefix': value.patPrefix,
        'scopes': value.scopes,
    };
}

