/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListPatItem
 */
export interface ListPatItem {
    /**
     * 
     * @type {string}
     * @memberof ListPatItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListPatItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ListPatItem
     */
    prefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListPatItem
     */
    scopes: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ListPatItem
     */
    environment: string;
    /**
     * 
     * @type {Date}
     * @memberof ListPatItem
     */
    lastUsedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListPatItem
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListPatItem
     */
    revokedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ListPatItem
     */
    createdAt: Date;
}

export function ListPatItemFromJSON(json: any): ListPatItem {
    return ListPatItemFromJSONTyped(json, false);
}

export function ListPatItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPatItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'prefix': json['prefix'],
        'scopes': json['scopes'],
        'environment': json['environment'],
        'lastUsedAt': !exists(json, 'lastUsedAt') ? undefined : (json['lastUsedAt'] === null ? null : new Date(json['lastUsedAt'])),
        'expiresAt': !exists(json, 'expiresAt') ? undefined : (json['expiresAt'] === null ? null : new Date(json['expiresAt'])),
        'revokedAt': !exists(json, 'revokedAt') ? undefined : (json['revokedAt'] === null ? null : new Date(json['revokedAt'])),
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ListPatItemToJSON(value?: ListPatItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'prefix': value.prefix,
        'scopes': value.scopes,
        'environment': value.environment,
        'lastUsedAt': value.lastUsedAt === undefined ? undefined : (value.lastUsedAt === null ? null : value.lastUsedAt.toISOString()),
        'expiresAt': value.expiresAt === undefined ? undefined : (value.expiresAt === null ? null : value.expiresAt.toISOString()),
        'revokedAt': value.revokedAt === undefined ? undefined : (value.revokedAt === null ? null : value.revokedAt.toISOString()),
        'createdAt': (value.createdAt.toISOString()),
    };
}

