/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNetworkPoolLogItem
 */
export interface ListNetworkPoolLogItem {
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    actionType: string;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    targetUserId: string;
    /**
     * 
     * @type {Date}
     * @memberof ListNetworkPoolLogItem
     */
    performedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    ruleId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    engagerUserId: string;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    targetListingId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListNetworkPoolLogItem
     */
    targetPlatformListingId?: string | null;
}

export function ListNetworkPoolLogItemFromJSON(json: any): ListNetworkPoolLogItem {
    return ListNetworkPoolLogItemFromJSONTyped(json, false);
}

export function ListNetworkPoolLogItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNetworkPoolLogItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'platform': json['platform'],
        'actionType': json['actionType'],
        'targetUserId': json['targetUserId'],
        'performedAt': (new Date(json['performedAt'])),
        'ruleId': !exists(json, 'ruleId') ? undefined : json['ruleId'],
        'engagerUserId': json['engagerUserId'],
        'targetListingId': !exists(json, 'targetListingId') ? undefined : json['targetListingId'],
        'targetPlatformListingId': !exists(json, 'targetPlatformListingId') ? undefined : json['targetPlatformListingId'],
    };
}

export function ListNetworkPoolLogItemToJSON(value?: ListNetworkPoolLogItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'platform': value.platform,
        'actionType': value.actionType,
        'targetUserId': value.targetUserId,
        'performedAt': (value.performedAt.toISOString()),
        'ruleId': value.ruleId,
        'engagerUserId': value.engagerUserId,
        'targetListingId': value.targetListingId,
        'targetPlatformListingId': value.targetPlatformListingId,
    };
}

