/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListNotificationIntegrationsItem
 */
export interface ListNotificationIntegrationsItem {
    /**
     * 
     * @type {object}
     * @memberof ListNotificationIntegrationsItem
     */
    config: object;
    /**
     * 
     * @type {string}
     * @memberof ListNotificationIntegrationsItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListNotificationIntegrationsItem
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof ListNotificationIntegrationsItem
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListNotificationIntegrationsItem
     */
    enabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ListNotificationIntegrationsItem
     */
    createdAt: Date;
}

export function ListNotificationIntegrationsItemFromJSON(json: any): ListNotificationIntegrationsItem {
    return ListNotificationIntegrationsItemFromJSONTyped(json, false);
}

export function ListNotificationIntegrationsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListNotificationIntegrationsItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'config': json['config'],
        'id': json['id'],
        'provider': json['provider'],
        'name': json['name'],
        'enabled': json['enabled'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function ListNotificationIntegrationsItemToJSON(value?: ListNotificationIntegrationsItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'config': value.config,
        'id': value.id,
        'provider': value.provider,
        'name': value.name,
        'enabled': value.enabled,
        'createdAt': (value.createdAt.toISOString()),
    };
}

