/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBuyerMonitorMatchesItem
 */
export interface ListBuyerMonitorMatchesItem {
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorMatchesItem
     */
    listingSlug: string;
    /**
     * 
     * @type {number}
     * @memberof ListBuyerMonitorMatchesItem
     */
    triggerPriceCents: number;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorMatchesItem
     */
    deliveredAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorMatchesItem
     */
    createdAt: string;
}

export function ListBuyerMonitorMatchesItemFromJSON(json: any): ListBuyerMonitorMatchesItem {
    return ListBuyerMonitorMatchesItemFromJSONTyped(json, false);
}

export function ListBuyerMonitorMatchesItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBuyerMonitorMatchesItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listingSlug': json['listingSlug'],
        'triggerPriceCents': json['triggerPriceCents'],
        'deliveredAt': !exists(json, 'deliveredAt') ? undefined : json['deliveredAt'],
        'createdAt': json['createdAt'],
    };
}

export function ListBuyerMonitorMatchesItemToJSON(value?: ListBuyerMonitorMatchesItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listingSlug': value.listingSlug,
        'triggerPriceCents': value.triggerPriceCents,
        'deliveredAt': value.deliveredAt,
        'createdAt': value.createdAt,
    };
}

