/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCbxBoostsItem
 */
export interface ListCbxBoostsItem {
    /**
     * 
     * @type {string}
     * @memberof ListCbxBoostsItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxBoostsItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxBoostsItem
     */
    targetKind: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxBoostsItem
     */
    targetValue?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListCbxBoostsItem
     */
    boostedRateBps: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxBoostsItem
     */
    budgetCents: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxBoostsItem
     */
    spentCents: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxBoostsItem
     */
    remainingCents: number;
    /**
     * 
     * @type {string}
     * @memberof ListCbxBoostsItem
     */
    startsAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxBoostsItem
     */
    endsAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxBoostsItem
     */
    status: string;
}

export function ListCbxBoostsItemFromJSON(json: any): ListCbxBoostsItem {
    return ListCbxBoostsItemFromJSONTyped(json, false);
}

export function ListCbxBoostsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCbxBoostsItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'targetKind': json['targetKind'],
        'targetValue': !exists(json, 'targetValue') ? undefined : json['targetValue'],
        'boostedRateBps': json['boostedRateBps'],
        'budgetCents': json['budgetCents'],
        'spentCents': json['spentCents'],
        'remainingCents': json['remainingCents'],
        'startsAt': json['startsAt'],
        'endsAt': json['endsAt'],
        'status': json['status'],
    };
}

export function ListCbxBoostsItemToJSON(value?: ListCbxBoostsItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'targetKind': value.targetKind,
        'targetValue': value.targetValue,
        'boostedRateBps': value.boostedRateBps,
        'budgetCents': value.budgetCents,
        'spentCents': value.spentCents,
        'remainingCents': value.remainingCents,
        'startsAt': value.startsAt,
        'endsAt': value.endsAt,
        'status': value.status,
    };
}

