/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListMarketGradersItem
 */
export interface ListMarketGradersItem {
    /**
     * 
     * @type {string}
     * @memberof ListMarketGradersItem
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ListMarketGradersItem
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListMarketGradersItem
     */
    categorySlugs: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ListMarketGradersItem
     */
    scale: ListMarketGradersItemScaleEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListMarketGradersItem
     */
    grades: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListMarketGradersItem
     */
    qualifiers: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListMarketGradersItem
     */
    sealGrades: Array<string>;
}

/**
* @export
* @enum {string}
*/
export enum ListMarketGradersItemScaleEnum {
    Numeric = 'numeric',
    Sheldon = 'sheldon',
    Dual = 'dual',
    Hundred = 'hundred'
}

export function ListMarketGradersItemFromJSON(json: any): ListMarketGradersItem {
    return ListMarketGradersItemFromJSONTyped(json, false);
}

export function ListMarketGradersItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMarketGradersItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'categorySlugs': json['categorySlugs'],
        'scale': json['scale'],
        'grades': json['grades'],
        'qualifiers': json['qualifiers'],
        'sealGrades': json['sealGrades'],
    };
}

export function ListMarketGradersItemToJSON(value?: ListMarketGradersItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'categorySlugs': value.categorySlugs,
        'scale': value.scale,
        'grades': value.grades,
        'qualifiers': value.qualifiers,
        'sealGrades': value.sealGrades,
    };
}

