/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListOrdersItemTrackingHistory
 */
export interface ListOrdersItemTrackingHistory {
    /**
     * 
     * @type {string}
     * @memberof ListOrdersItemTrackingHistory
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ListOrdersItemTrackingHistory
     */
    statusDetails?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListOrdersItemTrackingHistory
     */
    statusDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListOrdersItemTrackingHistory
     */
    location?: string | null;
}

export function ListOrdersItemTrackingHistoryFromJSON(json: any): ListOrdersItemTrackingHistory {
    return ListOrdersItemTrackingHistoryFromJSONTyped(json, false);
}

export function ListOrdersItemTrackingHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrdersItemTrackingHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'statusDetails': !exists(json, 'statusDetails') ? undefined : json['statusDetails'],
        'statusDate': !exists(json, 'statusDate') ? undefined : json['statusDate'],
        'location': !exists(json, 'location') ? undefined : json['location'],
    };
}

export function ListOrdersItemTrackingHistoryToJSON(value?: ListOrdersItemTrackingHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'statusDetails': value.statusDetails,
        'statusDate': value.statusDate,
        'location': value.location,
    };
}

