/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListVariationGroupsItemMembers
 */
export interface ListVariationGroupsItemMembers {
    /**
     * 
     * @type {string}
     * @memberof ListVariationGroupsItemMembers
     */
    listingId: string;
    /**
     * 
     * @type {string}
     * @memberof ListVariationGroupsItemMembers
     */
    axisValue?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListVariationGroupsItemMembers
     */
    sortKey: number;
    /**
     * 
     * @type {string}
     * @memberof ListVariationGroupsItemMembers
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListVariationGroupsItemMembers
     */
    price?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ListVariationGroupsItemMembers
     */
    images?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof ListVariationGroupsItemMembers
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ListVariationGroupsItemMembers
     */
    sku?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListVariationGroupsItemMembers
     */
    quantityAvailable: number;
}

export function ListVariationGroupsItemMembersFromJSON(json: any): ListVariationGroupsItemMembers {
    return ListVariationGroupsItemMembersFromJSONTyped(json, false);
}

export function ListVariationGroupsItemMembersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListVariationGroupsItemMembers {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'listingId': json['listingId'],
        'axisValue': !exists(json, 'axisValue') ? undefined : json['axisValue'],
        'sortKey': json['sortKey'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'images': !exists(json, 'images') ? undefined : json['images'],
        'status': json['status'],
        'sku': !exists(json, 'sku') ? undefined : json['sku'],
        'quantityAvailable': json['quantityAvailable'],
    };
}

export function ListVariationGroupsItemMembersToJSON(value?: ListVariationGroupsItemMembers | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'listingId': value.listingId,
        'axisValue': value.axisValue,
        'sortKey': value.sortKey,
        'title': value.title,
        'price': value.price,
        'images': value.images,
        'status': value.status,
        'sku': value.sku,
        'quantityAvailable': value.quantityAvailable,
    };
}

