/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListBuyerMonitorsItem
 */
export interface ListBuyerMonitorsItem {
    /**
     * 
     * @type {boolean}
     * @memberof ListBuyerMonitorsItem
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    pausedReason?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListBuyerMonitorsItem
     */
    matchCount: number;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    lastCheckedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    lastMatchAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    webhookSecret?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    kind: ListBuyerMonitorsItemKindEnum;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    delivery: ListBuyerMonitorsItemDeliveryEnum;
    /**
     * 
     * @type {string}
     * @memberof ListBuyerMonitorsItem
     */
    webhookUrl?: string | null;
}

/**
* @export
* @enum {string}
*/
export enum ListBuyerMonitorsItemKindEnum {
    NewListing = 'new_listing',
    PriceDrop = 'price_drop',
    BackInStock = 'back_in_stock'
}/**
* @export
* @enum {string}
*/
export enum ListBuyerMonitorsItemDeliveryEnum {
    Webhook = 'webhook',
    Poll = 'poll'
}

export function ListBuyerMonitorsItemFromJSON(json: any): ListBuyerMonitorsItem {
    return ListBuyerMonitorsItemFromJSONTyped(json, false);
}

export function ListBuyerMonitorsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBuyerMonitorsItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'active': json['active'],
        'pausedReason': !exists(json, 'pausedReason') ? undefined : json['pausedReason'],
        'matchCount': json['matchCount'],
        'lastCheckedAt': !exists(json, 'lastCheckedAt') ? undefined : json['lastCheckedAt'],
        'lastMatchAt': !exists(json, 'lastMatchAt') ? undefined : json['lastMatchAt'],
        'createdAt': json['createdAt'],
        'webhookSecret': !exists(json, 'webhookSecret') ? undefined : json['webhookSecret'],
        'id': json['id'],
        'name': json['name'],
        'kind': json['kind'],
        'delivery': json['delivery'],
        'webhookUrl': !exists(json, 'webhookUrl') ? undefined : json['webhookUrl'],
    };
}

export function ListBuyerMonitorsItemToJSON(value?: ListBuyerMonitorsItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'active': value.active,
        'pausedReason': value.pausedReason,
        'matchCount': value.matchCount,
        'lastCheckedAt': value.lastCheckedAt,
        'lastMatchAt': value.lastMatchAt,
        'createdAt': value.createdAt,
        'webhookSecret': value.webhookSecret,
        'id': value.id,
        'name': value.name,
        'kind': value.kind,
        'delivery': value.delivery,
        'webhookUrl': value.webhookUrl,
    };
}

