/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListCbxDisbursementRulesItem
 */
export interface ListCbxDisbursementRulesItem {
    /**
     * 
     * @type {string}
     * @memberof ListCbxDisbursementRulesItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxDisbursementRulesItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ListCbxDisbursementRulesItem
     */
    thresholdBaseUnits: string;
    /**
     * 
     * @type {number}
     * @memberof ListCbxDisbursementRulesItem
     */
    distributeBps: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxDisbursementRulesItem
     */
    checkCadenceHours: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxDisbursementRulesItem
     */
    requireCoverageBps: number;
    /**
     * 
     * @type {string}
     * @memberof ListCbxDisbursementRulesItem
     */
    metric: string;
    /**
     * 
     * @type {number}
     * @memberof ListCbxDisbursementRulesItem
     */
    lookbackDays: number;
    /**
     * 
     * @type {number}
     * @memberof ListCbxDisbursementRulesItem
     */
    maxRecipients: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListCbxDisbursementRulesItem
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListCbxDisbursementRulesItem
     */
    lastFiredAt?: string | null;
}

export function ListCbxDisbursementRulesItemFromJSON(json: any): ListCbxDisbursementRulesItem {
    return ListCbxDisbursementRulesItemFromJSONTyped(json, false);
}

export function ListCbxDisbursementRulesItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCbxDisbursementRulesItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'thresholdBaseUnits': json['thresholdBaseUnits'],
        'distributeBps': json['distributeBps'],
        'checkCadenceHours': json['checkCadenceHours'],
        'requireCoverageBps': json['requireCoverageBps'],
        'metric': json['metric'],
        'lookbackDays': json['lookbackDays'],
        'maxRecipients': json['maxRecipients'],
        'isActive': json['isActive'],
        'lastFiredAt': !exists(json, 'lastFiredAt') ? undefined : json['lastFiredAt'],
    };
}

export function ListCbxDisbursementRulesItemToJSON(value?: ListCbxDisbursementRulesItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'thresholdBaseUnits': value.thresholdBaseUnits,
        'distributeBps': value.distributeBps,
        'checkCadenceHours': value.checkCadenceHours,
        'requireCoverageBps': value.requireCoverageBps,
        'metric': value.metric,
        'lookbackDays': value.lookbackDays,
        'maxRecipients': value.maxRecipients,
        'isActive': value.isActive,
        'lastFiredAt': value.lastFiredAt,
    };
}

