/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListReturnsItem
 */
export interface ListReturnsItem {
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof ListReturnsItem
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    reason?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListReturnsItem
     */
    requestedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    orderId: string;
    /**
     * 
     * @type {Date}
     * @memberof ListReturnsItem
     */
    receivedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    refundAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    restockedToInventoryItemId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ListReturnsItem
     */
    inspectedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    inspectedUnitId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    inspectedIdentifier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListReturnsItem
     */
    identityCheck: string;
    /**
     * 
     * @type {Date}
     * @memberof ListReturnsItem
     */
    restockedAt?: Date | null;
}

export function ListReturnsItemFromJSON(json: any): ListReturnsItem {
    return ListReturnsItemFromJSONTyped(json, false);
}

export function ListReturnsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListReturnsItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['createdAt'])),
        'userId': json['userId'],
        'notes': !exists(json, 'notes') ? undefined : json['notes'],
        'status': json['status'],
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
        'requestedAt': (new Date(json['requestedAt'])),
        'orderId': json['orderId'],
        'receivedAt': !exists(json, 'receivedAt') ? undefined : (json['receivedAt'] === null ? null : new Date(json['receivedAt'])),
        'refundAmount': !exists(json, 'refundAmount') ? undefined : json['refundAmount'],
        'restockedToInventoryItemId': !exists(json, 'restockedToInventoryItemId') ? undefined : json['restockedToInventoryItemId'],
        'inspectedAt': !exists(json, 'inspectedAt') ? undefined : (json['inspectedAt'] === null ? null : new Date(json['inspectedAt'])),
        'inspectedUnitId': !exists(json, 'inspectedUnitId') ? undefined : json['inspectedUnitId'],
        'inspectedIdentifier': !exists(json, 'inspectedIdentifier') ? undefined : json['inspectedIdentifier'],
        'identityCheck': json['identityCheck'],
        'restockedAt': !exists(json, 'restockedAt') ? undefined : (json['restockedAt'] === null ? null : new Date(json['restockedAt'])),
    };
}

export function ListReturnsItemToJSON(value?: ListReturnsItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': (value.createdAt.toISOString()),
        'userId': value.userId,
        'notes': value.notes,
        'status': value.status,
        'reason': value.reason,
        'requestedAt': (value.requestedAt.toISOString()),
        'orderId': value.orderId,
        'receivedAt': value.receivedAt === undefined ? undefined : (value.receivedAt === null ? null : value.receivedAt.toISOString()),
        'refundAmount': value.refundAmount,
        'restockedToInventoryItemId': value.restockedToInventoryItemId,
        'inspectedAt': value.inspectedAt === undefined ? undefined : (value.inspectedAt === null ? null : value.inspectedAt.toISOString()),
        'inspectedUnitId': value.inspectedUnitId,
        'inspectedIdentifier': value.inspectedIdentifier,
        'identityCheck': value.identityCheck,
        'restockedAt': value.restockedAt === undefined ? undefined : (value.restockedAt === null ? null : value.restockedAt.toISOString()),
    };
}

