/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Seller API
 * The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAutomationRuleResponse
 */
export interface UpdateAutomationRuleResponse {
    /**
     * 
     * @type {object}
     * @memberof UpdateAutomationRuleResponse
     */
    rule?: object | null;
}

export function UpdateAutomationRuleResponseFromJSON(json: any): UpdateAutomationRuleResponse {
    return UpdateAutomationRuleResponseFromJSONTyped(json, false);
}

export function UpdateAutomationRuleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAutomationRuleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rule': !exists(json, 'rule') ? undefined : json['rule'],
    };
}

export function UpdateAutomationRuleResponseToJSON(value?: UpdateAutomationRuleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rule': value.rule,
    };
}

