/* tslint:disable */
/* eslint-disable */
/**
 * Crossly Buyer API
 * The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateBuyerActivityResponse,
    CreateBuyerActivityResponseFromJSON,
    CreateBuyerActivityResponseToJSON,
    CreateBuyerCartItemResponse,
    CreateBuyerCartItemResponseFromJSON,
    CreateBuyerCartItemResponseToJSON,
    CreateBuyerCartQuoteResponse,
    CreateBuyerCartQuoteResponseFromJSON,
    CreateBuyerCartQuoteResponseToJSON,
    CreateBuyerOfferResponse,
    CreateBuyerOfferResponseFromJSON,
    CreateBuyerOfferResponseToJSON,
    CreateBuyerWishlistItemResponse,
    CreateBuyerWishlistItemResponseFromJSON,
    CreateBuyerWishlistItemResponseToJSON,
    CreateBuyerWishlistResponse,
    CreateBuyerWishlistResponseFromJSON,
    CreateBuyerWishlistResponseToJSON,
    GetBuyerPreferenceResponse,
    GetBuyerPreferenceResponseFromJSON,
    GetBuyerPreferenceResponseToJSON,
    GetBuyerProfileResponse,
    GetBuyerProfileResponseFromJSON,
    GetBuyerProfileResponseToJSON,
    InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    InlineObject2,
    InlineObject2FromJSON,
    InlineObject2ToJSON,
    InlineObject3,
    InlineObject3FromJSON,
    InlineObject3ToJSON,
    InlineObject4,
    InlineObject4FromJSON,
    InlineObject4ToJSON,
    V1List,
    V1ListFromJSON,
    V1ListToJSON,
} from '../models';

export interface CreateBuyerActivityRequest {
    inlineObject4: InlineObject4;
}

export interface CreateBuyerCartItemRequest {
    inlineObject2: InlineObject2;
}

export interface CreateBuyerOfferRequest {
    inlineObject3: InlineObject3;
}

export interface CreateBuyerWishlistRequest {
    inlineObject: InlineObject;
}

export interface CreateBuyerWishlistItemRequest {
    id: string;
    inlineObject1: InlineObject1;
}

export interface DeleteBuyerCartItemRequest {
    id: string;
}

export interface ListBuyerCashbackRequest {
    status?: ListBuyerCashbackStatusEnum;
    page?: number;
    limit?: number;
}

export interface ListBuyerOrdersRequest {
    page?: number;
    limit?: number;
}

export interface ListBuyerWishlistItemsRequest {
    id: string;
}

/**
 * 
 */
export class BuyerApi extends runtime.BaseAPI {

    /**
     * Records the look and returns whether Crossly has the item and at what price. Send an identifier and a store DOMAIN — a full URL is refused. Nothing about the page itself is stored.
     * Report an item your user is looking at, and get our answer.
     */
    async createBuyerActivityRaw(requestParameters: CreateBuyerActivityRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateBuyerActivityResponse>> {
        if (requestParameters.inlineObject4 === null || requestParameters.inlineObject4 === undefined) {
            throw new runtime.RequiredError('inlineObject4','Required parameter requestParameters.inlineObject4 was null or undefined when calling createBuyerActivity.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/activity`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject4ToJSON(requestParameters.inlineObject4),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBuyerActivityResponseFromJSON(jsonValue));
    }

    /**
     * Records the look and returns whether Crossly has the item and at what price. Send an identifier and a store DOMAIN — a full URL is refused. Nothing about the page itself is stored.
     * Report an item your user is looking at, and get our answer.
     */
    async createBuyerActivity(requestParameters: CreateBuyerActivityRequest, initOverrides?: RequestInit): Promise<CreateBuyerActivityResponse> {
        const response = await this.createBuyerActivityRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a listing to your cart.
     */
    async createBuyerCartItemRaw(requestParameters: CreateBuyerCartItemRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateBuyerCartItemResponse>> {
        if (requestParameters.inlineObject2 === null || requestParameters.inlineObject2 === undefined) {
            throw new runtime.RequiredError('inlineObject2','Required parameter requestParameters.inlineObject2 was null or undefined when calling createBuyerCartItem.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/cart/items`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject2ToJSON(requestParameters.inlineObject2),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBuyerCartItemResponseFromJSON(jsonValue));
    }

    /**
     * Add a listing to your cart.
     */
    async createBuyerCartItem(requestParameters: CreateBuyerCartItemRequest, initOverrides?: RequestInit): Promise<CreateBuyerCartItemResponse> {
        const response = await this.createBuyerCartItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Runs the real checkout cascade and returns the totals instead of charging. Nothing is purchased. `taxComplete: false` means there is no saved delivery address, so the total is a floor rather than a final figure.
     * Price the cart, delivered — item, shipping, tax, total.
     */
    async createBuyerCartQuoteRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateBuyerCartQuoteResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/cart/quote`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBuyerCartQuoteResponseFromJSON(jsonValue));
    }

    /**
     * Runs the real checkout cascade and returns the totals instead of charging. Nothing is purchased. `taxComplete: false` means there is no saved delivery address, so the total is a floor rather than a final figure.
     * Price the cart, delivered — item, shipping, tax, total.
     */
    async createBuyerCartQuote(initOverrides?: RequestInit): Promise<CreateBuyerCartQuoteResponse> {
        const response = await this.createBuyerCartQuoteRaw(initOverrides);
        return await response.value();
    }

    /**
     * Sends an offer to the seller. Spends nothing — a seller accepting still leaves you to complete checkout. Offers at or above the asking price are refused; buy it instead.
     * Offer a price on a listing.
     */
    async createBuyerOfferRaw(requestParameters: CreateBuyerOfferRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateBuyerOfferResponse>> {
        if (requestParameters.inlineObject3 === null || requestParameters.inlineObject3 === undefined) {
            throw new runtime.RequiredError('inlineObject3','Required parameter requestParameters.inlineObject3 was null or undefined when calling createBuyerOffer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/offers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject3ToJSON(requestParameters.inlineObject3),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBuyerOfferResponseFromJSON(jsonValue));
    }

    /**
     * Sends an offer to the seller. Spends nothing — a seller accepting still leaves you to complete checkout. Offers at or above the asking price are refused; buy it instead.
     * Offer a price on a listing.
     */
    async createBuyerOffer(requestParameters: CreateBuyerOfferRequest, initOverrides?: RequestInit): Promise<CreateBuyerOfferResponse> {
        const response = await this.createBuyerOfferRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a wishlist.
     */
    async createBuyerWishlistRaw(requestParameters: CreateBuyerWishlistRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateBuyerWishlistResponse>> {
        if (requestParameters.inlineObject === null || requestParameters.inlineObject === undefined) {
            throw new runtime.RequiredError('inlineObject','Required parameter requestParameters.inlineObject was null or undefined when calling createBuyerWishlist.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/wishlists`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObjectToJSON(requestParameters.inlineObject),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBuyerWishlistResponseFromJSON(jsonValue));
    }

    /**
     * Create a wishlist.
     */
    async createBuyerWishlist(requestParameters: CreateBuyerWishlistRequest, initOverrides?: RequestInit): Promise<CreateBuyerWishlistResponse> {
        const response = await this.createBuyerWishlistRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a listing to a wishlist.
     */
    async createBuyerWishlistItemRaw(requestParameters: CreateBuyerWishlistItemRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CreateBuyerWishlistItemResponse>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling createBuyerWishlistItem.');
        }

        if (requestParameters.inlineObject1 === null || requestParameters.inlineObject1 === undefined) {
            throw new runtime.RequiredError('inlineObject1','Required parameter requestParameters.inlineObject1 was null or undefined when calling createBuyerWishlistItem.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/wishlists/{id}/items`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InlineObject1ToJSON(requestParameters.inlineObject1),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateBuyerWishlistItemResponseFromJSON(jsonValue));
    }

    /**
     * Add a listing to a wishlist.
     */
    async createBuyerWishlistItem(requestParameters: CreateBuyerWishlistItemRequest, initOverrides?: RequestInit): Promise<CreateBuyerWishlistItemResponse> {
        const response = await this.createBuyerWishlistItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a line from your cart.
     */
    async deleteBuyerCartItemRaw(requestParameters: DeleteBuyerCartItemRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteBuyerCartItem.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/cart/items/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Remove a line from your cart.
     */
    async deleteBuyerCartItem(requestParameters: DeleteBuyerCartItemRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteBuyerCartItemRaw(requestParameters, initOverrides);
    }

    /**
     * Derived, never declared — there is no preferences form anywhere. `matchRate` is the share of this person\'s searches Crossly could answer; a low number is an inventory problem, not a personalisation one, which is why it is here.
     * The shopping profile derived from that activity.
     */
    async getBuyerPreferenceRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetBuyerPreferenceResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/preferences`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBuyerPreferenceResponseFromJSON(jsonValue));
    }

    /**
     * Derived, never declared — there is no preferences form anywhere. `matchRate` is the share of this person\'s searches Crossly could answer; a low number is an inventory problem, not a personalisation one, which is why it is here.
     * The shopping profile derived from that activity.
     */
    async getBuyerPreference(initOverrides?: RequestInit): Promise<GetBuyerPreferenceResponse> {
        const response = await this.getBuyerPreferenceRaw(initOverrides);
        return await response.value();
    }

    /**
     * Your Crossly shopping profile — name, email, saved address, Bucks balance.
     */
    async getBuyerProfileRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<GetBuyerProfileResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/profile`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBuyerProfileResponseFromJSON(jsonValue));
    }

    /**
     * Your Crossly shopping profile — name, email, saved address, Bucks balance.
     */
    async getBuyerProfile(initOverrides?: RequestInit): Promise<GetBuyerProfileResponse> {
        const response = await this.getBuyerProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     * Newest first, and only as far back as the retention window — the link between a person and a comparison is dropped after 180 days, so this thins out rather than growing forever.
     * What this buyer has compared lately.
     */
    async listBuyerActivityRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/activity`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * Newest first, and only as far back as the retention window — the link between a person and a comparison is dropped after 180 days, so this thins out rather than growing forever.
     * What this buyer has compared lately.
     */
    async listBuyerActivity(initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listBuyerActivityRaw(initOverrides);
        return await response.value();
    }

    /**
     * Line items with the price captured when each was added. This is NOT a quote — shipping, tax and any discounts are computed at checkout against a delivery address, and the sum of these lines is not what you will be charged.
     * What is in your Crossly cart.
     */
    async listBuyerCartRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/cart`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * Line items with the price captured when each was added. This is NOT a quote — shipping, tax and any discounts are computed at checkout against a delivery address, and the sum of these lines is not what you will be charged.
     * What is in your Crossly cart.
     */
    async listBuyerCart(initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listBuyerCartRaw(initOverrides);
        return await response.value();
    }

    /**
     * Newest first. `pending` means an order was reported and the retailer\'s return window has not closed; nothing is paid until it does. `expired` means a click was never reported as converting, which is the ordinary outcome for most clicks.
     * Your Scout cashback — pending, confirmed, paid.
     */
    async listBuyerCashbackRaw(requestParameters: ListBuyerCashbackRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        const queryParameters: any = {};

        if (requestParameters.status !== undefined) {
            queryParameters['status'] = requestParameters.status;
        }

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/cashback`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * Newest first. `pending` means an order was reported and the retailer\'s return window has not closed; nothing is paid until it does. `expired` means a click was never reported as converting, which is the ordinary outcome for most clicks.
     * Your Scout cashback — pending, confirmed, paid.
     */
    async listBuyerCashback(requestParameters: ListBuyerCashbackRequest = {}, initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listBuyerCashbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * What you have bought on Crossly, newest first.
     */
    async listBuyerOrdersRaw(requestParameters: ListBuyerOrdersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        const queryParameters: any = {};

        if (requestParameters.page !== undefined) {
            queryParameters['page'] = requestParameters.page;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters['limit'] = requestParameters.limit;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/orders`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * What you have bought on Crossly, newest first.
     */
    async listBuyerOrders(requestParameters: ListBuyerOrdersRequest = {}, initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listBuyerOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * What is on one wishlist.
     */
    async listBuyerWishlistItemsRaw(requestParameters: ListBuyerWishlistItemsRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling listBuyerWishlistItems.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/wishlists/{id}/items`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * What is on one wishlist.
     */
    async listBuyerWishlistItems(requestParameters: ListBuyerWishlistItemsRequest, initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listBuyerWishlistItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Your wishlists.
     */
    async listBuyerWishlistsRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<V1List & object>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("BuyerOAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/v1/buyer/wishlists`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V1List &amp; objectFromJSON(jsonValue));
    }

    /**
     * Your wishlists.
     */
    async listBuyerWishlists(initOverrides?: RequestInit): Promise<V1List & object> {
        const response = await this.listBuyerWishlistsRaw(initOverrides);
        return await response.value();
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ListBuyerCashbackStatusEnum {
    Pending = 'pending',
    Confirmed = 'confirmed',
    Rejected = 'rejected',
    Paid = 'paid',
    Expired = 'expired'
}
